### PR TITLE
LPS-105754 The logic for VerifyPermissions needs to be run with a new…

### PR DESCRIPTION
**Pull request by SamZiemer**
… database and after an upgrade, moved that logic to a better place.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/samziemer/liferay-portal/pull/706. [See changes here.](https://github.com/achaparro/liferay-portal/compare/c5c4f658269c~1...c5c4f658269c)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/samziemer/liferay-portal/pull/707. [See changes here.](https://github.com/achaparro/liferay-portal/compare/a179ed5ceb8d~2...a179ed5ceb8d)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82079. [See changes here.](https://github.com/achaparro/liferay-portal/compare/645e33845924~3...645e33845924)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82154. [See changes here.](https://github.com/achaparro/liferay-portal/compare/bee1fb1ec2fc~3...bee1fb1ec2fc)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/399. [See changes here.](https://github.com/achaparro/liferay-portal/compare/1a94207e303b~4...1a94207e303b)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/402. [See changes here.](https://github.com/achaparro/liferay-portal/compare/fb8e6db5ddcf~4...fb8e6db5ddcf)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82239. [See changes here.](https://github.com/achaparro/liferay-portal/compare/31b821db5060~4...31b821db5060)

**Pull request closed without merging**
