### PR TITLE
LPS-115694 Add groupId to the GroupThreadLocal and use it to ensure w…

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-115694

Use the GroupThreadLocal to make sure we are checking the correct group for team roles.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/621. [See changes here.](https://github.com/achaparro/liferay-portal/compare/3c242745c579~3...3c242745c579)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/csierra/liferay-portal/pull/746. [See changes here.](https://github.com/achaparro/liferay-portal/compare/8ffb038b91fa~3...8ffb038b91fa)

**Pull request closed without merging**
