### PR TITLE
LPS-118989 Fix ORA-01795: maximum number of expressions in a list is 1000

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi Alberto,

I am sending the modified PR your requested [here](https://github.com/achaparro/liferay-portal/pull/702#issuecomment-693333322). I hope

I didn't move the runSQL anywhere, because I think it is logically at the right place. 

If you have any concerns, just let me know or feel free to apply the changes.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hi @istvansajtos,

Thank you! I will review it right now.

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/707. [See changes here.](https://github.com/achaparro/liferay-portal/compare/e84eecf5b942~3...e84eecf5b942)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/708. [See changes here.](https://github.com/achaparro/liferay-portal/compare/f329f46d2d71~3...f329f46d2d71)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/709. [See changes here.](https://github.com/achaparro/liferay-portal/compare/05607c8ea76e~3...05607c8ea76e)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/710. [See changes here.](https://github.com/achaparro/liferay-portal/compare/2f7ee7477053~2...2f7ee7477053)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/713. [See changes here.](https://github.com/achaparro/liferay-portal/compare/ea7bb0386ee0~2...ea7bb0386ee0)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/714. [See changes here.](https://github.com/achaparro/liferay-portal/compare/ea7bb0386ee0~2...ea7bb0386ee0)

**Pull request closed without merging**
