### PR TITLE
LPS-87396 Reorder the upgrades in order to allow backport the UpgradeDLFileShortcut

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65206. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
