### PR TITLE
LPS-143830 Upgrade does not properly handle partitioned databases

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://issues.liferay.com/browse/LPS-143830>

__Notes:__
The issue is that `CompanyThreadLocal` is prematurely locked before the portal upgrade processes are run on the companies. This is happening because `PortalUpgradeProcess` itself is a `UpgradeProcess`, meaning `PortalUpgradeProcess` is run on each company via `DBPartitionUtil.forEachCompanyId()`, which locks `CompanyThreadLocal` before executing the upgrade subprocesses within it. See the following code:

- [UpgradeProcess.java#L109-L123](https://github.com/liferay/liferay-portal/blob/7.4.3.8-ga8/portal-kernel/src/com/liferay/portal/kernel/upgrade/UpgradeProcess.java#L109-L123)
- [BaseDBProcess.java#L244](https://github.com/liferay/liferay-portal/blob/7.4.3.8-ga8/portal-kernel/src/com/liferay/portal/kernel/dao/db/BaseDBProcess.java#L244)
- [BaseDB.java#L308](https://github.com/liferay/liferay-portal/blob/7.4.3.8-ga8/portal-impl/src/com/liferay/portal/dao/db/BaseDB.java#L308)
- [DBPartitionUtil.java#L118-L130](https://github.com/liferay/liferay-portal/blob/7.4.3.8-ga8/portal-impl/src/com/liferay/portal/db/partition/DBPartitionUtil.java#L118-L130)

We only need to execute the **upgrade processes in** `PortalUpgradeProcess` on each company. `PortalUpgradeProcess` only needs to be run once. We can achieve this by overriding `UpgradeProcess.upgrade()`. `PortalUpgradeProcess` should be the only exception where this overriding is necessary. Let me know if you have any questions/thoughts.

Thank you!

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
