### PR TITLE
LPS-80165

### PR DESCRIPTION
**Pull request by jonathanmccann**
I put it in the v7_0_0 upgrade process since LPS-65314 was aimed at the upgrade from 6.2 to 7.0. Please let me know if you'd rather put it elsewhere though.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57846. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57849. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57851. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
