### PR TITLE
LPS-96014 Update schema version

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hey @ealonso,

I will send the pull Tuesday morning maximum. We have created a new framework for these cases and I need to adapt it a bit to use it here.

Tomorrow (Monday) is holidays in LA so don't worry, it will be committed for the release.

Is that ok?

Thanks!

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73820. [See changes here.](https://github.com/achaparro/liferay-portal/compare/c2b70755c096~5...c2b70755c096)

**Pull request closed without merging**
