### PR TITLE
Lps 106083

### PR DESCRIPTION
**Pull request by SamZiemer**
We no longer need VerifyAuditedModel as LayoutFriendlyURLAutidedModel was the last class using it, and the bug was only reproducible from 6.1 and below. https://issues.liferay.com/browse/LPS-44035 introduced LayoutFriendlyURLAuditedModel

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
@SamZiemer It seems that there is a semver error, can you fix it?

Thx

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by SamZiemer** [comment]
I've updated the version, hopefully these next tests will pass.

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82320.

**Pull request closed without merging**
