### PR TITLE
[TECHNICAL-SUPPORT] LPS-96987

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @achaparro,

I have tested this in Mysql and Oracle, I do not currently have a SQL Server or DB2 to test with though. I believe this should work across both of those as well.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2434. [See changes here.](https://github.com/achaparro/liferay-portal/compare/4c992accad8f~2...4c992accad8f)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2435. [See changes here.](https://github.com/achaparro/liferay-portal/compare/354e41c58052~2...354e41c58052)

**Pull request closed without merging**
