### PR TITLE
LPS-112063 Add deletion of old data after upgrading discussion subscr…

### PR DESCRIPTION
**Pull request by SamZiemer**
Journal and Wiki both need to delete old subscriptions after upgrading.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/826. [See changes here.](https://github.com/achaparro/liferay-portal/compare/c3f1c9f7d0ec~1...c3f1c9f7d0ec)

**Pull request closed without merging**
