### PR TITLE
LPS-139342 Processing company IDs can be parallelized

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://issues.liferay.com/browse/LPS-139342>

__Notes:__
Previous pull request: <https://github.com/achaparro/liferay-portal/pull/1027>

I added the new test case that you suggested in the previous pull request. Let me know if I missed anything. I think the current companies used for the integration tests (the default one and the test company) should suffice for testing.

Let me know if you have any questions/thoughts.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@vicnate5 @kyle-miho do you think the errors are  related?

Thanks

**Comment by kyle-miho** [comment]
looking into this

**Comment by kyle-miho** [comment]
should also check the upgrade suite since this pr is changing how upgrades work, i will check this tomorrow morning when the ci:test:upgrade finishes

**Comment by kyle-miho** [comment]
ci:test:upgrade

**Comment by kyle-miho** [comment]
@achaparro pr should be good to go

**Comment by achaparro** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/113627

**Pull request closed without merging**
