### PR TITLE
LPS-161695 SF rule to initialize the Release for web modules

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-161695

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
@achaparro see [88829c1](https://github.com/achaparro/liferay-portal/pull/1039/commits/88829c16eb2685ba73228d114bcac59fc6951804)

**Comment by achaparro** [comment]
@ling-alan-huang @qz1010 sorry for the delay, checking it now

**Comment by achaparro** [comment]
Good job guys! See some minor changes:
https://github.com/ling-alan-huang/liferay-portal/pull/1451

**Pull request closed without merging**
