### PR TITLE
LPS-100925 Revert LPS-96209 and LPS-99992 in favor of implementing LPS-100542. Leave the dummy upgrade steps so that the versions are still in sync.

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @dacousalr

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77955.

**Pull request closed without merging**
