### PR TITLE
LPS-114083 Ensure we have unique names before inserting into LayoutPa…

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-114083

This change reflects a similar, but slightly different logic we have when adding [friendlyURLs for layouts](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/exportimport/data/handler/LayoutFriendlyURLStagedModelDataHandler.java#L173-L206).

Some questions I still have regarding this fix, however.

1. The name for LayoutPageTemplateEntry is pulled from LayoutPrototypes, if we update the name for the LayoutPageTemplateEntry, should we also update the LayoutPrototypes to the same name (including adding the number to the name for each locale)?
2. The index that requires unique was added in https://issues.liferay.com/browse/LPS-85497 but I do not see any specific reasons it needs to be unique. Another route for fixing would be to remove unique from the index.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/236. [See changes here.](https://github.com/achaparro/liferay-portal/compare/6d2968a7eb89~2...6d2968a7eb89)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/237. [See changes here.](https://github.com/achaparro/liferay-portal/compare/62870e3541e0~2...62870e3541e0)

**Comment by achaparro** [comment]
Hey @SamZiemer,

First of all, thank you for fixing this, the LPP is already solved but this is important for future customer.

You have really good questions here:
1. The name for LayoutPageTemplateEntry is pulled from LayoutPrototypes, if we update the name for the LayoutPageTemplateEntry, should we also update the LayoutPrototypes to the same name (including adding the number to the name for each locale)?
2. The index that requires unique was added in https://issues.liferay.com/browse/LPS-85497 but I do not see any specific reasons it needs to be unique. Another route for fixing would be to remove unique from the index.

For the question 2, I think the index makes sense because of this finder:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-page-template-service/service.xml#L144

Maybe you can't see because anytime an index is modified, its name changes, this one changed after adding the type field, but it's the same as this one:
create unique index IX_C3960EB1 on LayoutPageTemplateEntry (groupId, name[$COLUMN_LENGTH:75$], type_);

For the question 1, that's really important and after some testing, I realized that even solving the upgrade we will have the same issue for new prototypes. I forwarded the pull and the Product Team should make a decision about it because I think that's another issue.

Thanks.

**Pull request closed without merging**
