### PR TITLE
LPS-97178 Fix query

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @achaparro ,

Can you review this pull request, please?

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78093.

**Pull request closed without merging**
