### PR TITLE
LPS-128860 Upgrade Report

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @Samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2281. [See changes here.](https://github.com/achaparro/liferay-portal/compare/694ee3c0012b~4...694ee3c0012b)

**Pull request closed without merging**
