### PR TITLE
LPS-106297 Disabled text field validation is enabled

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-106297

**Issue:**
Text field validation for disabled fields is validated and results in a form that cannot be submitted.

**Solution:**
These changes pertain to disabled fields. Form submission will not be prevented from a field validation error if the field is disabled/`readOnly`. 

Before validating the field, it checks if the field is a `readOnly` field. If it is, then that means the field is disabled and would not need to be validated. Otherwise, if the field is not a `readOnly` field, it would be validated per usual.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/645.

**Pull request closed without merging**
