### PR TITLE
Lps 137162

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-137162

I was able to use the persistence manager to get the configurations. You changes made sense, thank you for those.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:stop

**Comment by achaparro** [comment]
See https://github.com/achaparro/liferay-portal/pull/987

**Pull request closed without merging**
