### PR TITLE
Lps 126917 master

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @achaparro,

This is the issue we discussed earlier today. I had to move the upgradePortletId to the 1.1.0 -> 1.2.0 upgrade step because when the kaleo plugins were converted to modules from 6.2 the build number is used to generate the schema version, in this case the schema version starts at 1.1.0

In addition, the fix cannot be verified through the UI in master because [LPS-112055](https://issues.liferay.com/browse/LPS-112055) changed how the permission checking logic works which now throws an error with these permissions. However I can confirm the fix works in 7.2 and the names are correct in the database.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hey @SamZiemer,

The changes look good but I would like to talk to you first about this:
_In addition, the fix cannot be verified through the UI in master because LPS-112055 changed how the permission checking logic works which now throws an error with these permissions. However I can confirm the fix works in 7.2 and the names are correct in the database._

Can we talk about that at 10AM LA time?

Thanks!

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
