### PR TITLE
LPS-101351

### PR DESCRIPTION
**Pull request by jcampoy**
cc/ @pavel-savinov

### CODE REVIEW

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @jcampoy and @pavel-savinov,

I have been testing the pull and it seems that it doesn't cover upgrades from 7.2 GA1 to master. These are the steps:

1. Startup 7.2 GA1
2. Create a display page template (the field Layout.privateLayout is set to true)
3. Upgrade to master

Since the schema version for the display-asset-service is 2.1.1 7.2 GA1 this upgrade https://github.com/achaparro/liferay-portal/blob/316c16bfd66135f8525dddd6c11bf7187174e471/modules/apps/asset/asset-display-page-service/src/main/java/com/liferay/asset/display/page/internal/upgrade/AssetDisplayPageServiceUpgrade.java#L55 doesn't run and we only change LayoutFriendlyURLRecords here: https://github.com/achaparro/liferay-portal/blob/316c16bfd66135f8525dddd6c11bf7187174e471/modules/apps/asset/asset-display-page-service/src/main/java/com/liferay/asset/display/page/internal/upgrade/AssetDisplayPageServiceUpgrade.java#L71

Is my assumption correct?

If so, we should move the whole upgrade to the step 2.2.2 to cover all use cases. It seems that the upgrade was released before the fix for the creation of new pages so we are not sure if customers in SP1 have all objects fixed.

Let me know what you think.

Cheers!

**Comment by jcampoy** [comment]
Hi @achaparro , you are right, the best solutions should be to move the whole upgrade to 2.2.1, I will take a look today and send you the changes.

Cheers!

**Comment by jcampoy** [comment]
Just started reviewing :)

**Comment by jcampoy** [comment]
Hey @achaparro ,

after some new tests, this PR works fine, the key is that 7.2 GA1 (without FP1) has the 2.1.0 schema version for the `com.liferay.asset.display.page.service`

See the query for the original database of 7.2 GA1 that I created for my tests:

Screen Shot 2019-10-16 at 10 52 03

So, I think you can go ahead with this pull request and resend to Brian :)

Let me know if you have any question.

Cheers!
Jose

**Comment by achaparro** [comment]
Umm, I think you are right, I have 2.1.1 in my tests because I used an upgraded database from 7.1 to 7.2 fix pack 1 and then uninstalled the fix pack.

I will send the pull to Brian.

Thanks @jcampoy !

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79654. [See changes here.](https://github.com/achaparro/liferay-portal/compare/1523cedae7a4~1...1523cedae7a4)

**Pull request closed without merging**
