### PR TITLE
Lps 107149

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by achaparro** [comment]
@SamZiemer, there is an error in this point:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/exportimport/data/handler/FileEntryStagedModelDataHandler.java#L888

More info here:
https://testray.liferay.com/reports/production/logs/test-1-9/1579548738141/test-portal-acceptance-pullrequest(master)/2666/functional-smoke-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz

it seems that, somehow that method check if the verify processes were completed. I think you could try to reproduce the issue just executing `dm wtf` in the gogo console after starting up the server.

Since probably we are going to get more errors like these, I think it's a better approach to send the pull to your repo first to test it there and once all the errors are solved, send it to me for a further review.

Thanks.

**Comment by achaparro** [comment]
ci:test:stable

**Comment by achaparro** [comment]
ci:test:upgrade

**Pull request closed without merging**
