### PR TITLE
LPS-77945

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
For more information, see: https://issues.liferay.com/browse/LPS-77945

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55424. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
