### PR TITLE
Lps 116119 master

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @achaparro,

I've updated the pull with your suggestions and added tests.

### CODE REVIEW

**Comment by achaparro** [comment]
Thanks @SamZiemer, it looks good now. Let's execute the tests before sending them

**Comment by achaparro** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
I proceed to close this pull request waiting for fixing the issues we found. @SamZiemer

**Pull request closed without merging**
