### PR TITLE
LPS-117123 SF

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
resent here: https://github.com/achaparro/liferay-portal/pull/720

**Comment by SamZiemer** [comment]
ci:close

**Pull request closed without merging**
