### PR TITLE
LPS-135081 Apply SF rule

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by vicnate5** [comment]
@achaparro I fetched this PR and tested it with the database dumps from https://issues.liferay.com/browse/LPS-135818.

I am still unable to run the upgrade against a partitioned database
```
ERROR [main][BasePersistenceImpl:628] Caught unexpected exception
java.lang.UnsupportedOperationException: CompanyThreadLocal modification is not allowed
        at com.liferay.portal.kernel.security.auth.CompanyThreadLocal._setCompanyId(CompanyThreadLocal.java:198) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.security.auth.CompanyThreadLocal.setWithSafeCloseable(CompanyThreadLocal.java:134) ~[portal-kernel.jar:?]
        at com.liferay.portal.service.persistence.impl.CompanyPersistenceImpl.cacheResult(CompanyPersistenceImpl.java:1287) ~[portal-impl.jar:?]
        at com.liferay.portal.service.persistence.impl.CompanyPersistenceImpl.findBySystem(CompanyPersistenceImpl.java:897) ~[portal-impl.jar:?]
        at com.liferay.portal.service.persistence.impl.CompanyPersistenceImpl.findBySystem(CompanyPersistenceImpl.java:803) ~[portal-impl.jar:?]
        at com.liferay.portal.service.persistence.impl.CompanyPersistenceImpl.findBySystem(CompanyPersistenceImpl.java:765) ~[portal-impl.jar:?]
        at com.liferay.portal.service.impl.CompanyLocalServiceImpl.getCompanies(CompanyLocalServiceImpl.java:536) ~[portal-impl.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
        at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
        at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:80) ~[?:?]
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
        at com.sun.proxy.$Proxy136.getCompanies(Unknown Source) ~[?:?]
        at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:494) ~[portal-impl.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
        at com.sun.proxy.$Proxy136.forEachCompanyId(Unknown Source) ~[?:?]
        at com.liferay.portal.kernel.service.CompanyLocalServiceUtil.forEachCompanyId(CompanyLocalServiceUtil.java:356) ~[portal-kernel.jar:?]
        at com.liferay.portal.verify.VerifyResourcePermissions.verify(VerifyResourcePermissions.java:56) ~[portal-impl.jar:?]
        at com.liferay.portal.verify.VerifyResourcePermissions.doVerify(VerifyResourcePermissions.java:89) ~[portal-impl.jar:?]
        at com.liferay.portal.verify.VerifyProcess.lambda$verify$0(VerifyProcess.java:81) ~[portal-impl.jar:?]
        at com.liferay.portal.db.partition.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:119) [portal-impl.jar:?]
        at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:307) [portal-impl.jar:?]
        at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:228) [portal-kernel.jar:?]
        at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:68) [portal-impl.jar:?]
        at com.liferay.portal.tools.DBUpgrader.verify(DBUpgrader.java:191) [portal-impl.jar:?]
        at com.liferay.portal.tools.DBUpgrader._upgradePortal(DBUpgrader.java:433) [portal-impl.jar:?]
        at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:170) [portal-impl.jar:?]
        at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:162) [portal-impl.jar:?]
        at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:136) [portal-impl.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
        at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54) [com.liferay.portal.tools.db.upgrade.client.jar:?]
2021-07-16 21:38:50.905 INFO  [main][VerifyProcess:91] Completed verification process com.liferay.portal.verify.VerifyResourcePermissions in 33 ms
com.liferay.portal.verify.VerifyException: com.liferay.portal.kernel.exception.SystemException: java.lang.UnsupportedOperationException: CompanyThreadLocal modification is not allowed
        at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:85)
        at com.liferay.portal.tools.DBUpgrader.verify(DBUpgrader.java:191)
        at com.liferay.portal.tools.DBUpgrader._upgradePortal(DBUpgrader.java:433)
        at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:170)
        at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:162)
        at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:136)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54)
Caused by: com.liferay.portal.kernel.exception.SystemException: java.lang.UnsupportedOperationException: CompanyThreadLocal modification is not allowed
        at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:634)
        at com.liferay.portal.service.persistence.impl.CompanyPersistenceImpl.findBySystem(CompanyPersistenceImpl.java:904)
        at com.liferay.portal.service.persistence.impl.CompanyPersistenceImpl.findBySystem(CompanyPersistenceImpl.java:803)
        at com.liferay.portal.service.persistence.impl.CompanyPersistenceImpl.findBySystem(CompanyPersistenceImpl.java:765)
        at com.liferay.portal.service.impl.CompanyLocalServiceImpl.getCompanies(CompanyLocalServiceImpl.java:536)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
        at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
        at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:80)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
        at com.sun.proxy.$Proxy136.getCompanies(Unknown Source)
        at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:494)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
        at com.sun.proxy.$Proxy136.forEachCompanyId(Unknown Source)
        at com.liferay.portal.kernel.service.CompanyLocalServiceUtil.forEachCompanyId(CompanyLocalServiceUtil.java:356)
        at com.liferay.portal.verify.VerifyResourcePermissions.verify(VerifyResourcePermissions.java:56)
        at com.liferay.portal.verify.VerifyResourcePermissions.doVerify(VerifyResourcePermissions.java:89)
        at com.liferay.portal.verify.VerifyProcess.lambda$verify$0(VerifyProcess.java:81)
        at com.liferay.portal.db.partition.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:119)
        at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:307)
        at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:228)
        at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:68)
        ... 10 more
Caused by: java.lang.UnsupportedOperationException: CompanyThreadLocal modification is not allowed
        at com.liferay.portal.kernel.security.auth.CompanyThreadLocal._setCompanyId(CompanyThreadLocal.java:198)
        at com.liferay.portal.kernel.security.auth.CompanyThreadLocal.setWithSafeCloseable(CompanyThreadLocal.java:134)
        at com.liferay.portal.service.persistence.impl.CompanyPersistenceImpl.cacheResult(CompanyPersistenceImpl.java:1287)
        at com.lifera
```
Full log https://gist.githubusercontent.com/vicnate5/9459ec0c3d3226e614f338a6e68a1f93/raw/e38c89fd45bbc08d91e7d3381ad39a563ee0e7b5/gistfile1.txt

**Comment by achaparro** [comment]
Hi @vicnate5,

It should be fixed with this pull request:
https://github.com/achaparro/liferay-portal/pull/966

I tested locally with Liferay Online database and it worked.

**Pull request closed without merging**
