### PR TITLE
LPS-98387 add flatten to message boards

### PR DESCRIPTION
**Pull request by nhpatt**
El commit polémico es https://github.com/achaparro/liferay-portal/commit/69089b342bb744ecb80a1523ec9ceae793ef6968

Utilizo un do while porque queda infinitamente más legible, entiendo que tendría que añadir batch (en cada update?) y hay que renombrar alguna cosilla (dos ps2)

### CODE REVIEW

**Comment by nhpatt** [comment]
Cambiado a upgrade de 2.0.0 a 2.1.0, columna a String (como el resto de treePaths) y alterColumnAdd.

**Comment by nhpatt** [comment]
Actualizada PR :)

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/369. [See changes here.](https://github.com/achaparro/liferay-portal/compare/03fcd7e5800f~7...03fcd7e5800f)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/370. [See changes here.](https://github.com/achaparro/liferay-portal/compare/9786910798d5~7...9786910798d5)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/372. [See changes here.](https://github.com/achaparro/liferay-portal/compare/6e5e0f2a5260~10...6e5e0f2a5260)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/nhpatt/liferay-portal/pull/181. [See changes here.](https://github.com/achaparro/liferay-portal/compare/2d58b33c2df2~10...2d58b33c2df2)

**Pull request closed without merging**
