### PR TITLE
LPS-86461

### PR DESCRIPTION
**Pull request by yuhai**
Hi @achaparro,

The PR extends from https://github.com/dantewang/liferay-portal/pull/920. Could you please help review this? 

cc @dantewang

Thanks,
Hai

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai conflicts?

**Comment by yuhai** [comment]
@dantewang, sorry, I just rebase this and resolve the conflict. :)

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
si:test:relevant

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66109. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @yuhai @dantewang,

The revision of the pull took some time since I had to add more portlets and test them properly.

Best regards.

**Comment by yuhai** [comment]
Hi @achaparro,

Thanks for working on it. :)

I was on vacation last week. I came back to work at today and just sent one PR to solve the test error.
Please see https://github.com/achaparro/liferay-portal/pull/258

Best regards,
Hai

**Pull request closed without merging**
