### PR TITLE
LPS-138029 & LPS-138030

### PR DESCRIPTION
**Pull request by achaparro**
@samziemer @kevhlee

### CODE REVIEW

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:forward

**Comment by SamZiemer** [comment]
@vicnate5 can you check the failures on this pull request to see if it can be forwarded to Brian? I believe we have seen these tests fail before, but nothing here should be related to our changes in this PR.

**Comment by vicnate5** [comment]
@SamZiemer No related failures, this can be manually forwarded.

**Comment by SamZiemer** [comment]
Thanks @vicnate5,

I've forwarded the PR here: https://github.com/brianchandotcom/liferay-portal/pull/106859

**Comment by achaparro** [comment]
Thanks @SamZiemer !

**Pull request closed without merging**
