### PR TITLE
LPS-131851 (Part 2)

### PR DESCRIPTION
**Pull request by kevhlee**
**Ticket:**
<https://issues.liferay.com/browse/LPS-131851>

**Notes:**
Previous pull request: <https://github.com/achaparro/liferay-portal/pull/891>

As requested, using the trick you outlined involving `gw buildUpgradeTable`, I regenerated the upgrade table to remove the `ctCollectionId` field along with the `mvccVersion` field from the `StyleBookEntryVersion` upgrade table. Let me know if I made a mistake with regenerating the table or if I missed something.

cc: @SamZiemer

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/897. [See changes here.](https://github.com/achaparro/liferay-portal/compare/6a23ea25ca0e~1...6a23ea25ca0e)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/898. [See changes here.](https://github.com/achaparro/liferay-portal/compare/324d81ad65b8~2...324d81ad65b8)

**Pull request closed without merging**
