### PR TITLE
LPS-86288

### PR DESCRIPTION
**Pull request by jcampoy**
Here it is the upgrade for dates in SQLServer in the Web Experience modules. 

https://issues.liferay.com/browse/LPS-86288

/cc @ealonso

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
ci:test

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @jcampoy,

In the tests I see some errors in journalArticle comparasion, however it seems that we are trying to compare two different journalArticles, do you think can it be related to your changes? I don't think so, but please, let me know.

Thanks.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64648. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
