### PR TITLE
LPS-88059 Refactor.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:help

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hey @marianoalvarosaiz,

I will review the pull tomorrow, sorry for the delay.

Thanks for the collaboration :-)
Hasta mañana!

**Comment by marianoalvarosaiz** [comment]
Don't worry @achaparro,
 we aren't in a hurry, the ticket is all ready closed.
Buenos días!! Es buen momento para recordar el uso de hilos en github.

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65958. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65961. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
