### PR TITLE
LPS-86460 update db schema with PID changes

### PR DESCRIPTION
**Pull request by ajsampang67**
Since this was found to be reproducible in master, continuing from https://github.com/achaparro/liferay-portal-ee/pull/44#issuecomment-432746952

For RSS, PID was changed in configurationId but not dictionary.
For Flags, neither were changed, so added this to upgrade process

Also updated expected schema version in Flags/PageFlags portlets

cc/ @MichaelPrigge @ChrisKian

### CODE REVIEW

**Comment by ajsampang67** [comment]
ci:test:relevant

**Comment by ajsampang67** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hey @ajsampang67,

It seems that the errors are related to your changes, I think it is because the removal of this upgrade process for new installations:
https://github.com/achaparro/liferay-portal/pull/241/files#diff-d84a1c61b3de57988c4a766908b371a6L32

I guess we should keep it and point to 1.0.1 now, could you check it?

Thanks.

**Pull request closed without merging**
