### PR TITLE
LPS-82364 Update ddm structure class name id and classpk to support default structure values

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @ealonso

**Comment by pavel-savinov** [comment]
@achaparro It seems to be a problem of 6.1 -> 6.2 upgrade because **classNamId** in JournalArticle still points to the **JournalStructure** class after the upgrade.
Thanks.

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60572. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60577. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
@pavel-savinov, your solution is the good one. I tried to use the following index:
create index IX_9CE6E0FA on JournalArticle (groupId, classNameId, classPK);

But we can not do it because the groupId we have belongs to the Structure and the journal groupId can be different for those cases where the journal uses a global structure. Anyway, we use this index and it can be enough since filtering by classNameId in this case is really beneficial:
create index IX_C761B675 on JournalArticle (classNameId, DDMTemplateKey[$COLUMN_LENGTH:75$]);

Thanks!
cc/@ealonso

**Pull request closed without merging**
