### PR TITLE
LPS-80193

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi, @achaparro. Recreating indices during upgrade when fallback is invoked won't work unless the sql sentences end in a semicolon. Tell me if you have any questions.

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57773. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @ricardocousolr,

Errors seem to not be related.

There is a few more table clases in master-private. Could you apply the same pattern there if needed?

Thanks!

**Pull request closed without merging**
