### PR TITLE
LPS 137699 final

### PR DESCRIPTION
**Pull request by achaparro**
@samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:stop

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
Hi @vicnate5,

I think the failures are unrelated. Can you check them?

cc/ @SamZiemer

**Comment by vicnate5** [comment]
@achaparro The failures here are not related to this change, there are issues upstream.

But also of note, The test `com.liferay.portal.db.partition.messaging.test.DBPartitionMessageBusInterceptorTest` is unstable upstream

Example: https://testray.liferay.com/reports/production/logs/2021-09/test-1-27/test-portal-acceptance-pullrequest(master)/32/modules-integration-mysql57-jdk8/0/4/jenkins-console.txt.gz

History https://testray.liferay.com/home/-/testray/cases/1518351472

**Comment by achaparro** [comment]
Thanks @vicnate5.

Ok, I will send these changes manually. Regarding the DBPartitionMessageBusInterceptorTest issue, I saw is failing because it does not find a quartz table, can you open a ticket and provide more details about when this is happening (always or from time to time) and if you noticed this after one specific change?

thanks.

**Pull request closed without merging**
