### PR TITLE
Lps 128860

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-128860

Hi @achaparro,

I believe I have what Tina was requesting. Please let me know if you think this works. I am still not certain how she wanted us to only publish the service when the property is set, but I think this still achieves the same outcome.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2288.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2289. [See changes here.](https://github.com/achaparro/liferay-portal/compare/7683fe8fa68b~3...7683fe8fa68b)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/tinatian/liferay-portal/pull/2297. [See changes here.](https://github.com/achaparro/liferay-portal/compare/361e25173d68~3...361e25173d68)

**Pull request closed without merging**
