### PR TITLE
Lps 125591

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @brianikim

> https://issues.liferay.com/browse/LPS-125591
> 
> Straightforward issue. We are increasing title length for blog title as users in previous versions have titles longer than 150 characters and are not able to migrate those files over due to the title length.
> 
> I am implementing a length similar to one being used already in wiki-service which serves similar purposes as blogs:
> 
> https://github.com/liferay/liferay-portal/blob/6fe2335b4f23bd8e1134d66b8ec70aa2f9134231/modules/apps/wiki/wiki-service/src/main/resources/META-INF/portlet-model-hints.xml#L39

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @brianikim, @SamZiemer,

A few things that need to be changed:
- You are using the same upgrade path than the previous upgrade process -> 2.0.0 to 2.0.1 so I will never be executed:
https://github.com/achaparro/liferay-portal/pull/792/commits/5258145268f166f5700d9fbfa635a26d6e1a4f7b#diff-af89e821c1eef54e12175e239e18f4ef1b406659aea158ae6d9306cb456c2e48R82
- For master, we must add this upgrade process as the latest one since the previous upgrade _UpgradeMVCCVersion_ is already in 7.3.x and we want all customers/users execute this upgrade process.
- If you need to backport it to 7.3.x, you can use the same spot for the same reason. For older branches, you will need to reserve the proper spot in master with a dummyUpgradeStep and add the hasColumnType check to be sure that it is never executed twice, this is an example:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-category-property-service/src/main/java/com/liferay/asset/category/property/internal/upgrade/v2_2_0/UpgradeAssetCategoryProperty.java#L27


Apart from this, I am not sure that increasing the field length is the proper solution for this. I will open a slack thread to discuss it.

**Comment by achaparro** [comment]
ci:stop

**Pull request closed without merging**
