### PR TITLE
LPS-118989 UpgradeResourcePermission fails with ORA-01795

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-118989](https://issues.liferay.com/browse/LPS-118989)

Hi Alberto,

I hope you can review my changes.

**Issue**: Oracle has a limitation that prevents adding too many (> 1000) expressions to a list. This may cause problems for custom entities using string primKeys not convertible to long, resulting in "ORA-01795: maximum number of expressions in a list is 1000" error.

The error occurs if the inClause variable contains more than 1000 primKeys: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/upgrade/v7_0_0/UpgradeResourcePermission.java#L129-L145

Based on [Sam's advice](https://github.com/SamZiemer/liferay-portal-ee/pull/444#issuecomment-674165876), update will happen in batches for Oracle DB with more than 1000 primKeys.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @istvansajtos,

Sorry for the delay, I will review it tomorrow.

Thanks.

**Comment by istvansajtos** [comment]
Hi @achaparro,

No problem. Thanks for the update.

**Comment by achaparro** [comment]
Hey @istvansajtos,

Since we already have the logic to generate the in clause prior to your changes, can we simplify the changes passing as parameter a list of arrays of keys in groups of 1000 here?
https://github.com/achaparro/liferay-portal/blob/068fceace9e47e287e1670e7199c49bac1df84ff/portal-impl/src/com/liferay/portal/upgrade/v7_0_0/UpgradeResourcePermission.java#L91

We can execute this SQL at the end of the process:
https://github.com/achaparro/liferay-portal/blob/068fceace9e47e287e1670e7199c49bac1df84ff/portal-impl/src/com/liferay/portal/upgrade/v7_0_0/UpgradeResourcePermission.java#L163

Thanks.

**Comment by istvansajtos** [comment]
Hi @achaparro ,

I made the requested changes. After testing I will send you a new PR.

Thanks.

**Comment by achaparro** [comment]
Thanks a lot @istvansajtos!

**Pull request closed without merging**
