### PR TITLE
LPS 137225

### PR DESCRIPTION
**Pull request by achaparro**
@preston-crary

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:reevaluate:1297401_300

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @vicnate5,

Can you check if the test is related?

Thanks!

**Comment by achaparro** [comment]
Never mind @vicnate5, I think it is related.

**Comment by achaparro** [comment]
ci:forward

**Comment by vicnate5** [comment]
@achaparro Nothing looks like a real issue here. There is that random failure in `UpgradeAssetDisplayPageEntryTest.testUpgradeLocalStagingGroupMultipleArticlesMultipleVersions`, but if you reproduced this at head, then it is not related.

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@achaparro `UpgradeAssetDisplayPageEntryTest` failed again. Still no examples of it failing elsewhere so I do suspect it is related.

I am unable to reproduce this test failing at head.

**Comment by achaparro** [comment]
Hi @vicnate5,

It's an intermittent issue because we execute the upgrade concurrently and there are some dependencies between some executions, if they occur concurrently, we get the error. I modified the code to process first the staging groups and then live groups to always resolve those dependencies:
https://github.com/achaparro/liferay-portal/pull/1022/commits/5a5964d17f110490624956f53c749fef00b86601

Thanks.

**Pull request closed without merging**
