### PR TITLE
[TECHNICAL-SUPPORT] LPS-91307

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @achaparro,

I believe I did everything correctly but please let me know if there is something that I overlooked. I added this upgrade process to the 7.0 upgrade so that it can be backported for the client. If this isn't something you think should be backported I can add it to the latest upgrade process instead.

Thanks.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @jonathanmccann,

In these cases where we modify the database we need to ensure that all customer's databases have this change. With that purpose you can add the upgrade after the lastest one of 7.1.x (micro change):
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/upgrade/v7_1_x/PortalUpgradeProcessRegistryImpl.java#L51

With this all current customers, even the ones in 7.1, will execute this modification in a future upgrade (7.1 can also execute the upgrade tool to just carry out this change)

We will need to backport this to 7.1.x

For your customer, if they are already in 7.0.10 (correct me if they are in the middle of the upgrade), you will need to deliver them a post upgrade fix or a groovy script to give this modification (to avoid direct SQL executions).

Since at least one customer will have this change in an upgrade to future versions of Liferay, you will need to add a check which validates if the field legth is 255 (we have some generic methods for it).

Please, let me know if you are ok with it.

Thanks.
Best regards.

**Comment by jonathanmccann** [comment]
Thank you for that information. It might be good to update this article to be more specific because I thought I was following it correctly but I guess not:

https://grow.liferay.com/share/DXP-+How+to+code+upgrade+process+and+backport+rules

There it says:

> If the upgrade process is due to a bug you need to fix for the current version you should fix the existing previous upgrade process or add a new one in the upgrade path for the next GA if it didn't exist yet (for example, once it has been released 7.0 GA4 which is 7.0.3, you should add it to UpgradeProcess_7_0_4.java).

I took this to mean that if I wanted to backport it to my client's version then I need to add it to their specific version of Liferay. It seems that "next GA" doesn't mean the next GA for the client's version but for the latest version of Liferay.

What you're saying definitely makes sense though and I will begin working on moving the code to the correct upgrade process. Thank you for reviewing this pull and helping me better understand where the upgrade fix should go.

**Comment by jonathanmccann** [comment]
https://github.com/achaparro/liferay-portal/pull/281

**Comment by achaparro** [comment]
Hey @jonathanmccann,

You are totally right, that article is out to date.

Sorry I was quite busy these days, I will review the pull and I will update the article tomorrow.

Thank you.
Best regards.

**Pull request closed without merging**
