### PR TITLE
LPS-108993 We need to initialize the resource actions also during the auto upgrade. The upgrade tool does it

### PR DESCRIPTION
**Pull request by achaparro**
Hi @vicnate5,

This should fix the error from 6.2.10 at least. I will work in the other one too.

Cheers!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hi @vicnate5,

After these changes I don't reproduce the error for 7.2 locally:
https://github.com/vicnate5/liferay-portal/pull/1440#issuecomment-597771085

because we create the resource actions during the upgrade (I have checked it).

**Comment by achaparro** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
We can ignore that SF error for now, it just due to the temp commits

**Comment by achaparro** [comment]
Hey @vicnate5,

It seems that the auto upgrade from 7.1.x and below is fixed but we still have the error for auto upgrading from 7.2.10 right?

If so, can you send me the database you have for that case, thanks!

**Comment by vicnate5** [comment]
ci:test:upgrade

**Pull request closed without merging**
