### PR TITLE
[TECHNICAL-SUPPORT] LPS-92048

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau 

Notes from Kimberly:

> The issue is that database upgrades take a longer time to complete due to the use of the clause NOT IN, since it needs to look for the values twice. This degrades the query performance. NOT EXISTS looks at the missing values once, making this query ore efficient.
> 
> Taking into account Alberto's comment, I have changed the query in the cases that Postrges database is being used.
> 
> The DBTypeToSQLMap is the framework used to apply the newly converted string to Postgres databases. The original query string will be applied when the database is not Postgres.
> 
> LPS-92048

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @SamZiemer,

I am testing the changes with a huge database I have in Postgres, I guess I will be able to send the changes tomorrow.

Thanks.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69846. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @knchau, @SamZiemer, @gregory-bretall,

Please take a look at this commit:
https://github.com/brianchandotcom/liferay-portal/pull/69846/commits/8cecdec69e90fa06415b62a7cfc3e4966fe4830c

We have to specify the table when we filter by classPk otherwise the query will use DLFileEntry.classPk and we would remove more AssetEntry records than needed.

Regarding the results, I have tested the method using a huge database (871784 AssetEntry records) and we go the following results for the method v7_0_0.UpgradeAsset#deleteOrphanedAssetEntries:
- Before: 36.52 minutes
- After: 0.09 minutes

So this is going to save a lot of time for customers using Postgres :-)

Thanks.

**Pull request closed without merging**
