### PR TITLE
Lps 138030

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-138030

Hey Alberto,

After looking into this issue and trying a few different routes, I think the cleanest option is to just print the list of pending upgrades retrieved from releaseManagerOSGiCommands. The list given by it only shows modules that have pending upgrades and portal upgrade processes that are pending. If everything has upgraded completely, then nothing is shown. I needed to make a minor change within releaseManagerOSGiCommands to be able to pass a showUpgradesSteps parameter so we only see the bundle symbolic name and its current schema version plus the highest available schema version.

We can discuss this issue more tomorrow if you think another approach would be best.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@SamZiemer it's fine to do it here.

**Comment by achaparro** [comment]
See https://github.com/achaparro/liferay-portal/pull/1011

**Pull request closed without merging**
