### PR TITLE
LPS-102810 rating

### PR DESCRIPTION
**Pull request by nhpatt**
Another upgrade! (yeah I know that I have one on the queue, priorities :()

1 - Is it Ok?
2 - Can queries be parametrized with String.format to avoid duplication? (MIN, MAX can't be parametrized as a query param, I think*). I haven't found another occurrence on the existing code.
3 - Do you think a sqlRestriction can pass Brian's review? I don't see another way of doing it. Can't use criteria because of https://issues.liferay.com/browse/LPS-8292.

### CODE REVIEW

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @nhpatt,

At first glance, I don't see any major problem with the pull.

Regarding the queries used during the upgrade, I am thinking about using this instead:
```
update RatingsStats set RatingsStats.createDate = ( 
SELECT min(createDate) FROM RatingsEntry WHERE 
RatingsStats.classNameId = RatingsEntry.classNameId and 
RatingsStats.classPK = RatingsEntry.classPK)
```
Is it ok to you?

Regarding 2) I think we can create a method that returns the query with Max or Min as parameter. 

Regarding 3) I have never seen it either but I think that Brian will accept it.

Please, let me know which pull should I review first and sent to Brian  (I don't know if there is any dependency between them). I can work on it tomorrow. I can make previously mentioned changes, you don't need to resend it a new pull.

Thanks!

**Comment by nhpatt** [comment]
Ok, will change it!

No dependencies between them, this one is more important.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/363. [See changes here.](https://github.com/achaparro/liferay-portal/compare/8043246a5b4f~4...8043246a5b4f)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/364. [See changes here.](https://github.com/achaparro/liferay-portal/compare/29170670ff77~4...29170670ff77)

**Comment by achaparro** [comment]
Hi @nhpatt,

I am testing the pull on my repository first. If everything goes well I will send it to Brian.

Cheers!

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/365. [See changes here.](https://github.com/achaparro/liferay-portal/compare/8594e8540dae~4...8594e8540dae)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79954. [See changes here.](https://github.com/achaparro/liferay-portal/compare/287a2b09b6f6~4...287a2b09b6f6)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/366. [See changes here.](https://github.com/achaparro/liferay-portal/compare/12963d3b012f~5...12963d3b012f)

**Pull request closed without merging**
