### PR TITLE
[TECHNICAL SUPPORT] LPS-116472 Implement upgrade process

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-116472

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hey @rodrigopaulino,

There are a few things to check/modify in the pull:
- Upgrade tests in the CI are failing probably because you added a new upgrade process starting in the schema version 3.2.4 but you didn't move the previous one to the next step so there are two paths from 3.2.4:
https://github.com/achaparro/liferay-portal/pull/634/files#diff-6ced3bcca66649675138f4da58bb5840R298
- Anyway, this upgrade affects to everyone so it has to be added as the latest upgrade process. Otherwise, current users of Liferay 7.3 CE will miss this change and will have issues in the future.
- Also, as we talked in the PTR, please, add a dummy upgrade process for the place where you will backport this to 7.2.x and other for 7.1.x

I will proceed to close the ticket and I will wait for the next pull.

Thanks.
PS: I already sent a pull request for the SF rule: https://github.com/hhuijser/liferay-portal/pull/4477

**Comment by rodrigopaulino** [comment]
Yeah, I forgot about updating the next step. Sorry about that. 
Also, thanks for letting me know about the 7.3 CE and the SF pull request.

Best regards.

**Comment by rodrigopaulino** [comment]
New pull: https://github.com/achaparro/liferay-portal/pull/637

**Pull request closed without merging**
