### PR TITLE
LPS-96981 DBInspectorTest#testHasColumnTypeDate fails on Sybase

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-96981

**DBInspectorTest#testHasColumnTypeDate** fails on Sybase because here  [DBInspector.java#L125](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/dao/db/DBInspector.java#L125) Sybase returns 11 in TIMESTAMP columns, instead of 93 (`java.sql.Types.TIMESTAMP` value).

More information see: http://infocenter.sybase.com/help/topic/com.sybase.infocenter.dc38454.1570/doc/html/har1340078811386.html

In order to solve this, I am changing TIMESTAMP column value in `_SQL_TYPES` variable to 11.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82708.

**Pull request closed without merging**
