### PR TITLE
LPS-105763 Call VerifyProperties during the upgrade

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82077. [See changes here.](https://github.com/achaparro/liferay-portal/compare/a50cc56baf40~1...a50cc56baf40)

**Pull request closed without merging**
