### PR TITLE
LPS-111719 update new subscription with the old create and modify dates

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-111719

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hey @SamZiemer,

If we are going to try to keep the subscription data accurate, we have to do it with all related data. I see a couple of points we should review:
- When adding the subscription we are creating a new AssetEntryRecord with the new createDate and modifiedDate [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/service/impl/SubscriptionLocalServiceImpl.java#L145). The dates for the AssetEntry should be the old ones.
- Also, we are creating a new record for the social activity [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/service/impl/SubscriptionLocalServiceImpl.java#L157) and that's wrong because it's not a real subscription.

Can you verify this latest point? If for one reason the activity record is not created, this will simplify everything.

My feeling is that the original definition of this upgrade process is wrong because we should have replaced the className instead of doing the add and remove stuff.

Maybe some options we have now are:
- Refactor to do the update instead of the ADD and DELETE, we should take into account the cases where the upgrade already run.
- Instead of call addSubscription, take the old record, clone it, change the id and the className and persist in the the database with updateSubscription method. Then modify the current AssetEntry or create a new one.

Let me know what you think, there can be other options. Please, check my assumptions because maybe I am wrong.

Thanks.

**Comment by SamZiemer** [comment]
@achaparro,

I agree that the original fix should have been simpler than it currently us with just using SQL updates, and I think we should just go that route.

I originally submitted this fix as I thought the less code changing we do, the more likely we are able to get the fix committed quickly for the client. However, you are correct, we should be updating the assetEntry and social activities as well. All of it can be done with SQL however so we should go that route. I'll work on a new fix and submit it to you when I have it.

**Pull request closed without merging**
