### PR TITLE
LPS-107518 Add the missing upgrade step

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @katienesterovich,

It seems that we lost the upgrade process we are adding now during the implementation of the issue LPS-77556, see https://github.com/brianchandotcom/liferay-portal/pull/56253/commits/f735209e4e2646f4b121d1e89cff259ac43114b2
Is my assumption correct? If so, do you know if it was just a mistake or there was a reason behind that?

Thanks.

cc/ @ealonso

**Comment by katienesterovich** [comment]
Hey @achaparro,  
@SamZiemer and I believe this to be an oversight, as we didn't find anything that would indicate the need for the removal of the existing step.

**Comment by katienesterovich** [comment]
Here is the description from original PR in case that helps :) 

> https://issues.liferay.com/browse/LPS-107518
> 
> There are 5 upgrade steps that need to register on Asset Publisher in total -
> 
> 1.0.0 -> 1.0.1 -> 1.0.2 -> 1.1.0 -> 1.2.0
> 
> 1.1.0 was never registered, due to this commit: brianchandotcom@f735209.
> This fix re-introduces 1.1.0 step and upgrades the database Release_ schema version to 1.0.4.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84144. [See changes here.](https://github.com/achaparro/liferay-portal/compare/c4f47d707547~3...c4f47d707547)

**Comment by achaparro** [comment]
Thanks for the explanation @katienesterovich, then the modifications are perfect. I only added this relevant change:
https://github.com/brianchandotcom/liferay-portal/pull/84144/commits/6ff30dd8f9a2918960124a05264cdffd3a36a1e8

Feel free to deliver an SDH to speed up the process since the modifications are safe.

Thanks!

**Pull request closed without merging**
