### PR TITLE
[TS] LPS-53392 Column emailAddress length should be 254 characters long

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-53392

Hi Alberto,

**Modified Services**:
- Core: `Contact, EmailAddress, MBMailingList, User` when upgrading to 7.0.3  
- Modules:
-- `contacts-service` when upgrading from 1.0.0 to 1.0.1  
-- `shopping-service` from 1.0.0 or 2.0.0 to 2.0.1

Tested upgrade:
```
12:09:07,085 INFO  [main][UpgradeProcess:83] Upgrading com.liferay.shopping.upgrade.v1_0_1.UpgradeShoppingConfiguration
INFO - Upgrading com.liferay.shopping.upgrade.v1_0_1.UpgradeShoppingConfiguration
12:09:07,112 INFO  [main][UpgradeProcess:98] Completed upgrade process com.liferay.shopping.upgrade.v1_0_1.UpgradeShoppingConfiguration in 27ms
INFO - Completed upgrade process com.liferay.shopping.upgrade.v1_0_1.UpgradeShoppingConfiguration in 27ms
12:09:07,143 INFO  [main][UpgradeProcess:83] Upgrading com.liferay.shopping.upgrade.v1_0_1.UpgradeShoppingOrder
INFO - Upgrading com.liferay.shopping.upgrade.v1_0_1.UpgradeShoppingOrder
12:09:07,146 INFO  [main][LoggingTimer:70] Starting com.liferay.portal.kernel.upgrade.UpgradeProcess#alter
INFO - Starting com.liferay.portal.kernel.upgrade.UpgradeProcess#alter
12:09:07,359 INFO  [main][LoggingTimer:38] Completed com.liferay.portal.kernel.upgrade.UpgradeProcess#alter in 213 ms
INFO - Completed com.liferay.portal.kernel.upgrade.UpgradeProcess#alter in 213 ms
12:09:07,360 INFO  [main][UpgradeProcess:98] Completed upgrade process com.liferay.shopping.upgrade.v1_0_1.UpgradeShoppingOrder in 217ms
INFO - Completed upgrade process com.liferay.shopping.upgrade.v1_0_1.UpgradeShoppingOrder in 217ms
12:09:07,421 INFO  [main][UpgradeProcess:83] Upgrading com.liferay.contacts.internal.upgrade.v2_0_1.UpgradeEntry
INFO - Upgrading com.liferay.contacts.internal.upgrade.v2_0_1.UpgradeEntry
12:09:07,422 INFO  [main][LoggingTimer:70] Starting com.liferay.portal.kernel.upgrade.UpgradeProcess#alter
INFO - Starting com.liferay.portal.kernel.upgrade.UpgradeProcess#alter
12:09:07,564 INFO  [main][LoggingTimer:70] Starting com.liferay.portal.kernel.dao.db.BaseDBProcess#runSQLTemplateString
INFO - Starting com.liferay.portal.kernel.dao.db.BaseDBProcess#runSQLTemplateString
12:09:07,613 INFO  [main][LoggingTimer:38] Completed com.liferay.portal.kernel.dao.db.BaseDBProcess#runSQLTemplateString in 49 ms
INFO - Completed com.liferay.portal.kernel.dao.db.BaseDBProcess#runSQLTemplateString in 49 ms
12:09:07,613 INFO  [main][LoggingTimer:38] Completed com.liferay.portal.kernel.upgrade.UpgradeProcess#alter in 191 ms
INFO - Completed com.liferay.portal.kernel.upgrade.UpgradeProcess#alter in 191 ms
12:09:07,613 INFO  [main][UpgradeProcess:98] Completed upgrade process com.liferay.contacts.internal.upgrade.v2_0_1.UpgradeEntry in 192ms
INFO - Completed upgrade process com.liferay.contacts.internal.upgrade.v2_0_1.UpgradeEntry in 192ms
```

Please forward to @ drewbrokke or @ pei-jung if you agree.

Thanks,
Tibi

/cc @ugurcancetin

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by achaparro** [comment]
Hi @lipusz,

It seems that test have been suspend. Today it's holidays in Madrid, I hope to be able to take a look at the pull request tomorrow.

Cheers.

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
Rebased to latest HEAD.

**Comment by achaparro** [comment]
Hey @lipusz, @ugurcancetin,

I'm trying to create an specific field type for emails in model hints but it's a headache all the gw staff. I hope to complete it tomorrow.

Thanks.

**Comment by lipusz** [comment]
Is it really necessary within the scope of this fix?

Sent from mobile
--
Lead Software Engineer,  Platform TS,
SME, Subscription Services, EMEA

**Comment by achaparro** [comment]
I think is the proper the place since we are converting all emailAddresses from 75 to 254. The change is working for the portal, I'm checking the modules currently. It's worths to do it to try to avoid the same bug in the future.

**Comment by achaparro** [comment]
Hey @lipusz,

Didn't you have problems with the following field in contacts module?
		<field name="comments" type="String">
			<hint-collection name="TEXTAREA" />
		</field>
When you executed gradlew :apps:foundation:contacts:contacts-service:buildService

I think model hints logic isn't loading hint-collections from portal-model-hints.xml for modules.

**Comment by lipusz** [comment]
See the commit messages for what I did to regen the stuff.

Sent from mobile
--
Lead Software Engineer,  Platform TS,
SME, Subscription Services, EMEA

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/drewbrokke/liferay-portal/pull/289. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
