### PR TITLE
[TECHNICAL-SUPPORT] LPS-95219

### PR DESCRIPTION
**Pull request by SamZiemer**
Between 7.0 and 7.1 we added a few additional layout page templates, one of which was a 1_2_1 50/50 split. This left us with 2 layout-template-ids with 1_2_1_columns so we added _i and _ii to the end of the Ids, however, layouts currently using a 1_2_1 column layout were never updated upon upgrading.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @SamZiemer,

Maybe I didn't explain it properly. The idea would be to have just one update like this:
update Layout set typeSettings = REPLACE(typeSettings, "layout-template-id=1_2_1_columns", "layout-template-id=1_2_1_columns_ii") where typesettings like '%layout-template-id=1_2_1_columns%'

Please, let me know if it makes sense to you.

Thanks.

**Comment by SamZiemer** [comment]
Thank you for the explanation, @achaparro I've pushed an update that resolves the issue as you mentioned. I appreciate the help with this!

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72955. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72956. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Thanks @SamZiemer !

**Pull request closed without merging**
