### PR TITLE
LPS-135580 add column length limitation to the v1_1_3 SamlSpIdpConnec…

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @achaparro, I believe this is what is causing the index failure for LPP-41815. When I attempted to regenerate the table with the buildUpgradeTable command there were a lot of changes not present in the original file, so I opted to just change the 1 line that I believe is causing the issue. All other instances of creating IX_61204DD already had the column length limitation put on it, so I added this to bring it in line with the rest.

I do not have steps to reproduce for this bug, so if you think we need those to commit this, let me know and we can discuss it tomorrow.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
Hi @SamZiemer,

I forwarded this but I would like to know if there is an issue with the build upgrade table command, I guess you have modified this file manually but this should be done automatically. I am ok with making this change manually but can you confirm if there is an issue with the command? Can you verify how the class is generated for that table right now? does it contain the string length limitation? We have to avoid more issues like this in the future.

Regarding the upgrade steps, I guess we should use a database that requires to use this class to regenerate the table. Are you using the same database than the customer? Please, verify that to provide the exact steps in the LPS.

Thanks.

**Pull request closed without merging**
