### PR TITLE
LPS-67978 SF

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
ci:retest

**Comment by achaparro** [comment]
ci:retest

**Comment by achaparro** [comment]
ci:retest

**Comment by jpince** [comment]
@achaparro Looks like portlets are missing?
missing portlets
```
     [exec] INFO - Completed verification process com.liferay.portal.security.ldap.internal.verify.LDAPPropertiesVerifyProcess in 39ms
     [exec] 14:53:01,337 ERROR [localhost-startStop-1][com_liferay_portal_upgrade:97] Invocation to listener threw exception 
     [exec] java.lang.NullPointerException
     [exec] 	at com.liferay.portal.upgrade.internal.release.ReleaseManagerOSGiCommands.getCurrentUpgradeInfosList(ReleaseManagerOSGiCommands.java:318)
     [exec] 	at com.liferay.portal.upgrade.internal.release.ReleaseManagerOSGiCommands.doExecute(ReleaseManagerOSGiCommands.java:236)
     [exec] 	at com.liferay.portal.upgrade.internal.release.ReleaseManagerOSGiCommands$UpgradeInfoServiceTrackerMapListener.keyEmitted(ReleaseManagerOSGiCommands.java:435)
     [exec] 	at com.liferay.portal.upgrade.internal.release.ReleaseManagerOSGiCommands$UpgradeInfoServiceTrackerMapListener.keyEmitted(ReleaseManagerOSGiCommands.java:425)
     [exec] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$DefaultEmitter.emit(ServiceTrackerMapImpl.java:225)
     [exec] 	at com.liferay.osgi.service.tracker.collections.map.PropertyServiceReferenceMapper.map(PropertyServiceReferenceMapper.java:43)
     [exec] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:264)
     [exec] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:251)
     [exec] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
```
See gist: https://gist.github.com/jpince/6356a280e149e9a722821450954a2799

**Comment by achaparro** [comment]
Thanks @jpince,

There is an error in the code. I will fix it.

Cheers!

**Comment by jpince** [comment]
ci:stop

**Comment by achaparro** [comment]
ci:retest

**Comment by jpince** [comment]
@achaparro nice! there is one SF error I missed earlier, sorry:
```
org.junit.ComparisonFailure: ../../../modules/apps/foundation/portal/portal-upgrade/src/main/java/com/liferay/portal/upgrade/internal/release/ReleaseManagerOSGiCommands.java expected:<...> upgradeInfosList =[ getCurrentUpgradeInfosList(
			]bundleSymbolicName, ...> but was:<...> upgradeInfosList =[
			getCurrentUpgradeInfosList(]bundleSymbolicName, ...>
```

I think it wants https://github.com/achaparro/liferay-portal/pull/29/files#diff-89c389dbea43405b95339f04d5c08472R347 to be the same way you did it here https://github.com/achaparro/liferay-portal/pull/29/files#diff-89c389dbea43405b95339f04d5c08472R236

In the future, you can find this failure by, in the GitHub comment, clicking on SourceFormatterTest.testSourceFormatter at the bottom of the pull, or test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8 in the Job Summary.

**Comment by achaparro** [comment]
Hey @jpince,

I have sent a new pull request changing it:
https://github.com/achaparro/liferay-portal/pull/32

Thanks!

**Pull request closed without merging**
