### PR TITLE
LPS-185647 This doesn't work yet :(, but sending it in case you wanted to see my progress

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @achaparro,

I tested this against [LPS-184771](https://issues.liferay.com/browse/LPS-184771), and unfortunately, it does NOT resolve the issue. However, I am sending this anyway so that you can see the progress, and in case you had some time to work on it before my next working day. I haven't tested [LPS-185647](https://issues.liferay.com/browse/LPS-185647) yet because it's tedious for me to do so, due to an unrelated issue with my master branch.

I removed your commit to add the pop/push methods for companyId since I found it not to be necessary.

However, I think what you said about us needing to do this for the FlushEvent instead of (or in addition to?) the FlushEntityEvent is correct. Not only that, but I believe we also need to do this for the AutoFlushEvent. These all seem to be separate types of Events. The reason [LPS-184771](https://issues.liferay.com/browse/LPS-184771) is still occurring seems to be because it is happening during an AutoFlushEvent, which we don't have a Listener for yet.

However, I'm a bit concerned because I'm not sure how straightforward it will be (if it's even possible at all) to get the Entity that is being flushed during a FlushEvent or an AutoFlushEvent...

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @mbowerman,

Sorry I didn't have time to test it. Your changes make sense and I like the removal of push/pop company, I didn't like it either. Please, provide an update later today and probably I will have time tomorrow morning to work on it if needed.

Thank you.

**Comment by mbowerman** [comment]
Hi @achaparro,

I'm concerned about the feasibility of this approach, because from what I saw regarding `FlushEvent` and `AutoFlushEvent`, it seems that:
1. They operate using `PreparedStatement` instead of `Entity`, meaning that it's not really straightforward at all to get the relevant companyId for the event (we can't just cast it to a `ShardedModel` like we could with `Entity`.
2. Even worse, there can be multiple statement executions associated with the Event, and there's no guarantee (I think) that they will be on the same company. So if we have multiple statement executions that are on different companies, there's nothing we can really do in that case, since the Listener only allows us to wrap the entire event execution in a `CompanyThreadLocal.setCompanyId`, rather than wrapping each individual statement execution in a `CompanyThreadLocal.setCompanyId`.

This makes me think that in order to proceed with this approach, we'd need to reconfigure Hibernate somehow so that it always uses FlushEntityEvent instead of AutoFlushEvent or FlushEvent. However, I'm not sure if this is even possible, and even if it is, it probably would have a negative impact on performance. What do you think?

**Comment by achaparro** [comment]
Then, I think we should come back to the initial approach and use:
- PreDeleteEventListener
- PreInsertEventListener
- PreUpdateEventListener

I used that before and it worked for me (at least for the SAP issue) but I moved to the Flush event approach just to simplify it since I also implemented the Post event listener to restore the CompanyThreadLocal.

**Comment by mbowerman** [comment]
Hi @achaparro,

Do you happen to still have the branch somewhere where you tried to implement that fix? Even if it's very much a WIP for now, it would still be quite helpful for me to look at it to try to get started on it.

**Comment by mbowerman** [comment]
Hi @achaparro ,

I've sent a new pull request here: https://github.com/achaparro/liferay-portal/pull/1060

**Pull request closed without merging**
