### PR TITLE
LPS-106402 - My Organizations portlet should also check for Organization level permissions

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @achaparro!

https://issues.liferay.com/browse/LPP-35975
https://issues.liferay.com/browse/LPS-106402

The reproduction steps for this issue are a bit complicated, but ultimately this issue boils down to the fact that, when using the My Organizations portlet, the add organization permission is only checked on the portal level. Specifically, it checks for the permission labeled "Portal: Add Organization" in the UI. Therefore, if the permission is added on an organizational basis such as in an organization role, the check fails and the request is denied. This is inconsistent with how the check operates in the Users and Organizations portlet and thus can lead to user confusion.

The fix therefore adds a secondary check to see if a parentOrganizationId was sent as a parameter. If so, it'll check if the user has permission to add through the OrganizationPermissionUtil. This check is similar to one made in the addOrganization function in OrganizationServiceImpl.

Please let me know if you have any questions or if I can clarify anything further. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @wanderlast,

During the review process, I have been testing the issue in master without your changes first and I wasn't able to reproduce the issue. I could create the suborganization from TEST ORGANIZATION's option menu > Add Organization. Did I miss any step? If not, maybe another fix solved it during this time, can you verify it?

Thanks.

**Comment by wanderlast** [comment]
Hi @achaparro,
I just checked again and it's still reproducible for me. One thing to double-check is if you're trying to add the organization in the My Organizations portlet or not. If you're doing it under Control Panel > Users & Organizations, it should work and be able to be added successfully. You need to go through the User's Menu > My Organizations and attempt to add there for it to fail.

**Comment by achaparro** [comment]
I think I tried via "My organizations" portlet but let me check it again just in case

**Comment by achaparro** [comment]
My bad, you are right @wanderlast probably I logged in several times and probably I did the test with the admin user by mistake.

**Comment by achaparro** [comment]
I proceed to close the pull after our converation @wanderlast

**Pull request closed without merging**
