### PR TITLE
Lps 117123 master

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-117123
https://issues.liferay.com/browse/LPP-38126

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/646. [See changes here.](https://github.com/achaparro/liferay-portal/compare/6668f413c89b~4...6668f413c89b)

**Pull request closed without merging**
