### PR TITLE
LPS-84870

### PR DESCRIPTION
**Pull request by jcampoy**
Upgrade dates in SQLServer from datetime to datetime2. This PR is for the collaboration modules. I will continue with the WEM modules.

https://issues.liferay.com/browse/LPS-84870

cc/ @adolfopa

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test

**Comment by jcampoy** [comment]
ci:tests

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64055. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
