### PR TITLE
LPS-91476

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69251. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69252. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
