### PR TITLE
LPS-86289

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-86289

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
ci:test:upgrade

**Comment by jcampoy** [comment]
ci:help

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66997. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
