### PR TITLE
LPS-129575 Add option to remove Software Catalog data in DataCleanup module

### PR DESCRIPTION
**Pull request by kevhlee**
**Tickets:**
* <https://issues.liferay.com/browse/LPS-129575>

**Notes:**

It is worth noting that the Software Catalog module was removed from Portal 6.2 before the DXP 7.0 release (see [LPS-60705](https://issues.liferay.com/browse/LPS-60705)). For deleting the Software Catalog data, I based my code on the following:

* <https://github.com/liferay/liferay-portal-ee/blob/6.2.x/portal-impl/src/com/liferay/portlet/softwarecatalog/service/impl/SCProductScreenshotLocalServiceImpl.java#L30-L42>
* <https://github.com/liferay/liferay-portal-ee/blob/6.2.x/portal-impl/src/com/liferay/portlet/softwarecatalog/service/impl/SCProductEntryLocalServiceImpl.java#L222-L265>

Let me know if you have any questions/thoughts.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/970. [See changes here.](https://github.com/achaparro/liferay-portal/compare/d3eb8b502963~2...d3eb8b502963)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/971. [See changes here.](https://github.com/achaparro/liferay-portal/compare/c9ba8f8c5e8e~3...c9ba8f8c5e8e)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/972. [See changes here.](https://github.com/achaparro/liferay-portal/compare/2182c6047109~4...2182c6047109)

**Pull request closed without merging**
