### PR TITLE
LPS-107149 Untie Core verify processes from the upgrade

### PR DESCRIPTION
**Pull request by achaparro**
@SamZiemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:stable

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:foward

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@vicnate5 @kyle-miho

The errors don't seem related, what do you think? If not, can I send it to Brian?

Thanks.

**Comment by kyle-miho** [comment]
@achaparro we are only allowed to send to brian with ci:foward now, if the tests are truly failing due to unrelated changes, we have to send brian a pr (we can do this directly) to quarantine those tests, and when that merges stable, we can then re-run ci:test:relevant on this pr (sadly changes across all modules are going to be harder to get in)

**Comment by vicnate5** [comment]
@kyle-miho @achaparro We can add the quarantines directly to this PR if needed.

I can help.

**Comment by achaparro** [comment]
@vicnate5 @kyle-miho,

We are getting similar issues here:
https://github.com/achaparro/liferay-portal/pull/505#issuecomment-603544478

Do you think we can put in quarantine the ones are failing, are they failing in other upgrade pulls? If so, we should do it, otherwise I won't be able to send pull requests

**Pull request closed without merging**
