### PR TITLE
LPS-135819

### PR DESCRIPTION
**Pull request by kevhlee**
**Tickets:**
* <https://issues.liferay.com/browse/LPS-135819>
* <https://issues.liferay.com/browse/LRQA-68765>

**Notes:**
The issue is caused by faulty logic in `LayoutTypeSettingsUtil.java` from commit 42d9d98a73beaff7.

Let me know if you have any questions or if any changes need to be made.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Tested and passed! Thank you so much @kevhlee for being proactive and acting fast!

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
