### PR TITLE
LPS-87023 We must use SQL

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hey @vicnate5 @jpince, do you think is normal the failures during the upgrade tests? There are too many but I have checked a few of them and I can't get any clue about what it's failing.

Thanks!

**Comment by vicnate5** [comment]
@achaparro taking a look, the failure rate does look really high.

**Comment by vicnate5** [comment]
@achaparro The main issue here is specific to upgrades from 6.2.* - All of them are failing with:
```
upgrade-legacy-database:
     [java] JVM arguments: -Dfile.encoding=UTF8 -Duser.country=US -Duser.language=en -Duser.timezone=GMT -Xmx2048m -Dexternal-properties=portal-upgrade.properties -Dserver.detector.server.id=tomcat
     [java] Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.17/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
     [java] Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.17/webapps/ROOT/WEB-INF/classes/system-ext.properties
     [java] Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.17/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/portal.properties
     [java] Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.17/webapps/ROOT/WEB-INF/classes/portal-ext.properties
     [java] Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tools/portal-tools-db-upgrade-client/com.liferay.portal.tools.db.upgrade.client.jar!/portal-upgrade.properties
     [java] Loading file:/opt/dev/projects/github/liferay-portal/bundles/tools/portal-tools-db-upgrade-client/portal-upgrade-ext.properties
     [java] Loading file:/opt/dev/projects/github/liferay-portal/bundles/tools/portal-tools-db-upgrade-client/portal-upgrade-database.properties
     [java] 2019-06-14 17:49:15.519 INFO  [main][DialectDetector:159] Using dialect com.liferay.portal.dao.orm.hibernate.MariaDBDialect for MySQL 10.2
     [java] 2019-06-14 17:49:17.784 INFO  [main][ModuleFrameworkImpl:1319] Starting initial bundles
     [java] 2019-06-14 17:49:28.707 INFO  [main][ModuleFrameworkImpl:1596] Started initial bundles
     [java] 2019-06-14 17:49:28.803 INFO  [main][ModuleFrameworkImpl:1631] Starting dynamic bundles
     [java] 2019-06-14 17:49:29.031 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.bundle.blacklist.internal.BundleBlacklistConfiguration)][BundleBlacklist:188] Stopping blacklisted bundle com.liferay.portal.mobile.device.detection.fiftyonedegrees.api_4.0.0 [121]
     [java] 2019-06-14 17:49:29.038 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.bundle.blacklist.internal.BundleBlacklistConfiguration)][BundleBlacklist:188] Stopping blacklisted bundle com.liferay.portal.mobile.device.detection.fiftyonedegrees.enterprise_4.0.0 [122]
     [java] 2019-06-14 17:49:29.074 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.bundle.blacklist.internal.BundleBlacklistConfiguration)][BundleBlacklist:188] Stopping blacklisted bundle com.liferay.portal.mobile.device.detection.fiftyonedegrees.enterprise.test.data_2.0.0 [123]
     [java] 2019-06-14 17:49:29.081 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.bundle.blacklist.internal.BundleBlacklistConfiguration)][BundleBlacklist:188] Stopping blacklisted bundle com.liferay.portal.mobile.device.detection.fiftyonedegrees_5.0.0 [124]
     [java] 2019-06-14 17:49:38.995 INFO  [main][BundleBlacklist:188] Stopping blacklisted bundle com.liferay.portal.mobile.device.detection.fiftyonedegrees.api_4.0.0 [981]
     [java] 2019-06-14 17:49:39.373 INFO  [main][BundleBlacklist:188] Stopping blacklisted bundle com.liferay.portal.mobile.device.detection.fiftyonedegrees.enterprise_4.0.0 [982]
     [java] 2019-06-14 17:49:39.494 INFO  [main][BundleBlacklist:188] Stopping blacklisted bundle com.liferay.portal.mobile.device.detection.fiftyonedegrees.enterprise.test.data_2.0.0 [983]
     [java] 2019-06-14 17:49:39.564 INFO  [main][BundleBlacklist:188] Stopping blacklisted bundle com.liferay.portal.mobile.device.detection.fiftyonedegrees_5.0.0 [984]
     [java] 2019-06-14 17:49:39.647 INFO  [main][ModuleFrameworkImpl:1728] Started dynamic bundles
     [java] 2019-06-14 17:49:39.647 INFO  [main][ModuleFrameworkImpl:398] Navigate to Control Panel > Configuration > Gogo Shell and enter "lb" to see all bundles
     [java] 2019-06-14 17:49:44.716 INFO  [main][StartupHelper:73] There are no patches installed
     [java] java.sql.SQLSyntaxErrorException: Unknown column 'schemaVersion' in 'field list'
     [java] 	at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:138)
     [java] 	at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
     [java] 	at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:268)
     [java] 	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:296)
     [java] 	at org.mariadb.jdbc.MySQLStatement.executeQuery(MySQLStatement.java:349)
     [java] 	at org.mariadb.jdbc.MySQLPreparedStatement.executeQuery(MySQLPreparedStatement.java:104)
     [java] 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
     [java] 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
     [java] 	at com.liferay.portal.upgrade.PortalUpgradeProcess.getCurrentSchemaVersion(PortalUpgradeProcess.java:49)
     [java] 	at com.liferay.portal.upgrade.PortalUpgradeProcess.isInLatestSchemaVersion(PortalUpgradeProcess.java:95)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:134)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:87)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:55)
     [java] Caused by: org.mariadb.jdbc.internal.common.QueryException: Unknown column 'schemaVersion' in 'field list'
     [java] 	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:995)
     [java] 	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1050)
     [java] 	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1030)
     [java] 	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:289)
     [java] 	... 13 more
```

**Comment by achaparro** [comment]
it's an error in the pull, thanks @vicnate5!

**Comment by achaparro** [comment]
ci:close

**Comment by jpince** [comment]
@vicnate5 nice job, thanks!

@achaparro Victor is the best resource for you to go to for specific test failures. I am happy to help with general CI questions or if Victor is unavailable.

**Pull request closed without merging**
