### PR TITLE
LPS-79876

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by achaparro** [comment]
Hi @jonathanmccann,

This process was included in 6.1EE GA3:
https://issues.liferay.com/browse/LPS-29879

Since we allow direct upgrades from any version of 6.1.x, could you move this logic to an upgrade process in the path _UpgradeProcess_6_2_0_?

Thanks!

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonathanmccann** [comment]
The source formatter seems to be failing. I can make the changes and push again, not sure if you're still reviewing it or not.

**Comment by achaparro** [comment]
Hi @jonathanmccann,

What I had in mind it's to create a BaseUpgradeProcess with the layout change and use it here and these other pull:
https://github.com/achaparro/liferay-portal/pull/163
https://github.com/achaparro/liferay-portal/pull/179

Could you do that? If it's easier you can send one pull with the three changes.

Thanks.

**Comment by achaparro** [comment]
Ok @jonathanmccann , what do you think if we create a single upgrade process with this method:
https://github.com/jonathanmccann/liferay-portal/blob/14eea686c5e9a4742f32f8bedc6a3fc2f7aef257/portal-impl/src/com/liferay/portal/verify/VerifyLayout.java#L131

An we call it twice, for journal and Asset.

Apart from that, could we also include this method in that upgrade too:
https://github.com/jonathanmccann/liferay-portal/blob/14eea686c5e9a4742f32f8bedc6a3fc2f7aef257/portal-impl/src/com/liferay/portal/verify/VerifyLayout.java#L122

It also belongs to LPS-29879, right?

Thanks!

**Comment by jonathanmccann** [comment]
So something like an UpgradeUuid? That makes sense to me. I'll get to work on it, thanks!

**Comment by achaparro** [comment]
Hi @jonathanmccann,

It would be something like this:

protected void doUpgrade() throws Exception {
verifyUuid()
verifyUuid("asset")
verifyUuid("journal")
}

Is this what you had in mind too?

**Comment by jonathanmccann** [comment]
Yup, that's what I have! I'll send it along shortly once I double check everything.

**Comment by jonathanmccann** [comment]
https://github.com/achaparro/liferay-portal/pull/181

**Pull request closed without merging**
