### PR TITLE
LPS-85419 Implement the upgrade in comments layout

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by achaparro** [comment]
Hey @robertoDiaz,

Regarding this pull, we are removing data in the upgrade process, that means that it's not revertible right? If we want to backport it we should find another revertible way, at least in EE branches.

Apart from that I have realized that the pull https://github.com/adolfopa/liferay-portal/pull/715 was closed due to the tests.

Thanks.

**Comment by robertoDiaz** [comment]
Yes, in 7.0 and 7.1 we could avoid delete the old subscriptions.

Anyway, since we are not removing all the data, but modifiying it (we create a new one with a different classname) this data could be recovered using a script, for example and setting the old  classname again.

**Comment by robertoDiaz** [comment]
@achaparro 

See https://github.com/adolfopa/liferay-portal/pull/720

**Comment by achaparro** [comment]
see https://github.com/achaparro/liferay-portal/pull/245

**Pull request closed without merging**
