### PR TITLE
LPS-103035 Use the default companyId

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Service builder tests showed changes

```
     [echo] --- a/modules/apps/depot/depot-service/src/main/resources/META-INF/sql/indexes.sql
     [echo] +++ b/modules/apps/depot/depot-service/src/main/resources/META-INF/sql/indexes.sql
     [echo] @@ -1,4 +1,4 @@
     [echo] -create unique index IX_884D6226 on DepotEntry (groupId);
     [echo] +create unique index IX_38B9EE42 on DepotEntry (groupId, companyId);
     [echo]  create index IX_FBDFFFF8 on DepotEntry (uuid_[$COLUMN_LENGTH:75$], companyId);
     [echo]  create unique index IX_418C2F6E on DepotEntry (uuid_[$COLUMN_LENGTH:75$], groupId, companyId);
     [echo]  
```

**Pull request closed without merging**
