### PR TITLE
LPD-1721

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
@achaparro in case you want to review it also before sending it to the core team.

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:db-partition

**Comment by achaparro** [comment]
@marianoalvarosaiz it looks good to me, I am running the tests since this affected db partition

**Comment by achaparro** [comment]
ci:report:2534040689

**Comment by achaparro** [comment]
ci:report:2534035544

**Comment by achaparro** [comment]
@marianoalvarosaiz, please review the tests, it seems they are not related

**Comment by marianoalvarosaiz** [comment]
@achaparro the only unique failure is LocalFile.PortalSmokeAutoUpgrade#ViewPortalSmokeArchiveAutoUpgrade7413, but fails due to a timeout:

```
Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [http://172.31.0.2:9201], URI [/_ingest/pipeline/timestamp?master_timeout=30s&timeout=30s], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[{"type":"process_cluster_event_timeout_exception","reason":"failed to process cluster event (put-pipeline-timestamp) within 30s"}],"type":"process_cluster_event_timeout_exception","reason":"failed to process cluster event (put-pipeline-timestamp) within 30s"},"status":503}
```

So if you are OK I will send it to the core team (or you can send it if you prefer it).

Kind regards.

**Comment by achaparro** [comment]
@marianoalvarosaiz send it to core. You can mention me saying I passed the review.

Thanks!

**Comment by marianoalvarosaiz** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6586

**Pull request closed without merging**
