### PR TITLE
LPS-73023

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-73023

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test

**Comment by achaparro** [comment]
Hi @holatuwol,

This comes at a very opportune since we are currently doing the upgrade performance tests. I wiil include these changes in the iteration of tomorrow or Thursday.

Thanks!

**Comment by achaparro** [comment]
@holatuwol  By the way, could you check the CI errors? can they be related?

Thanks!

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hola @holatuwol,

The changes look good to me, I am going to test them for SQL Server this weekend.

I will let you know.

Thanks.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60006. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
