### PR TITLE
LPS 137162

### PR DESCRIPTION
**Pull request by achaparro**
@samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:stop

**Comment by achaparro** [comment]
ci:forward

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
@SamZiemer The unique test failure is a known issue in upstream. I am currently looking into it

**Comment by SamZiemer** [comment]
ok, great, thank you @vicnate5, I thought it may be that's why I reran the test.

**Comment by vicnate5** [comment]
The failure is random, it might pass on re-run

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:reevaluate:1327401_205

**Comment by achaparro** [comment]
ci:reevaluate:1327401_205

**Comment by achaparro** [comment]
sent manually in:
https://github.com/brianchandotcom/liferay-portal/pull/105788

**Pull request closed without merging**
