### PR TITLE
LPS-125591

### PR DESCRIPTION
**Pull request by brianikim**
Resent from here: https://github.com/achaparro/liferay-portal/pull/792

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/796. [See changes here.](https://github.com/achaparro/liferay-portal/compare/bf31190733d4~1...bf31190733d4)

**Pull request closed without merging**
