### PR TITLE
SF: Remove verify Oracle

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:stop

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
ci:retest

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Sent https://github.com/migue/liferay-portal/pull/875

**Pull request closed without merging**
