### PR TITLE
LPS-93558

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-93558

Regression of LPS-91476 which only occurs in Sybase.

Let me know if you have any questions about the pull, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hi @ChrisKian,

Sorry for the dealy, the change looks good, I am just testing locally the upgrade to be sure that we didn't forget anything with the previous pull. I will send the pull tomorrow.

Thanks.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71323. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
