### PR TITLE
[TS] LPS-93431

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-93431

Hey Alberto,

This upgrade process is needed for any Sybase DB (and possibly others) which are originally from 6.2 or below and have been upgraded (or will be upgraded).

When starting a portal from DXP and above on a new Sybase DB, we are fine since [we create the DDLRecordSet.versionUserId as type LONG](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-lists/dynamic-data-lists-service/src/main/resources/META-INF/sql/tables.sql#L29).

However, when upgrading to DXP instead, the upgrade process didn't account for this, [upgrading it to VARCHAR instead](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-lists/dynamic-data-lists-service/src/main/resources/com/liferay/dynamic/data/lists/internal/upgrade/v1_0_2/dependencies/update.sql#L3).  This eventually leads to conversion errors when attempting to add a DDLRecordSet since Sybase cannot implicitly cast from DECIMAL to VARCHAR.

It's also important to note this issue is blocked by LPS-93558, which you are currently reviewing as well.  It's blocked simply because the upgrade process won't complete without it, so there is no way to test the current fix.

Please let me know if you have any questions, or if there is any additional work for me.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @ChrisKian,

First of all, sorry for the delay, last weeks are being really busy for me due to some movements (I think you already know the reason :grinning:)

Regarding the pull, it seems that the root of the issue is here:
https://issues.liferay.com/browse/LPS-69161

We added the new field for fresh databases as long, but we created the following upgrade process defining the field as varcha as you properly explained before:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-lists/dynamic-data-lists-service/src/main/resources/com/liferay/dynamic/data/lists/internal/upgrade/v1_0_2/dependencies/update.sql#L3

Taking this into account, could you?
1- Fix the previous file v1_0_2/dependencies/update.sql to use long
2- Keep your upgrade process but validate first if the type is already long (we have some Util classes for that) to do or not to do the conversion. In this way we will cover all possibilities (fresh databases and customers with previous fix once we backport it)
3- Could you confirm that the conversion from varchar to long will work for all databases in this way?
https://github.com/achaparro/liferay-portal/pull/293/commits/bec5d2c7d6600fd9059e46d634c3770d9bfc44f2#diff-41085a19d33d391a82ff643eefa933f9

Please, let me know if you agree with this or you see any drawbacks

Thanks!

**Pull request closed without merging**
