### PR TITLE
Lps 120146

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
I needed to rebase to upstream/master

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
hey @SamZiemer,

I am checking the changes (probably we need to remove all references to upgrade) but it seems that the tests failed, can you check it?

Thanks.

**Comment by achaparro** [comment]
Hey @SamZiemer,

Let's keep the references to the upgrade for now since they are upgrade processes and I am not sure if Brian would like to change it. It looks good to me. We just need to fix the tests. I am going to mention this change in the Core meeting today at 8 AM, I will keep you updated.

Thanks.

**Pull request closed without merging**
