### PR TITLE
LPS-73034 Correct Calendar Upgrade Versions and Calendar Resource Guest Block Permissions Upgrade

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-73034

I renamed versions of upgrades that are "Tecnical Task" or "Store" in commit https://github.com/achaparro/liferay-portal/pull/57/commits/c1898299e24db590d99005f24fb1a4b41e512324 in order to follow numbers versions rules regarding upgrades.

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @JosemariaMunoz,

I think that calendar has its own repo:
https://github.com/liferay/com-liferay-calendar

Could you verify it and send me a pull request to that repo if it's true?

Thanks.
@jorgediaz-lr

**Comment by achaparro** [comment]
My bad, there is no subrepo for Calendar

@JosemariaMunoz @jorgediaz-lf

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @JosemariaMunoz,

I have done several changes in the pull request and I would like to talk about that with you in person. I will come back from vacation this wednesday, so we can talk that day in the morning. Modification in upgrade processes are really important so I prefer to do it carefully.

On the other hand, I have created two tickets to tell Calendar team about the way to create upgrade processes in modules, see:
https://github.com/natocesarrego/liferay-portal/pull/84
https://github.com/natocesarrego/liferay-portal/pull/85

As you can see, the lastest one contain your first commit. Since the original fix is complex I decided to separate this in several LPS. Also because in this way then the backport of LPS-73034 will be complete to ee-7.0.x.

Cheers!

**Comment by JosemariaMunoz** [comment]
Ok @achaparro no problem, we'll see this changes on wednesday.

Thanks and enjoy your vacations!

**Pull request closed without merging**
