### PR TITLE
LPS-79878 Convert JournalServiceVerifyProcess into an UpgradeProcess

### PR DESCRIPTION
**Pull request by Preston-Crary**
Please wait for the functional upgrade tests to run, thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/193. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/196. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/197. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1652. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
