### PR TITLE
LPS-79881

### PR DESCRIPTION
**Pull request by jonathanmccann**
I wasn't sure if we should deprecate the classes or simply remove them since they're all "internal".

### CODE REVIEW

**Comment by achaparro** [comment]
Sorry @jonathanmccann, could you rebase this pull?

Thanks!

**Comment by achaparro** [comment]
Maybe we have to wait until the following pull is approved:
https://github.com/brianchandotcom/liferay-portal/pull/57603

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
I wasn't sure if we could outright delete these classes so I went for deprecating. If you think we can get rid of them, I can definitely do that. Other than that I removed the classes from `util-spring.xml` that were only of the type `VerifiableUUIDModel` since those beans are no longer referenced. For the other classes that implement other `Verifiable*` classes, I left those in but removed their implementation of `VerifiableUUIDModel`.

Let me know if you have any questions or concerns.

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by achaparro** [comment]
Hi @jonathanmccann,

We can not remove the execution of the verifyUUID for most of the entities since the uuid field and the verification for most of them were added in 6.1 or 6.2. Please see my final pull:
https://github.com/achaparro/liferay-portal/pull/187

And let me know if you see somthing wrong

Thanks.

**Comment by achaparro** [comment]
FInal pull:
https://github.com/brianchandotcom/liferay-portal/pull/57776

**Pull request closed without merging**
