### PR TITLE
Lps 116119 master

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-116119

I've tested this in my local environment and in a PR to myself. The tests look like they pass now.

Test results: https://github.com/SamZiemer/liferay-portal/pull/743

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by SamZiemer** [comment]
@achaparro, I've added the removal of the release record now.

**Comment by achaparro** [comment]
good @SamZiemer, I think you can move the removal of the release record outside of the if just to have it once.

Anyway, it's good to be delivered as SDH for the customer after testing the build as we talked. 

I will review it to commit in master later.

Thanks.

**Comment by SamZiemer** [comment]
@achaparro that is a good point. I've updated to commit to move the release deletion outside of the if statements.

**Comment by achaparro** [comment]
thanks @SamZiemer

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/636. [See changes here.](https://github.com/achaparro/liferay-portal/compare/fcfbb32d7d7e~4...fcfbb32d7d7e)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/640. [See changes here.](https://github.com/achaparro/liferay-portal/compare/ed33ac9e2a6a~6...ed33ac9e2a6a)

**Pull request closed without merging**
