### PR TITLE
LPS-107322

### PR DESCRIPTION
**Pull request by jonathanmccann**
As discussed, moved the base class to the module.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83729. [See changes here.](https://github.com/achaparro/liferay-portal/compare/c5cb0672f563~2...c5cb0672f563)

**Pull request closed without merging**
