### PR TITLE
LPS 145031 pr3

### PR DESCRIPTION
**Pull request by dantewang**
Hi @achaparro, Hai made changes according to https://github.com/achaparro/liferay-portal/pull/1025#issuecomment-1017667108

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @dantewang @yuhai sorry I am now in the hospital for a few days, I will check the pull next week or, if it is critical, send it to liferay-upgrades so @samziemer can check it 

Thanks!

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Looks good to me anyway so let's wait for the tests

**Comment by SamZiemer** [comment]
ci:reevaluate:1377401_44

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@vicnate5 @kyle-miho do you think the errors are  related?

Thanks

**Comment by kyle-miho** [comment]
looking into this

**Comment by kyle-miho** [comment]
failures unrelated

**Comment by achaparro** [comment]
Hi guys, I will review this tomorrow. I was out of the office las days

**Comment by achaparro** [comment]
@dantewang @yuhai This pull is really good, thank guys!

I have sent the final pull request here:
https://github.com/liferay-upgrades/liferay-portal/pull/244

**Pull request closed without merging**
