### PR TITLE
[TECHNICAL-SUPPORT] LPS-78665

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by mbowerman** [comment]
ci:reopen

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56148. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56192. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
