### PR TITLE
[TS] LPS-132627 Add again the primKeyId != 0 condition to the SQL as it is necessary in some cases

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-132627

Add again the primKeyId != 0 condition to the SQL to fix the issue detected in https://issues.liferay.com/browse/LRQA-67333

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Semantic version error seems to be unrelated to my changes as it fails in points that I didn't change.

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Pull request closed without merging**
