### PR TITLE
LPS-90108 Semantic versioning

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by achaparro** [comment]
Hi @kyle-miho, @brianchiu, @pavel-savinov,

I am doing the final verifications regarding the failure and possible related failures in the pull. I will send the pull tomorrow.

Cheers!

**Comment by achaparro** [comment]
see https://github.com/pavel-savinov/liferay-portal/pull/306

**Comment by achaparro** [comment]
Final pull:
https://github.com/pavel-savinov/liferay-portal/pull/307

@kyle-miho, @brianchiu, @pavel-savinov

**Comment by achaparro** [comment]
Already solved

**Pull request closed without merging**
