### PR TITLE
LPS-98968 Check article group in order to get the proper default language

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @achaparro,

This problem is very related to https://issues.liferay.com/browse/LPS-90417

However, the fix for LPS-90417 did not take into account the article group relying on the LocaleUtil.getSiteDefault() instead. Unfortunately, LocaleUtil.getSiteDefault() depends on a ThreadLocal that is not correctly populated when performing the upgrade.

I have tried to minimize the computational cost by caching the default language per group in a map.

Please, let me know if any additional clarification is needed for your review.

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76375. [See changes here.](https://github.com/achaparro/liferay-portal/compare/ffeb00c1b27b~1...ffeb00c1b27b)

**Comment by achaparro** [comment]
Everything is clear. I think we didn't take into account the possibility that the content filed didn't contain the default language field and we didn't care about the ThreadLocal due to that.

Good catch @dacousalr !

Thanks!

**Pull request closed without merging**
