### PR TITLE
[TECHNICAL SUPPORT] LPS-105662 Upgrade process to fix field's validation to the correct field name

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-105662

@achaparro, here are the modifications suggested on https://github.com/achaparro/liferay-portal/pull/434
Thanks.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/651. [See changes here.](https://github.com/achaparro/liferay-portal/compare/39d04141e878~1...39d04141e878)

**Pull request closed without merging**
