### PR TITLE
LPS-115692 When staging is in process, users should be added to teams…

### PR DESCRIPTION
**Pull request by SamZiemer**
This issue was caused by https://issues.liferay.com/browse/LPS-111489.

We should be adding users to teams they are a member of on the live site when we initialize staging, the users will be members of the staging site later in the process.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/vendeltoreki/liferay-portal/pull/74. [See changes here.](https://github.com/achaparro/liferay-portal/compare/9f3ec1f1cab6~2...9f3ec1f1cab6)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/90446. [See changes here.](https://github.com/achaparro/liferay-portal/compare/bd08b5101d51~3...bd08b5101d51)

**Pull request closed without merging**
