### PR TITLE
LPS-120292 Upgrade Layout table to make description CLOB

### PR DESCRIPTION
**Pull request by achaparro**
Hey @laszlopap,

Please, check this commit:
https://github.com/achaparro/liferay-portal/pull/695/commits/3c42585ed759a016cfc8c83edb323bbafdb6649b

I know that agreed to put the upgrade in 7.2.x but then I realized that if we do so, users currently in 7.3 (CE) will miss this change. For that reason, I move the upgrade to the 7.3 path and reserved a step in the 7.2 path so you can use that schema version (5.1.2) when you have to do the backport. This is the change https://github.com/achaparro/liferay-portal/pull/695/commits/3c42585ed759a016cfc8c83edb323bbafdb6649b

Apart from that, the pull was really good even taking into account that it's complex and it was your first time with these kinds of changes. Good job!

Thank you.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
Hi @laszlopap,

Can you check if the error is related to our changes? If not, can you verify if it's happening in other pull requests?

In that way we can ask QA to omit this error.

Thanks.

**Comment by achaparro** [comment]
ci:forward

**Comment by laszlopap** [comment]
Hi @achaparro !

I am on holiday until wednesday. I will check this when I came back.
Thanks for the additional commits! :) 

Regards!

**Comment by achaparro** [comment]
Ok @laszlopap, I will try to push the pull request these days in case the error is not related.

Thanks.

**Pull request closed without merging**
