### PR TITLE
LPS-109105 | master

### PR DESCRIPTION
**Pull request by vicnate5**
From https://github.com/vicnate5/liferay-portal/pull/1422

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/477.

**Comment by achaparro** [comment]
@vicnate5 the DDM team removed the upgrade today so we don't need my commit anymore
See:
https://github.com/achaparro/liferay-portal/pull/477

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/481.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/483. [See changes here.](https://github.com/achaparro/liferay-portal/compare/88ca057d4126~3...88ca057d4126)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/484. [See changes here.](https://github.com/achaparro/liferay-portal/compare/08cc3992c088~4...08cc3992c088)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/485. [See changes here.](https://github.com/achaparro/liferay-portal/compare/62b16e7ef2d9~5...62b16e7ef2d9)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/487. [See changes here.](https://github.com/achaparro/liferay-portal/compare/be229034731a~5...be229034731a)

**Pull request closed without merging**
