### PR TITLE
LPS-109105 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Catching LPS-109105

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
ci:close

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/470. [See changes here.](https://github.com/achaparro/liferay-portal/compare/c425be173b90~1...c425be173b90)

**Pull request closed without merging**
