### PR TITLE
LPS-68625

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-68625

Resend of https://github.com/achaparro/liferay-portal/pull/194

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test

**Comment by achaparro** [comment]
Hi @holatuwol,

This comes at a very opportune since we are currently doing the upgrade performance tests. I wiil include these changes in the iteration of tomorrow or Thursday.

Can the errors be related?

Thanks!

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/holatuwol/liferay-portal/pull/74. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
