### PR TITLE
LPS-95203 Ensure there's service.bundleLocation property in fileinstall configurations.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
As I told you, I don't know if this PR should be sent directly to the core team (if so, please feel free to resent it directly) or to you.

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/759. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
