### PR TITLE
LPS-77827

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-77827

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:stop

**Comment by jorgediaz-lr** [comment]
ci:stop

**Comment by jorgediaz-lr** [comment]
ci:stop

**Comment by jorgediaz-lr** [comment]
ci:stop

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55159. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
