### PR TITLE
LPS-77946

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
For more information, see: https://issues.liferay.com/browse/LPS-77946

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
After some analysis seems 6.1 version is using same format than 6.0, so we have to maintain the verify or move to 6.2 upgrade

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55484. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
