### PR TITLE
LPS-74532

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:reopen

**Comment by jcampoy** [comment]
Reopened, my changes are not related with the test failed.

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51498. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
