### PR TITLE
LPS-190861 Set CompanyThreadLocal correctly for sharding

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi @achaparro ! Here are my proposed changes to fix the on-demand admin portlet in a Sharding environment.  It is a tactical fix for this portlet only, because I think your intention is to not use a defensive strategy like setting the CompanyThreadLocal whenever there is a SB service invocation. Because cross company interactions are rare.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Hi @stian-sigvartsen,

> It is a tactical fix for this portlet only, because I think your intention is to not use a defensive strategy like setting the CompanyThreadLocal whenever there is a SB service invocation. Because cross company interactions are rare.

That's the point. Inside a service, we should not set the CompanyThreadLocal and we must rely on the current CompanyThreadLocal companyId. However I guess this API is internal and it is rare case to access to another virtual instances as administrator, can you confirm this point? If so, the changes are good.

Thanks.

**Comment by stian-sigvartsen** [comment]
Thanks for your review @achaparro . Yes I can confirm that point.

Following on from your comment, It is a shame that our SB generated APIs are polluted with `companyId` parameters that are competing with the `CompanyThreadLocal` for "single source of truth". But I understand that is legacy and changing it now is not trivial.

Once CI is green I will forward.

**Comment by stian-sigvartsen** [comment]
ci:stop

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hey @stian-sigvartsen,

Yes, we should remove the company field from our API since it is not something the user can define. We have a task fro that but it is not critical for now and since it is quite a lot of work we are postponing it. We will plan at some point for 2024.

Thanks.

**Pull request closed without merging**
