### PR TITLE
LPS-74606 Upgrade tool now fails if database has not been populated first

### PR DESCRIPTION
**Pull request by JavierMoral**

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:reopen

**Comment by JavierMoral** [comment]
ci:retest

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51557. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
