### PR TITLE
Lps 137162

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @achaparro, here is an updated PR without the issue mentioned by Victor [here](https://github.com/achaparro/liferay-portal/pull/987#issuecomment-900529434).

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:reevaluate:1267401_302

**Comment by achaparro** [comment]
Hi @SamZiemer I am closing this pull request since it is not the latest version of the changes

**Comment by achaparro** [comment]
see https://github.com/achaparro/liferay-portal/pull/990

**Pull request closed without merging**
