### PR TITLE
Lps 120146

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:foward

**Comment by SamZiemer** [comment]
ci:forward

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/samziemer/liferay-portal/pull/755. [See changes here.](https://github.com/achaparro/liferay-portal/compare/0672f24671a2~2...0672f24671a2)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/samziemer/liferay-portal/pull/756. [See changes here.](https://github.com/achaparro/liferay-portal/compare/ccfea9a92c00~1...ccfea9a92c00)

**Pull request closed without merging**
