### PR TITLE
LPS 134196

### PR DESCRIPTION
**Pull request by achaparro**
testing

### CODE REVIEW

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@vicnate5 Upgrades don't seem to be failing now, can you verify it?

Thanks!

**Comment by vicnate5** [comment]
@achaparro This looks good now.

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@zhangyan0701 can you check the results here?

**Comment by achaparro** [comment]
@zhangyan0701 if you can tell me in which databases the upgrade do not work, I will focus on that in my local tests.

Thanks.

**Comment by achaparro** [comment]
@vicnate5 @zhangyan0701 I fixed the issue with DB2:
https://github.com/achaparro/liferay-portal/pull/1012

**Comment by zhangyan0701** [comment]
There are some unique failures in this PR:

**1.  Upgrade failed from 73101 with below error:**
```
     [java] 2021-09-07 19:06:57.491 INFO  [main][UpgradeProcess:117] Failed upgrade process com.liferay.style.book.internal.upgrade.v1_2_0.StyleBookEntryVersionUpgradeProcess in 17 ms
     [java] 2021-09-07 19:06:57.498 ERROR [main][UpgradeStepRegistratorTracker:143] Failed upgrade process for module com.liferay.style.book.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Duplicate column name 'modifiedDate'
```
Example log in Testray:  https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/212/functional-upgrade-tomcat90-mysql57-jdk8/11/10/jenkins-console.txt.gz

**2. Upgrade Failed from 62, the error are different on different database:**
**DB2:** 
```
     [java] 2021-09-07 19:06:00.509 INFO  [main][UpgradeProcess:117] Failed upgrade process com.liferay.portal.upgrade.v7_0_1.UpgradeLayoutBranch in 39 ms
     [java] 2021-09-07 19:06:00.509 INFO  [main][UpgradeProcess:117] Failed upgrade process com.liferay.portal.upgrade.UpgradeProcess_7_0_1 in 65 ms
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-612, SQLSTATE=42711, SQLERRMC=LAYOUTBRANCHID, DRIVER=4.24.92
```
https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/212/functional-upgrade-tomcat90-db2111-jdk8/6/2/jenkins-console.txt.gz

**Maria DB:**
```
     [java] 2021-09-07 18:42:40.190 INFO  [main][UpgradeProcess:117] Failed upgrade process com.liferay.portal.upgrade.v7_3_x.UpgradeLayoutSet in 25 ms
     [java] 2021-09-07 18:42:40.190 INFO  [main][UpgradeProcess:117] Failed upgrade process com.liferay.portal.upgrade.PortalUpgradeProcess in 375 ms
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Key column 'head' doesn't exist in table
```
https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/212/functional-upgrade-tomcat90-mariadb102-jdk8/0/4/jenkins-console.txt.gz

**Oracle DB:**
```
     [java] 2021-09-07 18:45:43.764 INFO  [main][UpgradeProcess:117] Failed upgrade process com.liferay.portal.upgrade.v7_0_0.UpgradeResourcePermission in 114 ms
     [java] 2021-09-07 18:45:43.764 INFO  [main][UpgradeProcess:117] Failed upgrade process com.liferay.portal.upgrade.UpgradeProcess_7_0_0 in 5032 ms
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLException: ORA-01408: such column list already indexed
```
https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/212/functional-upgrade-tomcat90-oracle193-jdk8/0/13/jenkins-console.txt.gz

**PostgreSQL:**
```
     [java] 2021-09-07 19:18:35.971 INFO  [main][UpgradeProcess:117] Failed upgrade process com.liferay.portal.upgrade.v7_0_1.UpgradeLayoutBranch in 0 ms
     [java] 2021-09-07 19:18:35.972 INFO  [main][UpgradeProcess:117] Failed upgrade process com.liferay.portal.upgrade.UpgradeProcess_7_0_1 in 9 ms
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: column "layoutbranchid" of relation "layoutbranch" already exists
```
https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/212/functional-upgrade-tomcat90-postgresql11-jdk8/5/17/jenkins-console.txt.gz

**3. Failure that only happens on PostgreSQL:**
```
     [java] 2021-09-07 00:34:10.808 ERROR [main][UpgradeExecutor:250] org.postgresql.util.PSQLException: ERROR: cache lookup failed for relation 19179
     [java] org.postgresql.util.PSQLException: ERROR: cache lookup failed for relation 19179
```
https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/212/functional-upgrade-tomcat90-postgresql11-jdk8/0/7/jenkins-console.txt.gz

4. On DB2 and OracleDB, there are some warning messages like below:
`Attempting to upgrade table Layout by adding a temporary column due to: ORA-22858: invalid alteration of datatype`

https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/212/functional-upgrade-tomcat90-db2111-jdk8/0/3/jenkins-console.txt.gz
https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/212/functional-upgrade-tomcat90-oracle193-jdk8/0/7/jenkins-console.txt.gz

**Comment by zhangyan0701** [comment]
Hi @achaparro 

Sorry for the delay, cause there are different errors on different database types, it took me quite a long time to check the results and try to make sure not miss any error.

**Comment by achaparro** [comment]
No worries @zhangyan0701, this is great analysis! In the new pull I have fixed the error 2 but I will need to fix the other ones.

I will keep you posted! 

Thanks a lot!

cc/ @vicnate5

**Comment by achaparro** [comment]
The warning 4 is fine, it is a new way to recreate a column when the alter fails.

I fixed the rest of the cases and now I am testing it here:
https://github.com/achaparro/liferay-portal/pull/1015

cc/ @zhangyan0701 @vicnate5

**Pull request closed without merging**
