### PR TITLE
LPS-128867 PortletPreferences need to be added and we need to find th…

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-128867

Hey Alberto,

The issue was Asset Publishers were able to have subscriptions, but the classNameId is a PortletPreference. Unfortunately the PortletPreferences table does not have a groupId column, so we need to fetch it another way. We can fetch the groupId from the layout the asset publisher is on using the plid from the portletPreferences table.

Let me know if you think this is the right way to resolve this issue.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/851. [See changes here.](https://github.com/achaparro/liferay-portal/compare/4d140ca51be5~1...4d140ca51be5)

**Pull request closed without merging**
