### PR TITLE
Lps 107149

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @SamZiemer,

I think we are missing the semver changes, can you update the pull and execute the ci tests again?

Thanks.

**Comment by SamZiemer** [comment]
Hi @achaparro Yes, I will update and send again.

**Comment by achaparro** [comment]
Thanks @SamZiemer, I will close the pull due to the conflicts. Regarding the semver issue maybe we will need to deprecate instead of removing non internal classes but we can discuss it later.

**Pull request closed without merging**
