### PR TITLE
LPS-109105 We only need to create the release record when the initial step starts in 0.0.0

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:stop

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Testing a root level fix
https://github.com/vicnate5/liferay-portal/pull/1436

**Pull request closed without merging**
