### PR TITLE
Print the stacktrace when failing the call

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:poshi

**Comment by achaparro** [comment]
ci:test:poshi

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/404. [See changes here.](https://github.com/achaparro/liferay-portal/compare/f566fdb4b9ef~1...f566fdb4b9ef)

**Pull request closed without merging**
