### PR TITLE
LPS-99973

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-99973
https://issues.liferay.com/browse/LPS-89065

Resent from https://github.com/achaparro/liferay-portal/pull/347

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by ryannealeigh** [comment]
Hey @achaparro, I see a semver issue here. But for some reason, ant baseline-current-branch is not updating the version. Does that only work with backporting?

**Comment by achaparro** [comment]
hey @ryannealeigh,

it's quite tricky, you need to execute the following line in portal-kernel:
`ant -Dbaseline.jar.report.level=persist clean jar`

Semver for asset modules were also missing. For this case it's enough to execute this in modules:
`gradlew baseline`

I have added a commit with both. Let me finish the review and I will come back to you.

Thanks.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/577. [See changes here.](https://github.com/achaparro/liferay-portal/compare/b91cf57f312f~1...b91cf57f312f)

**Pull request closed without merging**
