### PR TITLE
LPS-86461

### PR DESCRIPTION
**Pull request by yuhai**
Hi @achaparro 

The PR extends from https://github.com/brianchandotcom/liferay-portal/pull/66109 to solve the test error.

cc @dantewang

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Sent to Brian:
https://github.com/brianchandotcom/liferay-portal/pull/66214

Thanks!

**Pull request closed without merging**
