### PR TITLE
LPS-91940

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hey @jcampoy,

Has you removed these lines for one specific reason?
https://github.com/achaparro/liferay-portal/pull/286/files#diff-b3d5e86bfab915498b41192ebfc832ecL182

**Comment by jcampoy** [comment]
Hi @achaparro 

the behaviour is the same because are added to the jvmOptionsComand and finally added to the command list, https://github.com/achaparro/liferay-portal/pull/286/files#diff-b3d5e86bfab915498b41192ebfc832ecR187

the reason was for simplifying and printing the complete jvmOption list

BR!

**Comment by achaparro** [comment]
Joder, no me había dado cuenta. La paso ahora cuando acabe la llamada.

Gracias!

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69460. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
