### PR TITLE
LPS-122786 Add JournalArticle to map

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-122786

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/744. [See changes here.](https://github.com/achaparro/liferay-portal/compare/baeeb8196b79~1...baeeb8196b79)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/745. [See changes here.](https://github.com/achaparro/liferay-portal/compare/559baab82e78~1...559baab82e78)

**Pull request closed without merging**
