### PR TITLE
LPS-82683 Upgrade column types patch front port

### PR DESCRIPTION
**Pull request by Preston-Crary**
@achaparro trying to get this fix in for the release.

Thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @Preston-Crary, @NorbertKocsis,

These changes were already addressed in master and 7.1.x by the issue https://issues.liferay.com/browse/LPS-84602, please check this class and other related modifications:
https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/upgrade/BaseUpgradeLocalizedColumn.java

Due to this, you have two options:
- Deliver your patch on demand in 7.0.x (it's not going to be really common)
- Send a pull request only for 7.0.x with your changes in the class upgrade process 7_0_6

Please, let me know your thoughs so that I can close the pull or analyze something else.

Thanks.

**Comment by Preston-Crary** [comment]
I'm fine with on demand patch for this.  Since this doesn't affect 7.2 or 7.1 it's not a release blocker so I'll downgrade the priority.

**Pull request closed without merging**
