### PR TITLE
LPS-147890 SF rule to avoid incorrect usages after this epic

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-147890

Hey @achaparro @LuisOrtiz89

We added 4 sub-checks for LPS-147890.

1. Check unnecessary if-statement
2. Check unnecessary upgrade process class
3. Check move upgrade steps into `preUpgradeSteps` when possible
4. Check move upgrade steps into `postUpgradeSteps` when possible

I also added a SF documentation to instruct with examples on how to fix SF issues when the code break those 4 checks, see [upgrade_process_check.markdown](https://github.com/ling-alan-huang/liferay-portal/blob/LPS-147890_20221108/modules/util/source-formatter/src/main/resources/documentation/check/upgrade_process_check.markdown)

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
Hey @LuisOrtiz89 
You are right, for that negative conditional case, SF code skip checking.
So we should also check the negative conditional and provide the same SF message, right?

BTW, is this SF check a `Performance` related check or `Bug Prevention` SF check?
https://github.com/achaparro/liferay-portal/blob/5a7c71d247f1ae550040d9c4f5b6657a9c8a5bd4/modules/util/source-formatter/src/main/resources/checkstyle.xml#L846

**Comment by LuisOrtiz89** [comment]
Hi @ling-alan-huang, yes, we should also check the negative conditional and provide the same SF message.

Regarding the type of SF check, it is a `Performance` related check, the portal will work in the same way with the old way of doing the upgrades than now. It is also a code standardization check, but I guess in the end all SF rules are kind of that also.

**Comment by ling-alan-huang** [comment]
Hey @LuisOrtiz89 I added addtional commits for the negative conditional.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by LuisOrtiz89** [comment]
@ling-alan-huang this looks good to me, let's wait for @achaparro to review it. He will be back on Monday.
Thanks!

**Comment by achaparro** [comment]
Sorry for the delay @ling-alan-huang, checking this now

**Comment by achaparro** [comment]
see https://github.com/ling-alan-huang/liferay-portal/pull/1500

**Pull request closed without merging**
