### PR TITLE
[TS] LPS-116699 Specify schema name when querying indexes

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-116699](https://issues.liferay.com/browse/LPS-116699)

Hi Alberto,

I hope you can review my changes.

The issue occurs when storing multiple Liferay portal schema in a single PostgreSQL database and upgrading one of the portal schemas. During the upgrade process some indexes are dropped. Later on, the verify process also selects indexes for dropping. The problem is that we don't specify the schema name from which to query the indexes, so we get back indexes already deleted from the current schema but still existing in other portal schema(s). Apparently, the attempt of dropping non-existent indexes fails.

Please let me know if you have any questions or concerns.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
@achaparro , please let me know if you think the solution can go out in an SDH.

Thank you.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
I will check it today @istvansajtos

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/641. [See changes here.](https://github.com/achaparro/liferay-portal/compare/acaad65c1718~1...acaad65c1718)

**Pull request closed without merging**
