### PR TITLE
[TECHNICAL SUPPORT] LPS-105662 Upgrade process to fix field's validation to the correct field name

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-105662

**Note:** @achaparro, this PR only has one commit related to upgrade process (https://github.com/achaparro/liferay-portal/pull/434/commits/829df299089eea83f74fa6852fdbb432934ebe43).

**Porting related question:** Since this will need to be backported all the way to 7.1.x, I'm guessing we're gonna have to include a _DummyUpgradeStep_ from **2.0.6** to **2.0.7** in the 7.2.x backport for this to work. Is my assumption correct?

Thanks for reviewing this.
Best.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:upgrade

**Comment by yichenroy** [comment]
ci:test:upgrade

Network issues, restarting test.

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @rodrigopaulino,

Does the upgrade need to be executed for customers in both branches? I mean 7.1.x and 7.2.x, or the issue is solved for customers in 7.2.x?

If so,  in master and 7.2.x we will need to set this upgrade process as the last one for 7.2.x, from 3.2.1 to 3.2.2 and move the others since we can do it because they haven't been released yet (we have to act fast before the 7.3 release)

Apart from that, and as you suggested, we have to include a DummyUpgradeStep from 2.0.6 to 2.0.7 in 7.2.x and in master too (in that way we will reserve that step) so we can add the upgrade process in that point for 7.1.x branch.

To be able to do this we have to be sure that this upgrade process can run twice since that will happen for customers upgrading from 7.1.x once we backport this. Is that safe in this case? If possible, can you add some logic to avoid to run most of the queries and improve the performance in that way, if that's not possible, but the upgrade process is safe to be executed twice, we can go ahead tomorrow and send the pull. I will do it first thing in the morning.

Thanks!

**Comment by rodrigopaulino** [comment]
Hi, @achaparro.

> Does the upgrade need to be executed for customers in both branches? I mean 7.1.x and 7.2.x, or the issue is solved for customers in 7.2.x?

Yes, they need to be executed in both branches. The bug happens across all versions, starting from 7.1.

> If so, in master and 7.2.x we will need to set this upgrade process as the last one for 7.2.x, from 3.2.1 to 3.2.2 and move the others since we can do it because they haven't been released yet (we have to act fast before the 7.3 release)

The reason why I put the upgrade process from 3.2.2 to 3.2.3 is because we have to backport to 7.2.x first the upgrade process before this new one. Not only that other upgrade process needs to run on customers using 7.2.x regardless of this bug but this new upgrade process depends on it. Can we stick to 3.2.3 for this new upgrade process?

> Apart from that, and as you suggested, we have to include a DummyUpgradeStep from 2.0.6 to 2.0.7 in 7.2.x and in master too (in that way we will reserve that step) so we can add the upgrade process in that point for 7.1.x branch.

It totally makes sense. Thanks for clarifying that.

> To be able to do this we have to be sure that this upgrade process can run twice since that will happen for customers upgrading from 7.1.x once we backport this. Is that safe in this case? If possible, can you add some logic to avoid to run most of the queries and improve the performance in that way, if that's not possible, but the upgrade process is safe to be executed twice, we can go ahead tomorrow and send the pull. I will do it first thing in the morning once you include the new changes.

Yes, the upgrade process is safe to run twice, but I can put some more work to make it "not executable" for not needed cases too. I'll work on that.

Thanks for your feedback! It helped a lot.

**Comment by achaparro** [comment]
Hi @rodrigopaulino,

Regarding this:
> The reason why I put the upgrade process from 3.2.2 to 3.2.3 is because we have to backport to 7.2.x first the upgrade process before this new one. Not only that other upgrade process needs to run on customers using 7.2.x regardless of this bug but this new upgrade process depends on it. Can we stick to 3.2.3 for this new upgrade process?
Ok, then you are right, we can put it in from 3.2.2 to 3.2.3

The rest is clear, I will wait for the pull to send it as fast as possible to the next reviewer.

Thanks!

**Pull request closed without merging**
