### PR TITLE
Lps 124518

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-124518

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @SamZiemer, @kevhlee,

First of all, sorry for the delay reviewing this. The changes look really good :-) but the new test is failing in the CI:
https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/468387//testReport/com.liferay.data.cleanup.test/UpgradeExpiredJournalArticleTest/testUpgradeExpiredJournalArticle

I am going to take a look since you sent the pull 2 weeks ago but please, review the test results next time.

Thanks.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/kevhlee/liferay-portal/pull/9. [See changes here.](https://github.com/achaparro/liferay-portal/compare/9d3c021a07a0~2...9d3c021a07a0)

**Pull request closed without merging**
