### PR TITLE
LPS-79878

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by achaparro** [comment]
Hi @jonathanmccann,

This process was included in 6.1EE GA3:
https://issues.liferay.com/browse/LPS-29879

Since we allow direct upgrades from any version of 6.1.x, could you move this logic to an upgrade process in the path UpgradeProcess_6_2_0?

Thanks!

**Comment by jonathanmccann** [comment]
I will close this for now since this verify has a lot of logic that will need to be converted.

**Pull request closed without merging**
