### PR TITLE
LPS-132020

### PR DESCRIPTION
**Pull request by kevhlee**
**Ticket:**
<https://issues.liferay.com/browse/LPS-132020>

**Notes:**
This implementation utilizes the `PersistenceManager` API, specifically `ConfigurationPersistenceManager`, to set the configuration values to `false` after the data clean-up and removal tasks are executed. Let me know if there's anything I need to add or modify.

As a note, deleting the configuration information using `PersistenceManager#delete(String pid)` is an alternative approach that works. However, it would change the behavior of how the `Data Cleanup` and `Data Removal` configuration values are written to their corresponding OSGi configuration files. At the moment, the default behavior is that the current configuration values would be written to the files prior to DXP shutting down. However, because the configuration information is being deleted, the files would not get written and the values prior to startup would be preserved. So, if a user were to restart the portal without editing the files, then the clean-up and removal tasks would be run again.

Based on the goal of [LPS-132020](https://issues.liferay.com/browse/LPS-132020), I think this is not the behavior we want. With the implementation I'm proposing, the configuration values in the files would be written to `false`. And so users would not have to worry about re-running the clean-up and removal tasks. Let me know if you think otherwise and I can send another pull request.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hey @achaparro, I think I need to push one more commit as I think I'm missing a case where some of the configuration values need to be updated during component activation.

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
Hey @achaparro,

As I mentioned earlier, I will need to add a commit to make sure that certain configuration values are updated upon component activation (this is why the tests failed). I also discovered strange behavior with the UI whenever the data cleanup/removal tasks are run. So for now, I'll be closing this pull request.

**Comment by achaparro** [comment]
ok @kevhlee!

**Pull request closed without merging**
