### PR TITLE
LPS-114387 DBPartition: use schema name prefix property with a default value to make it optional

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@vicnate5 the previous error in the CI seems unrelated but, can you verify it?

Thanks.

**Comment by vicnate5** [comment]
@achaparro yea, those tests are flaky...

**Comment by vicnate5** [comment]
@achaparro Go ahead and manually forward.

@alexcandidos Is there a known issue with the App Builder tests? it was different tests failing each time. We only ran the App Builder tests here because of the relevant properties limitation (https://issues.liferay.com/browse/LRCI-1398)

**Comment by achaparro** [comment]
thank you for the explanation @vicnate5 :-)

**Comment by alexcandidos** [comment]
Hey @vicnate5 , I don't know what happened for these tests fail (maybe these are flaky on CI), but there is no known issue as you can see here in the [app-builder](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1226329229&testrayComponentId=871640652) test routine.

**Pull request closed without merging**
