### PR TITLE
LPS-90417 Only rely on content as fallback. If title is xml rely on title, if not try to see if content has a default-language attribute.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
Hi @achaparro,
 this is very important. With the previous solution in case it's a non basic web content that has an internationalized title we're discarding that option as a valid way to retrieve the default language id.
Kind regards.

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hey @marianoalvarosaiz,

I've been thinking about this, since in most of the cases the title contains the default language, could we only get the content when the title is not a XML? In this way the performance would be better for most of the cases.

Let me know your opinion about this.

Thanks.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/marianoalvarosaiz/liferay-portal/pull/173. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68327. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
