### PR TITLE
[TS]LPS-93431

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-93431

Resent from https://github.com/achaparro/liferay-portal/pull/293

Hey Alberto,

I've made the changes you asked for on the previous PR (fixed the initial upgrade process and added a check before altering the column).  I've tested the following scenarios on Sybase and confirmed they work as intended:
Upgrade from 6.2 (using revised 1.0.2 upgrade process)
Upgrade from 6.2 (using 2.1.1 upgrade process)
Upgrade from master (column is already upgraded, so nothing happens)

As far as testing on all DB types, I did some research and found nothing explicitly preventing the conversion of VARCHAR to DECIMAL, BIGINT, etc.  The only stipulation is the current data (if any) must be convertible.  If it isn't, some DBs will throw errors while others leave a null value (if the column allows for null).  In either case, the versionUserId value should always be convertible, so there should be no issues.  I can manually double-check on each DB type too if needed.

Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/ChrisKian/liferay-portal/pull/131. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
