### PR TITLE
LPS-79874 Remove unnecessary verifications from BlogsServiceVerifyProcess added by LEP-3865 and LPS-40614. No longer necessary due since the bad data only exists in versions prior to 6.1.

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
Hi @jonathanmccann,

Could you take a look a this error? It seems related but I don't know how this table is not created:
 Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lportal.BlogsEntry' doesn't exist

Thanks.

**Comment by jonathanmccann** [comment]
Looking at the changes you made here:

https://github.com/brianchandotcom/liferay-portal/pull/57431/commits/68d2e13d9c39ee3e099d19aa0079e30fbfacf3b6

This file can be completely removed. Once yours is committed, I'll rebase and do that unless you have an objection.

**Comment by achaparro** [comment]
Hi @jonathanmccann,

Yes please, resend.

Thanks!

**Comment by jonathanmccann** [comment]
https://github.com/achaparro/liferay-portal/pull/178

**Pull request closed without merging**
