### PR TITLE
LPS-125637 #p_p_id portlet references in custom css are not upgraded from 6.2

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-125637

**Implementation notes**

- This issue is similar to https://issues.liferay.com/browse/LPS-118902 but instead of replacing the portletId in the `#portlet_` styles, we have to also replace it in the `#p_p_id_` styles
- After the https://issues.liferay.com/browse/LPS-122562 code changes, it is also necessary to do some additional changes in the BaseUpgradePortletId class, see https://github.com/achaparro/liferay-portal/commit/7d887de6c293b0ec8f216c0cf34e05ed072fa924#diff-fe9beec00e5996c4155b9fc06f206351c6aadb200d925d7b57b3df41b3686feaR339-R344
- I have also have some problems with the https://issues.liferay.com/browse/LPS-122562 code changes, after that LPS the upgrade is not working correctly, I have applied some commits in order to be able to test my changes, see: https://github.com/achaparro/liferay-portal/commit/f050e0db877a530b63c24e40d33c172443541061, https://github.com/achaparro/liferay-portal/commit/5d6737e76b7b47aedb7bf2595118c82d48ba7c65, https://github.com/achaparro/liferay-portal/commit/f44ad154838a4135f0362510abdf8f42a406f393 and https://github.com/achaparro/liferay-portal/commit/2601d1bfbbae792e9cb598b7f5d58feefea997f2

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
