### PR TITLE
[TECHNICAL-SUPPORT] LPS-44965 VerifyOracle should reduce columns in 6.1.20 and above if you come from 5.2.9 or from 6.0.5 to 6.1.10

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-44965

Here it is.
Please, take care of the further review and pass it forward to Miguel if you agree.

Thx,
Tibi

/cc @istvansajtos

### CODE REVIEW

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hey @istvansajtos,

We can not remove this check:
https://github.com/lipusz/liferay-portal/commit/1c6d53fefb8674e4e88f586de4a11dca261363d5

Since we need to modify just Liferay tables. If we remove it, the verify process could modify:
- Quartz tables.
- Tables generated by the customer using service Builder
- Other customer tables in the same schema.

We need other way to get all Liferay tables (in the core or OSGI modules)

Thanks.

**Comment by istvansajtos** [comment]
Alberto, you are right, we shouldn't remove that check. Thinking about this problem raised some other questions:
* Some initially separate plugins (e.g. Kaleo) were integrated as modules on trunk while other plugins (e.g. Chat portlet) weren't. The non-integrated official plugins should be handled too, right?
* How can we differentiate official plugin tables which need correction from custom plugin tables which don't? This doesn't seem to be possible.

I can't think of a clever solution that handles all those questions. What do you think?

Thank you!

**Comment by lipusz** [comment]
Hey Guys,

Have you managed to reach a consensus?

@achaparro @istvansajtos

**Comment by achaparro** [comment]
Hey @lipusz,

I will answer tomorrow about it. Since the customer already has a patch is not so critical. Perhaps I will need to talk to Miguel or Carlos Sierra and he comes back from DevCon on Mnonday.

Cheers.

**Comment by lipusz** [comment]
:+1: 
Thanks for the prompt reply.
I know it's not urgent, but I also want to avoid creating backlog. It's already a backlog anyway... :-/

**Comment by istvansajtos** [comment]
Hi @achaparro,

I hope you are doing well. Did you manage to reach Miguel or Carlos in connection with this?

Many thanks!

**Comment by achaparro** [comment]
Hi @istvansajtos,

Sorry for the late response but yesterday was a day off here in Spain.

After talking to @migue, we agreed to remove this verify class in master since it does not make sense to try to fix it in every new Liferay version since the problem is old and, also, it adds unnecessary complex logic difficult to mantain. Instead, we will create an upgrade process from 6.2 to 7 which does the same. To achieve it we have to add an array with all table names (existing tables when the bug was present in the code, from LPS-12048 to LPS-25861) so we can check it prior to modify a field (we can not use _isPortalTableName_ anymore)

Regarding the plugins, we will keep the logic just for portal tables for now.

Could you take care of this and send me a pull request once you have finished?

Let me know if you have any doubt about it.

Thanks!
PS: we will commit this as Verify in 6.2.

**Comment by lipusz** [comment]
Closing as per Alberto's comment.

@istvansajtos Please, proceed as Alberto advised. Thx!

**Pull request closed without merging**
