### PR TITLE
LPS-77101 Make sure upgrade process is triggered even for those who are already on 7.0

### PR DESCRIPTION
**Pull request by jonathanmccann**
In reference to https://github.com/liferay/liferay-portal-ee/pull/4610

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54979. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Thanks @jonathanmccann !

**Pull request closed without merging**
