### PR TITLE
[Technical Support] LPS-78519 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Reference:
https://issues.liferay.com/browse/LPS-78519

Regards,
Sergio.

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test

**Comment by samanzanedo** [comment]
ci:retest

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56284. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
