### PR TITLE
LPS-107816

### PR DESCRIPTION
**Pull request by jesseyeh-liferay**
**[LPS-107816](https://issues.liferay.com/browse/LPS-107816)**

**Previous pull requests**: https://github.com/achaparro/liferay-portal/pull/894 > https://github.com/achaparro/liferay-portal/pull/896 > https://github.com/achaparro/liferay-portal/pull/902 > https://github.com/achaparro/liferay-portal/pull/937

> This changes the type of the version column in KaleoDefinitionVersion from a String to an int.

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by jesseyeh-liferay** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:stop

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:reevaluate:1277401_160

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Sorry for the delay but other critical issues came up.

I have checked the logs and the upgrade is executed successfully, I am going to send the pull to the workflow team solving the conflicts first and we can analyze there the situation.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/liferay-workflow/liferay-portal/pull/449. [See changes here.](https://github.com/achaparro/liferay-portal/compare/ea3eecf995ef~2...ea3eecf995ef)

**Pull request closed without merging**
