### PR TITLE
LPS-129575 Software Catalog cleanup

### PR DESCRIPTION
**Pull request by achaparro**
Hi @kevhlee,

I know it was not easy to know the kind of objects we need to remove for this case so, good work! :-)

I just added two relevant commits, please take a look at them and let me know if they make sense to you.

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:forward

**Comment by kevhlee** [comment]
Hey @achaparro,

Thanks for reviewing my changes! For the most part, the changes you added look good though I have one concern/uncertainty.

Based on this commit <https://github.com/achaparro/liferay-portal/pull/971/commits/2cf5920a51683ebbd39137740ea8f2132a67f811>, shouldn't we remove `"com.liferay.softwarecatalog.service"` from `_BUNDLE_SYMBOLIC_NAMES` so that we don't automatically create the entry in the table? With commit <https://github.com/achaparro/liferay-portal/pull/971/commits/971482bc651a5a9a63dde2c66f3ffc054b61ba72>, I added `"com.liferay.softwarecatalog.service"` to `_BUNDLE_SYMBOLIC_NAMES` in `v7.4.0/UpgradeModules.java` to always make sure Software Catalog would be in the Release_ table.

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @kevhlee,

Let's discuss it in the call today.

**Comment by achaparro** [comment]
ci:stop

**Pull request closed without merging**
