### PR TITLE
[TS] LPS-135622 Remove old CalEvent classNameId entries from ExpandoTable

### PR DESCRIPTION
**Pull request by joseluisbango**
Hello @achaparro, 

This is similar to  [LPS-112455](https://issues.liferay.com/browse/LPS-112455 ) changes. 
We need to remove old _CalEvent classNameId_ entries from _ExpandoTable_ and all the related entries from _Expando*_ tables (_ExpandoColumn_, _ExpandoValue_ and _ExpandoRow_).

Please let me know if you have any questions.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by joseluisbango** [comment]
Hi @achaparro, the error seems to be related with the semantic versioning in portal-impl module, but I haven't make changes in that module and I cannot find the relationship.
How should I proceed?

Thank you

**Comment by achaparro** [comment]
Hi @joseluisbango,

I think it is fine, I got similar issues yesterday. We can re-execute the relevant tests. I will review the pull in deep later today or Monday morning.

Thanks!

**Comment by achaparro** [comment]
ci:reevaluate:1277401_310

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @joseluisbango,

In [LPS-65075](https://issues.liferay.com/browse/LPS-65075) we implemented a process to migrate all references to the old _CalEvent_ to the new _CalendarBooking_ including expando:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/archived/calevent-importer/src/main/java/com/liferay/calevent/importer/internal/verify/CalEventImporterVerifyProcess.java#L1088

However we recently archived that process in [LPS-106466](https://issues.liferay.com/browse/LPS-106466) so it is not included in the release anymore.

Can you deploy that module calevent-importer in your installation and verify if it solves the issue? I would prefer this solution since with changes we are removing the records but not migrating them to the new Calendar object (correct me if I am wrong)

In case it works, we should deliver that module to the customer and, additionally, make a decision about publish it again in the release or just create Help Center article where we attach the module and document the issue.

Thanks.

**Comment by joseluisbango** [comment]
Hi @achaparro,

Thanks for your explanation! 

I was aware of that problem (losing custom fields), see [this comment](https://issues.liferay.com/browse/LPS-135622?focusedCommentId=2483983&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2483983), but I can see your point. I will do the test you suggest and let you know the results.

Regards.

**Comment by achaparro** [comment]
Hi @joseluisbango,

Perfect, let's wait for the results. I will keep this pull request open until then.

Thanks.

**Comment by achaparro** [comment]
We will finally deliver this as SDH only for the customer

**Pull request closed without merging**
