### PR TITLE
 [TS] LPS-122913 Remove old CalEvent classNameId entries from Subscription table

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-122913

This is similar to https://issues.liferay.com/browse/LPS-112455 changes, just deleting the old CalEvent entries from Subscription table

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/ChrisKian/liferay-portal/pull/275.

**Pull request closed without merging**
