### PR TITLE
LPS-107255 Output of TextFormatter#formatStorageSize is not localised

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @achaparro

could you please review my changes and push it forward?

Thanks, Roland

### CODE REVIEW

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/8783.

**Comment by achaparro** [comment]
Hi @rolandpakai,

Regarding the comment made by @ericyanLr here:
https://github.com/ericyanLr/liferay-portal/pull/147#issuecomment-579001518

I don't have a strong opinion about which option is better, both make sense to me, so I kept the pull with your original changes.

Thanks.

**Comment by rolandpakai** [comment]
Thank you @achaparro :)

**Pull request closed without merging**
