### PR TITLE
LPS-107816

### PR DESCRIPTION
**Pull request by jesseyeh-liferay**
**[LPS-107816](https://issues.liferay.com/browse/LPS-107816)**

**Previous pull requests**: https://github.com/achaparro/liferay-portal/pull/894 > https://github.com/achaparro/liferay-portal/pull/896

> This changes the type of the version column in KaleoDefinitionVersion from a String to an int.

**Changelog**:
* Resolve additional test failures
* Update additional usages

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
I'm not sure if https://github.com/achaparro/liferay-portal/pull/902/commits/27a67914f0647096b1254038a55ca38377a61f9f is necessary, as the tests still passed without this change.

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by jesseyeh-liferay** [comment]
ci:test:upgrade

**Comment by jesseyeh-liferay** [comment]
ci:stop

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by jesseyeh-liferay** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/liferay-workflow/liferay-portal/pull/374. [See changes here.](https://github.com/achaparro/liferay-portal/compare/1dd074fe7a17~1...1dd074fe7a17)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/liferay-workflow/liferay-portal/pull/375. [See changes here.](https://github.com/achaparro/liferay-portal/compare/675619e4e0ae~2...675619e4e0ae)

**Pull request closed without merging**
