### PR TITLE
LPS-119275 Add a CAST_TEXT to Sybase using DBTypeToSQLMap to avoid problems with that database

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-119275

Same change than https://github.com/achaparro/liferay-portal/pull/683 but applying it only to Sybase using DBTypeToSQLMap

/cc @ricardocousolr

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
@achaparro I have added two commits https://github.com/achaparro/liferay-portal/commit/9698457d7854c0470542f2bf9f9059824d1cd069 and https://github.com/achaparro/liferay-portal/commit/310b7dc6dbe539b07c990757c4db64656b72919a

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
