### PR TITLE
Lps 109525 added commits

### PR DESCRIPTION
**Pull request by SamZiemer**
Hey @achaparro,

I'm sending you this pull since it changes a core upgrade class and is not so related to Adolfo's component area.

The idea here is we add an extra element to the name array, if this 3rd element is present, we will skip deleting that class, or classes depending on the wildcardMode selected for the upgrade.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @SamZiemer,

There are some tests which failed, please be sure that any of them is related and let me know. After that, I will review the pull, exclude tests and execute the ci tests again.

Thanks.

**Comment by SamZiemer** [comment]
Hi @achaparro,

I just looked through the failing tests and I do not believe any of the failures are caused by these changes.

**Comment by achaparro** [comment]
Ok @SamZiemer, I am currently trying to pass other pull with similar issues, once I get it, I will be able to exclude the same tests in this pull too.

Thanks.

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/528. [See changes here.](https://github.com/achaparro/liferay-portal/compare/bf43132aa808~1...bf43132aa808)

**Pull request closed without merging**
