### PR TITLE
LPS-111719 Avoid to execute the update when there are not matching records

### PR DESCRIPTION
**Pull request by achaparro**
@samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hey @Vicnate5, I have checked the issues and they don't see related, can you tell me if they are unique to this pull?

Thanks

**Comment by vicnate5** [comment]
@achaparro The poshi test has failed for this reason randomly before, it is strange it failed here twice (which means 4 times in a row since we auto-rerun functional tests). There is a slight change to wiki here, so I am not sure with the info right now.

The other test failure is unrelated. It is a race condition: https://issues.liferay.com/browse/LPS-110102

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Thanks @vicnate5, let's wait for the next results, if it fails again I will review it again, if after that I don't get any clue, I will send a different pull request for wiki changes to compare.

**Comment by achaparro** [comment]
See https://github.com/achaparro/liferay-portal/pull/561

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hey @vicnate5,

Can you share with me the steps to reproduce the test LocalFile.WorkflowWiki#ApproveFrontPageUserEdit locally?

Thanks.

**Comment by achaparro** [comment]
Testing here again:
https://github.com/achaparro/liferay-portal/pull/562

**Pull request closed without merging**
