### PR TITLE
LPS-69509 Apply multi table delete syntax for MySQL so that indexes are not ignored.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
Tests failing are same as in https://github.com/arboliveira/liferay-portal/pull/168

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Done

**Pull request closed without merging**
