### PR TITLE
[TECHNICAL-SUPPORT] LPS-92509

### PR DESCRIPTION
**Pull request by SamZiemer**
cc/@matthewchan123

Notes from Matthew:
> https://issues.liferay.com/browse/LPS-92509
> 
> This PR address an error in the DB2 upgrade process where tables fail to be dropped. The functionality of the command [DROP_TABLE_IF_EXISTS](https://github.com/liferay/liferay-portal/blob/dfeea96b35f2700cd1d927190c403c490f36cb3c/sql/update-6.2.0-7.0.0.sql#L13-L15) was not added for DB2 database language, and is noticeable when upgrading from 6.2 to 7.0 for tables AssetTagProperty, CyrusUser, and CyrusVirtual, where error -104 is shown and the tables incorrectly remain in database after the upgrade.
> 
> The proposed fix implemented in this PR is to add a method overriding replaceDropTableIfExistsText for DB2SQLTransformerLogic.java adjusted to DB2's specific SQL syntax. This solution takes inspiration from the OracleSQLTransformerLogic.java method [replaceDropTableIfExistsText](https://github.com/liferay/liferay-portal/blob/dfeea96b35f2700cd1d927190c403c490f36cb3c/portal-impl/src/com/liferay/portal/dao/sql/transformer/OracleSQLTransformerLogic.java#L69-L85) which also overrides the [default function](https://github.com/liferay/liferay-portal/blob/dfeea96b35f2700cd1d927190c403c490f36cb3c/portal-impl/src/com/liferay/portal/dao/sql/transformer/BaseSQLTransformerLogic.java#L222-L224) of same name in BaseSQLTransformerLogic.java class.
> 
> With the inclusion of this change, the three aforementioned tables are successfully removed from DB2 and throw no exceptions should they not have existed beforehand. Future upgrade scripts for this database language that drop tables are affected by the fix as well.
>
> It seems the best implementation is to use this continue handler as it is native DB2 SQL PL. Writing a code block the oracle way requires an extra plugin for DB2 which [isn't enabled by default](https://stackoverflow.com/questions/27982019/an-unexpected-token-exception-was-found-in-pl-sqldb2). Thus, since we can't know for certain whether a client has PL/SQL support, I think we should stick to the exception handler as is.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Sorry for the delay @SamZiemer, I will finish the review tomorrow.

Thanks.

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70914. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Good job @matthewchan123 !

**Pull request closed without merging**
