### PR TITLE
LPS-87023 Initialize the release

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hey @vicnate5, do you find any issue in the recent results?

Thanks!

**Comment by vicnate5** [comment]
@achaparro Looks a lot better now. The failures are not related to this pull.

**Pull request closed without merging**
