### PR TITLE
LPS 134196

### PR DESCRIPTION
**Pull request by achaparro**
testing

### CODE REVIEW

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hi @vicnate5,

We are getting unrelated sf and semver errors, what do you think about it?

Thanks

**Comment by vicnate5** [comment]
@achaparro Lots of real failures here.

All the upgrade tests in Relevant failed.

Run upgrade on this dump from 7.2.10 to see the issue: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.2.10/data-archive/data-archive-portal-mysql.zip

```
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '20111-0' for key 'PRIMARY'
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:111)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:173)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:136)
     [java] 	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:172)
     [java] 	at com.liferay.portal.tools.DBUpgrader._upgradePortal(DBUpgrader.java:375)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:161)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:153)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:129)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54)
     [java] Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '20111-0' for key 'PRIMARY'
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:111)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:133)
     [java] 	at com.liferay.portal.upgrade.PortalUpgradeProcess.doUpgrade(PortalUpgradeProcess.java:137)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.lambda$upgrade$0(UpgradeProcess.java:105)
     [java] 	at com.liferay.portal.db.partition.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:110)
     [java] 	at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:444)
     [java] 	at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:290)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:92)
     [java] 	... 12 more
     [java] Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '20111-0' for key 'PRIMARY'
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
     [java] 	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335)
     [java] 	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2108)
     [java] 	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
     [java] 	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:117)
     [java] 	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
     [java] 	at com.liferay.portal.dao.db.BaseDB.runSQL(BaseDB.java:501)
     [java] 	at com.liferay.portal.dao.db.BaseDB.runSQL(BaseDB.java:467)
     [java] 	at com.liferay.portal.kernel.dao.db.BaseDBProcess.runSQL(BaseDBProcess.java:71)
     [java] 	at com.liferay.portal.kernel.upgrade.CTModelUpgradeProcess._upgradeCTModel(CTModelUpgradeProcess.java:122)
     [java] 	at com.liferay.portal.kernel.upgrade.CTModelUpgradeProcess.doUpgrade(CTModelUpgradeProcess.java:47)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.lambda$upgrade$0(UpgradeProcess.java:105)
     [java] 	at com.liferay.portal.db.partition.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:110)
     [java] 	at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:444)
     [java] 	at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:290)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:92)
     [java] 	... 19 more
 ```
Full log https://testray.liferay.com/reports/production/logs/2021-09/test-1-31/test-portal-acceptance-pullrequest(master)/180/functional-upgrade-tomcat90-mysql57-jdk8/0/8/jenkins-console.txt.gz

**Pull request closed without merging**
