### PR TITLE
LPS-130274

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:stop

**Comment by marianoalvarosaiz** [comment]
See https://github.com/achaparro/liferay-portal/pull/870

**Comment by marianoalvarosaiz** [comment]
I've sent a new pull and tried to forwarded from there, as this one seems stuck.

**Pull request closed without merging**
