### PR TITLE
Lps 113083 2

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @achaparro,

I've added the commit to update the LayoutPrototype default locale name as well as the name we add to LayoutTemplatePageEntry

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
@SamZiemer, this pull request is good the be forward, the tests passed. I will review it and send it today

Thanks.

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/238.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/dacousalr/liferay-portal/pull/239.

**Pull request closed without merging**
