### PR TITLE
Lps 107149

### PR DESCRIPTION
**Pull request by SamZiemer**
resent from https://github.com/achaparro/liferay-portal/pull/438

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
@SamZiemer I think we would need to apply the same than here:
https://github.com/brianchandotcom/liferay-portal/pull/79952/commits/ce0fcd7b9cd2cf770de85b2ce1874a0e90690e2c

To solve the issues with the dependencies.

Anyway, and after checking the pull I have seen that we are creating several major changes and I think we can't do major modifications now we are not on time to do it for the 7.3 release so we will need to deprecate instead of remove non-internal things.

Maybe we need to separate:
- Untie verfiers from the upgrade (for 7.3.x)
- Removal of the verified column (for a future 7.4.x)

Let's review the pull tomorrow morning.

**Comment by achaparro** [comment]
Just started reviewing :)

**Pull request closed without merging**
