### PR TITLE
[TS] LPS-93431

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-93431

Resent from https://github.com/ChrisKian/liferay-portal/pull/131

I've changed the _getColumnDataType() method to compare using the  dataType string provided and the DB.  Before, if would compare the ModelTable.class to the DB, which would be incorrect for the specific bug we are trying to fix.

I've tested and an confirm the new method works as intended.  Please let me know if there is anything else I can do.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hi @ChrisKian,

I would like to analyze this code in deep since we use that method in several points of the upgrade process. However I am on vacation until next Monday, is that ok to you?

Don't block the solution for the customer, please deliver a SDH with the first solution you made with the check of the existence of the field.

Thanks!

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @ChrisKian,

First of all, sorry for the delay.

I am not sure that this can work all cases, picture the following case:
- We need to check if the following field has the proper type in the database:
https://github.com/liferay/liferay-portal/blob/master/sql/portal-tables.sql#L66

And take into account which means STRING in every database based on the types template:
	protected static final String[] TEMPLATE = {
		"##", "TRUE", "FALSE", "'01/01/1970'", "CURRENT_TIMESTAMP", " BLOB",
		" SBLOB", " BOOLEAN", " DATE", " DOUBLE", " INTEGER", " LONG",
		" STRING", " TEXT", " VARCHAR", " IDENTITY", "COMMIT_TRANSACTION"
	};
	private static final String[] _POSTGRESQL = {
		"--", "true", "false", "'01/01/1970'", "current_timestamp", " oid",
		" bytea", " bool", " timestamp", " double precision", " integer",
		" bigint", " text", " text", " varchar", "", "commit"
	};

	private static final String[] _MYSQL = {
		"##", "1", "0", "'1970-01-01'", "now()", " longblob", " longblob",
		" tinyint", " datetime(6)", " double", " integer", " bigint",
		" longtext", " longtext", " varchar", "  auto_increment", "commit"
	};

	private static final String[] _HYPERSONIC = {
		"//", "true", "false", "'1970-01-01 00:00:00'", "now()", " blob",
		" blob", " bit", " timestamp", " double", " int", " bigint",
		" longvarchar", " longvarchar", " varchar", "", "commit"
	};

	private static final String[] _SQL_SERVER = {
		"--", "1", "0", "'19700101'", "GetDate()", " image", " image", " bit",
		" datetime2(6)", " float", " int", " bigint", " nvarchar(4000)",
		" nvarchar(max)", " nvarchar", "  identity(1,1)", "go"
	};	

	private static final String[] _ORACLE = {
		"--", "1", "0",
		"to_date('1970-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')", "sysdate",
		" blob", " blob", " number(1, 0)", " timestamp", " number(30,20)",
		" number(30,0)", " number(30,0)", " varchar2(4000 char)", " clob",
		" varchar2", "", "commit"
	};

	private static final String[] _SYBASE = {
		"--", "1", "0", "'19700101'", "getdate()", " image", " image", " int",
		" bigdatetime", " float", " int", " decimal(20,0)", " varchar(4000)",
		" text", " varchar", "  identity(1,1)", "go"
	};

	private static final String[] _DB2 = {
		"--", "1", "0", "'1970-01-01-00.00.00.000000'", "current timestamp",
		" blob", " blob", " smallint", " timestamp", " double", " integer",
		" bigint", " varchar(4000)", " clob", " varchar",
		" generated always as identity", "commit"
	};	

Now, what should we do?
1. hasColumnType(AnnouncementsEntry.class, "url", "CLOB null")
2. hasColumnType(AnnouncementsEntry.class, "url", "LONGVARCHAR null")
3. hasColumnType(AnnouncementsEntry.class, "url", "VARCHAR(4000) null")

My guess is that #1 will work for _POSTGRESQL, #2 for mysql and hypersonic and #3 for the rest of the databases.

If this is true, this solution is not valid and we are going to need something like this:
1. hasColumnType should only accept value from previous template:
	protected static final String[] TEMPLATE = {
		"##", "TRUE", "FALSE", "'01/01/1970'", "CURRENT_TIMESTAMP", " BLOB",
		" SBLOB", " BOOLEAN", " DATE", " DOUBLE", " INTEGER", " LONG",
		" STRING", " TEXT", " VARCHAR", " IDENTITY", "COMMIT_TRANSACTION"
	};

2. Transform that value in the proper one for every database.
3. Transform that value in the equivalent for Types class.
4. Then compare with the database value.

What do you think? It's going to be more complex but it's the only way to ensure that it will work for all databases and we also simplify the call this method because we will use our template of types.

Thanks.

**Comment by achaparro** [comment]
Hey @ChrisKian,

Don't worry about these changes, they are related to the upgrade framework so I will work on it as soon as possible. If you still want to analyze the previous example and provide a solution, that's good but I understand that you have other duties with User's component.

Thanks.

**Comment by ChrisKian** [comment]
Hey @achaparro,

I think it's a good idea, and it makes sense to me.  I am currently pretty busy though, and think you would be better suited to resolve the issue.

If I have extra time to work on this issue, I will, otherwise, you should assume it's on your plate now.  

Thanks, and let me know if this is alright or if there is anything I can assist with.

**Pull request closed without merging**
