### PR TITLE
Lps 72046 addtional commits

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @achaparro,

This is an additional commit for LPS-72046. The first commits did not actually solve the problem as the portlet IDs are never removed from the portlet table, so the hasPortletIds method will always return true. I have added a new method to check the release table if there is no entry we will run the upgrade.

I have also applied the same pattern to BaseUpgradeServiceModuleRelease as there are a few modules that use this class resulting in the same problem of upgrades running each time portal starts up.

Let me know if there are any questions.
Sam

### CODE REVIEW

**Comment by achaparro** [comment]
Hey @SamZiemer,

I will check it today or tomorrow.

Thanks!

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @SamZiemer,

For which web modules the portletId does not change in portlet table? It should if you check this:
https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/upgrade/BaseUpgradePortletId.java#L406

If there is a bug in one specific web module, we should fix it instead of changing the logic for all of them.

Thanks.

**Comment by SamZiemer** [comment]
Hi @achaparro,

The original fix did not alter the behavior, all of the web module upgrades were still running each time the portal starts up. 

From what I understand the only reason we would need to run the baseUpgradeWebModule or baseUpgradeServiceModule upgrades is if there are no entries in the release table for a module. So it seems to me checking for the existence of an entry in the release table first before running the upgrade prevents any extra logic from running that does not need to.

**Comment by achaparro** [comment]
Hi @SamZiemer,

This could be true:
> From what I understand the only reason we would need to run the baseUpgradeWebModule or baseUpgradeServiceModule upgrades is if there are no entries in the release table for a module. So it seems to me checking for the existence of an entry in the release table first before running the upgrade prevents any extra logic from running that does not need to.

But we cannot replace one check for the other one without checking why the old portletId is still in the portlet table as you said before. If this is true, it could be an issue more critical than the current one so we should need to fix it. For example if you check the directory web module:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/directory/directory-web/src/main/java/com/liferay/directory/web/internal/upgrade/DirectoryWebUpgrade.java

The method _hasPortletIds_ should return true the first time is executed and false the rest of the times since the method _UpgradePortletId_  is executed after the first execution.

So, and just to confirm it, do all old portlet ids for web modules persist after an upgrade in the portlet table?

Thanks.

**Comment by achaparro** [comment]
I also wanted to point out that I did some tests with the original code and the web modules I checked were upgraded properly (the upgrade wasn't executed more than once), for that reason I want to be sure what you mean before changing anything,

**Comment by SamZiemer** [comment]
I understand, thank you. I will look into what you mentioned and get back to you with an update.

**Comment by SamZiemer** [comment]
Hi, @achaparro, sorry for the delay in getting back to you on this.

You are correct about there being another issue at play, however it is not too critical luckily. It seems like most web module upgrades are working correctly and not running the base web module release more than once. However, there are a few like the [DirectoryWebUpgrade](https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/directory/directory-web/src/main/java/com/liferay/directory/web/internal/upgrade/DirectoryWebUpgrade.java#L46-L49) that add all possible portletIds to the getPortletId method, including the current DXP portletIds. This causes the getPortletId method to always return true and always run the upgrade. Unless I am mistaken, I think the best option is to remove the excessive portletIds from those getPortletId methods. 

However I do think we still need to make changes to baseUpgradeServiceModuleRelease to perform the same getPortletId check prior to running the upgrade as we have done in the baseUpgradeWebModuleRelease.

I will close this pull request for now and send you a new one with the appropriate changes, unless you would like me to send it somewhere else?

Thank you for helping me figure out the real issue here!
Sam

**Comment by achaparro** [comment]
Hi @SamZiemer,

Regarding your comments:
> However, there are a few like the DirectoryWebUpgrade that add all possible portletIds to the getPortletId method, including the current DXP portletIds. This causes the getPortletId method to always return true and always run the upgrade. Unless I am mistaken, I think the best option is to remove the excessive portletIds from those getPortletId methods.
I have been taking to @adolfopa and we agree about that could be the proper solution. Anyway, he wants to be sure that it will work for all use cases (there are a few one taking into account that the Liferay 7.0 CE version didn't upgrade those modules properly), with that purpose, could you test the issue https://issues.liferay.com/browse/LPS-69656 once you have a solution?

> However I do think we still need to make changes to baseUpgradeServiceModuleRelease to perform the same getPortletId check prior to running the upgrade as we have done in the baseUpgradeWebModuleRelease.
For these cases, just check the release table since it's not necessary to check portletId here (I think we alaready are doing simething similar here but we need to avoid to print the log)

Let me know if you have any question.

Thanks!

**Pull request closed without merging**
