### PR TITLE
LPS-138029 (Part 2)

### PR DESCRIPTION
**Pull request by kevhlee**
**Ticket:**
<https://issues.liferay.com/browse/LPS-138029>

**Previous Pull Request:**
<https://github.com/achaparro/liferay-portal/pull/995>

**Notes:**
I've made the necessary additions since the previous pull request:

* Display the number of rows in each table, both before and after the upgrade.
  * Indicate added/removed tables using the `-` symbol.
* Limit output to only non-empty tables.
* Add a date to the beginning of the report.

Regarding the latest commit (0feacab4f34deb7d9768224dbb651310de1a8648), I remove the usage of `TableInfo` class to simplify the code. However, in the future, I do see how we can extend and use the `TableInfo` class to record more information about the database tables and thus display more information (e.g. indexes, data types, memory size, etc.). Perhaps we may want to revert commit 0feacab4f34deb7d9768224dbb651310de1a8648. Let me know if we should.

Feel free to make adjustments if necessary or let me know if I need to change anything.

### CODE REVIEW

**Comment by kevhlee** [comment]
Also, congrats on having 1000 pull requests on this repo!

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Thanks @kevhlee, the report looks great! :-)

See https://github.com/achaparro/liferay-portal/pull/1011

**Pull request closed without merging**
