### PR TITLE
LPD-29718 Create SF rule to avoid caching non-company scoped classNameIds

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @achaparro
I made a SF rule for classNameId, but I still can see some violations, can you help take a look at it?
Thanks.

```
     [java] java.lang.Exception: Found 4 formatting issues:
     [java] 1: Avoid using variable name '_classNameIds', see LPD-29718: ./modules/apps/asset/asset-categories-admin-web/src/main/java/com/liferay/asset/categories/admin/web/internal/exportimport/data/handler/helper/AssetVocabularySettingsImportHelper.java 163 (Checkstyle:ClassNameIdCheck)
     [java] 2: Avoid using variable name '_classNameId', see LPD-29718: ./modules/apps/layout/layout-api/src/main/java/com/liferay/layout/util/structure/FormStyledLayoutStructureItem.java 294 (Checkstyle:ClassNameIdCheck)
     [java] 3: Avoid using variable name '_classNameIds', see LPD-29718: ./portal-kernel/src/com/liferay/asset/kernel/service/persistence/AssetEntryQuery.java 701 (Checkstyle:ClassNameIdCheck)
     [java] 4: Avoid using variable name '_notificationClassNameId', see LPD-29718: ./portal-kernel/src/com/liferay/portal/kernel/util/SubscriptionSender.java 1196 (Checkstyle:ClassNameIdCheck)

```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
Hi @achaparro Do you have chance to take a look?

**Comment by achaparro** [comment]
Hi @ling-alan-huang,

I was on PTO and I missed this. I will review today or tomorrow.

Sorry!

**Comment by achaparro** [comment]
@marianoalvarosaiz, I have been checking the cases mentioned here by @ling-alan-huang and it is not clear to me how to solve it especially for _AssetVocabularySettingsImportHelper_

All of them are non-static objects to be instantiated and company scope, so maybe, we can exclude them when not possible to adapt them.

Let me know your thoughts

Thanks.

**Comment by marianoalvarosaiz** [comment]
-  `./modules/apps/asset/asset-categories-admin-web/src/main/java/com/liferay/asset/categories/admin/web/internal/exportimport/data/handler/helper/AssetVocabularySettingsImportHelper.java`: This one doesn't need to be fixed because it's instantiated at method scope level in AssetVocabularyStagedModelDataHandler#_getImportSettings, so its content will be garbage collected as soon as the method finishes. If this is difficult to detect @ling-alan-huang at SF level we can change this class although with its current use is not needed.

-  `./modules/apps/layout/layout-api/src/main/java/com/liferay/layout/util/structure/FormStyledLayoutStructureItem.java` @ling-alan-huang why this one isn't ignored with https://github.com/achaparro/liferay-portal/pull/1088/commits/9d305c34535cb6fa2a467ffee260ec39869dbe52. Is it due the getClassName method?

-  `./portal-kernel/src/com/liferay/asset/kernel/service/persistence/AssetEntryQuery.java`: I would exclude this one for the same reason as: `*Criterion : They are just value objects. The classNameId is just a value handler.`

- ./portal-kernel/src/com/liferay/portal/kernel/util/SubscriptionSender.java: The subscription sender by its nature is instantiated and used in the scope that is being instantiated (method) and garbage collected afterwards. So the object is not going to be used among threads. @achaparro with this one we have to options: discard it due to its nature or fix it and replace setNotificationClassNameId with setNotificationClassName since there is no use of setNotificationClassNameId in our repo.

**Comment by ling-alan-huang** [comment]
Thanks, @marianoalvarosaiz 
> * `./modules/apps/asset/asset-categories-admin-web/src/main/java/com/liferay/asset/categories/admin/web/internal/exportimport/data/handler/helper/AssetVocabularySettingsImportHelper.java`: This one doesn't need to be fixed because it's instantiated at method scope level in AssetVocabularyStagedModelDataHandler#_getImportSettings, so its content will be garbage collected as soon as the method finishes. If this is difficult to detect @ling-alan-huang at SF level we can change this class although with its current use is not needed.

It's difficult for SF to check it, please change the class.

> * `./modules/apps/layout/layout-api/src/main/java/com/liferay/layout/util/structure/FormStyledLayoutStructureItem.java` @ling-alan-huang why this one isn't ignored with [9d305c3](https://github.com/achaparro/liferay-portal/commit/9d305c34535cb6fa2a467ffee260ec39869dbe52). Is it due the getClassName method?

But we also have `_classNameId` in other methods, see `getItemConfigJSONObject`

> * `./portal-kernel/src/com/liferay/asset/kernel/service/persistence/AssetEntryQuery.java`: I would exclude this one for the same reason as: `*Criterion : They are just value objects. The classNameId is just a value handler.`

I will exclude this class.

**Comment by marianoalvarosaiz** [comment]
@ling-alan-huang for the first case I've created the following pull request that is under review: https://github.com/liferay-database-infra/liferay-portal/pull/2243. Once it is merged the SF should not detect it.

For the second one, FormStyledLayoutStructureItem.java, it is just a value object, the id is only assigned and used in get*/equals methods. So I would best exclude it.

**Comment by ling-alan-huang** [comment]
@marianoalvarosaiz Thank you so much.

**Comment by marianoalvarosaiz** [comment]
@ling-alan-huang the pull has been merged by Brian, see https://github.com/brianchandotcom/liferay-portal/pull/153493. So `AssetVocabularySettingsImportHelper.java` and `SubscriptionSender.java` should have been fixed.

Kind regards.

**Comment by marianoalvarosaiz** [comment]
ci:close

**Comment by ling-alan-huang** [comment]
Thanks @achaparro @marianoalvarosaiz, I just sent SF PR here: https://github.com/liferay-devtools/liferay-portal/pull/180

**Pull request closed without merging**
