### PR TITLE
[TECHNICAL-SUPPORT] LPS-76928

### PR DESCRIPTION
**Pull request by SamZiemer**
Hey Alberto, this issue seems similar to the verifyRatings where the fix should not be running this verify process, but rather fix the underlying issue. In addition I don't think an problem will crop up for a client unless they change their mysql database engine after already setting up their database, since we now always create tables using the database engine set in the portal properties by default.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @SamZiemer,

I am not sure if we can remove this verify process because it ensures that all tables uses the same engine in Mysql or MariaDB. Right now it is not working as expected because we don't check module tables here:
https://github.com/achaparro/liferay-portal/pull/165/commits/5d3d6fea9ef796db42a8a584e1e7f8a9e0e299d1#diff-0f9ba3c3fa4feea5c642991467f89f10L56

Maybe @shuyangzhou can help us to decide in this point, what do you think?

Thanks!

**Comment by SamZiemer** [comment]
Hi @achaparro,

I can put this in the 7.0 upgrade if you would prefer, and use the _is62PortalTable method you added to the upgradeProcess if you would prefer.

I initially thought this may be better resolved as not an upgrade issue, but rather we may potentially need to have a script available to alter the database engine if a client chooses to change it. Since the upgrade would not run after being upgraded anyway, having it in the upgradeProcess would not help anyone who changes the engine later. However, I think having this in the upgradeProcess will at least ensure clients using MySQL or MariaDB will have all liferay related tables using the same database engine during the upgrade.

**Comment by SamZiemer** [comment]
Resent here: https://github.com/achaparro/liferay-portal/pull/180

**Pull request closed without merging**
