### PR TITLE
LPS-91307

### PR DESCRIPTION
**Pull request by jonathanmccann**
Resent from https://github.com/achaparro/liferay-portal/pull/278

Again, please let me know if I missed anything. Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69018. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
