### PR TITLE
LPS-109105 TEMP Custom upgrade run

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@achaparro Failure caught in first run
https://testray.liferay.com/reports/production/logs/test-1-6/1582598567489/test-portal-acceptance-pullrequest(master)/5644/functional-upgrade-tomcat90-mysql57-jdk8-22/0/0/jenkins-console.txt.gz

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
@vicnate5 I think we can have a quick solution for 2 of the 3 common issues. I will finish something related to DBPartitioning first and then I will upload a few commits here to test it.

**Comment by achaparro** [comment]
Next tests:
https://github.com/achaparro/liferay-portal/pull/481

@vicnate5

**Pull request closed without merging**
