### PR TITLE
LPS-123218 SAML Upgrade processes

### PR DESCRIPTION
**Pull request by martamedio**
Hey @achaparro 

Please note that this PR is based on BChan's `master`, I had to take the changes he has mixed before to add the updates, last three commits are the ones that contain the changes we have discussed.

Thanks!

cc/ @stian-sigvartsen

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
Thanks @martamedio looks great! :-)

**Pull request closed without merging**
