### PR TITLE
LPS-89218

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-89218

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test

**Comment by jcampoy** [comment]
ci:test

**Comment by jcampoy** [comment]
ci:reopen

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66848. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
