### PR TITLE
LPS-135887

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-135887

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Looks good to me @mbowerman, I didn't reproduce the issue after several tries and I tracked the OSGI dependencies and they are working well

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
