### PR TITLE
[TECH SUPPORT] LPS-69369 Setting virtual host for private page breaks site control p… 

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi,

Could you please review this fix.
For more information about the issue see:
https://issues.liferay.com/browse/LPS-69369
Or the previous review:
https://github.com/jonathanmccann/liferay-portal/pull/1148

Regards,

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @rimisaadouwork,

Before reopening the pull request and analyzing it, could you tell me why do yout think I am the proper person to check this? I'm the SME for upgrade issues and I'm not an expert for virtual host issues.

Thanks.

**Comment by rimisaadouwork** [comment]
Hi @achaparro,

According to this sheet:
https://docs.google.com/spreadsheets/d/1lKosh2tqsyrXb-6E3MP7x0aMWGJ85h3lEdP_poU-4P8/edit#gid=0

Jonathan McCann or you are the SME of Core Infrastructure. Jonathan told me to send this to the appropriate person. So I assumed you will be the  appropriate person.

Thanks

**Comment by achaparro** [comment]
Hi @rimisaadouwork,

Upgrade belongs to Core infrastructure but I am not an expert for the rest of the areas. @jonathanmccann, who do you mean with the "send this to the appropiate person"

Thanks.

@dsanz

**Comment by jonathanmccann** [comment]
@achaparro,

I meant to follow their normal review chain. I know in TS, we usually have other people in TS review our code before sending it to Engineering. In this case, that would probably be Julio or Ray.

**Comment by rimisaadouwork** [comment]
Hi @achaparro and @jonathanmccann ,

I am sorry for the miscommunication. But could you please provide me the family names or github names of the persons. And do you know where this information is stored? I found only the mentioned sheet.

Thanks,

**Comment by jonathanmccann** [comment]
For engineering reviewers, please see https://in.liferay.com/web/global.engineering/wiki/-/wiki/A+Main/Cross-functional+Team

Julio - https://github.com/juliocamarero/liferay-portal
Ray - https://github.com/rotty3000/liferay-portal

Whoever normally does reviews for your team locally should also know who to send the pull request to.

**Pull request closed without merging**
