### PR TITLE
[TS] LPS-93033 Increase the character limit for the clientIP column in the AUDIT_AUDITEVENT table from 75 to 255

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-93033

Hi @achaparro ,

We had a short discussion awhile back regarding allowing backports of UpgradeProcesses that only alter the size of a Varchar field, since it's considered a Micro change.

This pr increases the clientIP Varchar field from 75 to 255.

Please let me know if you have any questions.
Thanks!

/cc @peterpetrekanics

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72141. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Good job @ericyanLr and @peterpetrekanics, thanks!

**Pull request closed without merging**
