### PR TITLE
[TECHNICAL SUPPORT] LPS-116472 Implement upgrade process

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-116472

I will run `ci:test:sf`, but it will fail due to https://issues.liferay.com/browse/LPS-116530

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/639. [See changes here.](https://github.com/achaparro/liferay-portal/compare/a6b0134d2969~1...a6b0134d2969)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/943. [See changes here.](https://github.com/achaparro/liferay-portal/compare/a6b0134d2969~1...a6b0134d2969)

**Pull request closed without merging**
