### PR TITLE
LPS-103035 JDBC returns primary keys ordered by name, we have to use KEY_SEQ

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:stable

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@vicnate5

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by vicnate5** [comment]
@achaparro The test results here look good. However, this was only tested on MySQL. I triggered more tests.

**Comment by vicnate5** [comment]
@achaparro A few tests failed on certain databases

com.liferay.portal.upgrade.test.UpgradeCompanyIdPrimaryKeyTest.testAddColumnAsPrimaryKeyAfterCompanyId
com.liferay.portal.upgrade.test.UpgradeCompanyIdPrimaryKeyTest.testAddCompanyIdAsPrimaryKey
com.liferay.portal.upgrade.test.UpgradeCompanyIdPrimaryKeyTest.testAddExistingCompanyIdAsPrimaryKey

PostgreSQL
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/357856/AXIS_VARIABLE=33,label_exp=!master/consoleText

Oracle
https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/341189/AXIS_VARIABLE=33,label_exp=!master/consoleText

HSQL
https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/350535/AXIS_VARIABLE=33,label_exp=!master/consoleText

**Comment by achaparro** [comment]
see https://github.com/achaparro/liferay-portal/pull/432

**Pull request closed without merging**
