### PR TITLE
LPS-134196 Ignore expected warning

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@achaparro Based on the previous results this should be good to go, I am just re-running the tests to check the warning ignore

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@achaparro Any reason a message like this is `WARN` level?
`WARN  [Portal Dependency Manager Component Executor--1][DB2DB:196] Successfully upgraded table LayoutPageTemplateStructureRel`
https://testray.liferay.com/reports/production/logs/2021-09/test-1-31/test-portal-acceptance-pullrequest(master)/347/functional-upgrade-tomcat90-db2111-jdk8/0/7/liferay-log.txt.gz

**Comment by achaparro** [comment]
@vicnate5 see the final pull here:
https://github.com/liferay-upgrades/liferay-portal/pull/255

**Comment by achaparro** [comment]
@vicnate5 this is the latest one:
https://github.com/liferay-upgrades/liferay-portal/pull/256

I took into account your last comment:
https://github.com/liferay-upgrades/liferay-portal/pull/256

**Pull request closed without merging**
