### PR TITLE
LPS-134196 Do not require buildUpgradeTable anymore

### PR DESCRIPTION
**Pull request by achaparro**
testing

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@zhangyan0701 The upgrade results didn't seem to import into testray, I retriggered, hopefully they finish quickly

**Comment by vicnate5** [comment]
@koor4356 please help with this if it the test run takes longer.

**Comment by achaparro** [comment]
ci:reevaluate:1317401_305

**Comment by koor4356** [comment]
Looks good. But most of the modules' integration tests are aborted.

**Comment by vicnate5** [comment]
@achaparro Please hold on this, there actually might be some unique failures.

**Comment by koor4356** [comment]
@achaparro @vicnate5, These are the few issues I have noticed. Can you take a look, please?
**Failure that only happens on PostgreSQL:**
`ERROR [main][UpgradeExecutor:250] org.postgresql.util.PSQLException: ERROR: cache lookup failed for relation 18263
`
https://testray.liferay.com/reports/production/logs/2021-09/test-1-31/test-portal-acceptance-pullrequest(master)/305/functional-upgrade-tomcat90-postgresql11-jdk8/6/0/jenkins-console.txt.gz

`WARN  [Framework Event Dispatcher: Equinox Container: 413c509f-6570-454c-b1c2-4e584c6f6ee2][Framework:99] FrameworkEvent WARNING 
org.osgi.framework.ServiceException: org.apache.felix.scr.impl.manager.SingleComponentManager.getService() returned a null service object`

https://testray.liferay.com/reports/production/logs/2021-09/test-1-31/test-portal-acceptance-pullrequest(master)/305/functional-upgrade-tomcat90-postgresql11-jdk8/5/24/jenkins-console.txt.gz

**Failure that only happens on SQL Server 2017:**
`ERROR [main][UpgradeStepRegistratorTracker:143] Failed upgrade process for module com.liferay.layout.seo.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 51) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.`

**Comment by vicnate5** [comment]
@achaparro the errors highlighted by @koor4356 looks to be unrelated

PSQL error is a known random issue at head (see https://issues.liferay.com/browse/LPS-136307)

Also, the PSQL cache error might be unrelated and random.
Seen here at head: https://testray.liferay.com/reports/production/logs/2021-09/test-1-1/test-portal-release/2772/functional-bundle-tomcat-postgresql121-jdk8/1/0/jenkins-console.txt.gz

The SQL Server failure is due to the database server deadlock on CI.

I resent this PR to ignore the expected WARN since it is failing quite a few tests `Attempting to upgrade table FragmentEntryLink by adding a temporary column due to`

Resent at
https://github.com/achaparro/liferay-portal/pull/1018

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
