### PR TITLE
LPS-124848 Passing the connection object

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @achaparro 

Thank you for the suggestion, passing the connection object in an UnsafeBiFunction works.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/831. [See changes here.](https://github.com/achaparro/liferay-portal/compare/f6e7ead7749f~1...f6e7ead7749f)

**Pull request closed without merging**
