### PR TITLE
LPS-122572

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/736.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/739. [See changes here.](https://github.com/achaparro/liferay-portal/compare/1fc4b7ccaad1~1...1fc4b7ccaad1)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/740. [See changes here.](https://github.com/achaparro/liferay-portal/compare/5704f8bef854~2...5704f8bef854)

**Pull request closed without merging**
