### PR TITLE
[TECHNICAL-SUPPORT] LPS-96599

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hey @SamZiemer,

I have a few questions before sending this pull
- is there any chance that there are DDLRecordVersion or DDLRecordSetVersion records with recordId or recordSetId with null value? would it make sense?
- Apart from this DDLRecordVersion are pretty old, why they created an upgrade at this point, should those records have already the proper version?

I know that it's more related to DDL logic and not with the pull but just to be sure about it.

Thanks!

**Comment by SamZiemer** [comment]
Hey @achaparro,

> is there any chance that there are DDLRecordVersion or DDLRecordSetVersion records with recordId or recordSetId with null value? would it make sense?
We added  DDLRecordSetVersion in 7.1 fix pack 1 and the upgrade process that populates the table uses the counter to increment a recordId. As far as DDLRecordVersion, we add a recordId upon creation of the DDLRecordVersion using the existing record, I do not believe the recordId and recordSetId can be null in these cases.

>Apart from this DDLRecordVersion are pretty old, why they created an upgrade at this point, should those records have already the proper version?
We did not add a version column to the DDLRecord and DDLRecordSet tables until [v1_0_2 upgrade](https://github.com/SamZiemer/liferay-portal/blob/master/modules/apps/dynamic-data-lists/dynamic-data-lists-service/src/main/resources/com/liferay/dynamic/data/lists/internal/upgrade/v1_0_2/dependencies/update.sql#L1-L5), the upgrade immediately prior to the once I am changing in this pull. I do not know, however, if we should be pulling the version number from the DDLRecordVersion table. It has been around for a while, but it is not entirely clear to me if this record version should be used as the version for DDLRecord and DDLRecordSet

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74311.

**Pull request closed without merging**
