### PR TITLE
LPS-99014

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76529. [See changes here.](https://github.com/achaparro/liferay-portal/compare/5931e9787bff~1...5931e9787bff)

**Pull request closed without merging**
