### PR TITLE
LPS-120225

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@achaparro see https://github.com/brianchandotcom/liferay-portal/pull/96803

Can you also update my commit in https://github.com/achaparro/liferay-portal/pull/781/commits/008dd8b29234f2042ada3f1cd8be306a5517462f  - I forgot the commit message.

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/782.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/783.

**Pull request closed without merging**
