### PR TITLE
LPS 137162

### PR DESCRIPTION
**Pull request by achaparro**
@samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by koor4356** [comment]
@achaparro @vicnate5
Everything looks good except the following. These tests are only failing on this PR. Can you take a look?
`com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest > classMethod FAILED
     [exec]     com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not execute query
     [exec]     	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:634)
     [exec]     	at com.liferay.change.tracking.service.persistence.impl.CTPreferencesPersistenceImpl.fetchByC_U(CTPreferencesPersistenceImpl.java:1242)
     [exec]     	at com.liferay.change.tracking.service.persistence.impl.CTPreferencesPersistenceImpl.fetchByC_U(CTPreferencesPersistenceImpl.java:1164)
     [exec]     	at com.liferay.change.tracking.service.impl.CTPreferencesLocalServiceImpl.fetchCTPreferences(CTPreferencesLocalServiceImpl.java:56)
     [exec]     	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec]     	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec]     	at com.sun.proxy.$Proxy641.fetchCTPreferences(Unknown Source)
     [exec]     	at com.liferay.change.tracking.internal.CTCollectionIdSupplierImpl.getCTCollectionId(CTCollectionIdSupplierImpl.java:36)
     [exec]     	at com.liferay.portal.kernel.change.tracking.CTCollectionThreadLocal._getCTCollectionId(CTCollectionThreadLocal.java:65)
     [exec]     	at com.liferay.petra.lang.CentralizedThreadLocal.initialValue(CentralizedThreadLocal.java:219)
     [exec]     	at com.liferay.petra.lang.CentralizedThreadLocal.get(CentralizedThreadLocal.java:142)
     [exec]     	at com.liferay.portal.kernel.change.tracking.CTCollectionThreadLocal.getCTCollectionId(CTCollectionThreadLocal.java:28)
     [exec]     	at com.liferay.change.tracking.internal.CTPersistenceHelperImpl.isProductionMode(CTPersistenceHelperImpl.java:90)
     [exec]     	at com.liferay.portal.kernel.service.persistence.change.tracking.helper.CTPersistenceHelperUtil.isProductionMode(CTPersistenceHelperUtil.java:44)
     [exec]     	at com.liferay.portlet.social.service.persistence.impl.SocialActivityPersistenceImpl.findAll(SocialActivityPersistenceImpl.java:6262)
     [exec]     	at com.liferay.portlet.social.service.persistence.impl.SocialActivityPersistenceImpl.findAll(SocialActivityPersistenceImpl.java:6241)
     [exec]     	at com.liferay.portlet.social.service.persistence.impl.SocialActivityPersistenceImpl.findAll(SocialActivityPersistenceImpl.java:6205)
     [exec]     	at sun.reflect.GeneratedMethodAccessor609.invoke(Unknown Source)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.portal.kernel.test.ReflectionTestUtil.invoke(ReflectionTestUtil.java:221)
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.lambda$_captureDataMap$0(DataGuardTestRule.java:343)
     [exec]     	at com.liferay.portal.spring.transaction.BaseTransactionExecutor.execute(BaseTransactionExecutor.java:37)
     [exec]     	at com.liferay.portal.spring.transaction.TransactionInvokerImpl.invoke(TransactionInvokerImpl.java:39)
     [exec]     	at com.liferay.portal.kernel.transaction.TransactionInvokerUtil.invoke(TransactionInvokerUtil.java:28)
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRule._captureDataMap(DataGuardTestRule.java:333)
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.beforeClass(DataGuardTestRule.java:156)
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.beforeClass(DataGuardTestRule.java:73)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:54)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)`

- https://testray.liferay.com/reports/production/logs/2021-08/test-1-6/test-portal-acceptance-pullrequest(master)/8753/modules-integration-mysql57-jdk8/0/4/jenkins-console.txt.gz

This one is a functional test.
-https://testray.liferay.com/reports/production/logs/2021-08/test-1-6/test-portal-acceptance-pullrequest(master)/8753/functional-tomcat90-mysql57-jdk8/2/8/jenkins-console.txt.gz

https://testray.liferay.com/home/-/testray/case_results/1553939162?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1552586477%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1552586477%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc

**Comment by vicnate5** [comment]
@achaparro The issues @koor4356 noted above as unique are probably not related.
The integration test failure is due to https://issues.liferay.com/browse/LPS-136747
The functional test failure is related to the Forms data provider, which is not in the scope of these changes.

However, I noticed some leftover merge conflict lines in the code (e.g. https://github.com/achaparro/liferay-portal/pull/987/files#diff-e1a1f5c290a22e933bd3197c4a63e39c6d6ecaf151a6511696a4a0bbc5e820e8R62)

**Pull request closed without merging**
