### PR TITLE
LPS-68619

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-68619

Resend of https://github.com/achaparro/liferay-portal/pull/219 which manually updates the packageinfo (for some reason, my local machine still doesn't think that file needs a baseline update).

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/holatuwol/liferay-portal/pull/82. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62099. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
