### PR TITLE
LPS-135040

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Alberto,

The customer was facing an issue similar to [LPS-133602](https://issues.liferay.com/browse/LPS-133602). This time, however, the repository that failed to be loaded was the `LiferayRepository` rather than the `PortletRepository`.

Unfortunately, I'm not familiar enough with OSGi to know whether this is the proper way to fix it. Could you please take a look and let me know what you think?

https://issues.liferay.com/browse/LPS-135040

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Looks good to me @mbowerman We also have to wait for LiferayRepository which is not available until this reference is published:
https://github.com/liferay/liferay-portal/blob/3b99c7e1281a3d35b6237481963ccc832a7a3334/portal-impl/src/com/liferay/portal/repository/registry/RepositoryClassDefinitionCatalogImpl.java#L198

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
