### PR TITLE
LPS-127157 Need to run dependency manager sync on non-auto-upgrade st…

### PR DESCRIPTION
**Pull request by SamZiemer**
**Ticket:**
<https://issues.liferay.com/browse/LPS-127157>

tests passed here: https://github.com/SamZiemer/liferay-portal/pull/794#issuecomment-804437918

**Notes from @kevhlee:**

> The issue is that the necessary resource permissions are not being created in the database during startup. This issue also affects other components besides Style Books (e.g. [LPS-125389](https://issues.liferay.com/browse/LPS-125389)). Upon further examination, the issue does not occur on auto-upgrade startups (when `upgrade.database.auto.run=true`). The reason for this is that when auto-upgrade is disabled, the portal startup does not run `DependencyManagerSyncUtil.sync()`, which is preventing the resource actions/permissions from being properly initialized. See the following links:
> 
> - <https://github.com/liferay/liferay-portal/blob/7.3.5-ga6/portal-impl/src/com/liferay/portal/spring/context/PortalContextLoaderListener.java#L363-L370>
> - <https://github.com/liferay/liferay-portal/blob/7.3.5-ga6/portal-impl/src/com/liferay/portal/tools/DBUpgrader.java#L147-L159>
> 
> Let me know if you have any questions or thoughts.

### CODE REVIEW

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @kevhlee, @SamZiemer 

What _DependencyManagerSyncUtil.sync()_ basically does is to call com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl#initPortletDefaultPermissions for every portlet to generate missing ResourcePermissions.

Adding this to every startup:
https://github.com/achaparro/liferay-portal/pull/858/files#diff-6c679ebd8c1dc56340f80284ef7704ad02d80b78c066567e18935b17d72f3b40R370

maybe we are overloading the startup process when it's not necessary since we should check permissions after the upgrade and the first time we initialized the portlet (we already do that here: com.liferay.portal.osgi.web.portlet.tracker.internal.PortletTracker#addingService)

@kevhlee do you think calling _DependencyManagerSyncUtil.sync()_ at another point during the upgrade could solve the issue?

I have to leave but I will continue checking this later.

Thanks.

**Comment by achaparro** [comment]
Hi @kevhlee,

Can you try the following? Add a call to DependencyManagerSyncUtil.sync() after this line:
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/tools/DBUpgrader.java#L157

Then execute the upgrade with a breakpoint in here:
com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl#initPortletDefaultPermissions

And see which portlets stop there in the first execution of DependencyManagerSyncUtil.sync() and which ones are handled in the second execution.

Does it make sense to you?

Thanks.

**Comment by kevhlee** [comment]
Hi @achaparro,

I tried to add `DependencyManagerSyncUtil.sync()` to the location you specified and set the breakpoint. However, `com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl#initPortletDefaultPermissions` is never called during the upgrade. It only seems to run during startup.

Let me know if you want me to try more things.

**Comment by achaparro** [comment]
Hi @kevhlee,

@SamZiemer helped me to figure out what could happen here and we came up with an idea to solve it. He will talk to you about it. Please, let me know about the results.

Thanks!

**Comment by kevhlee** [comment]
Hi @achaparro,

I'm still looking into the different approach for solving this issue. I was able to verify that `PortletLocalServiceUtil.checkPortlets()` fixes the issue by running this code in Server Administration after startup:

```groovy
import com.liferay.portal.kernel.service.CompanyLocalServiceUtil;
import com.liferay.portal.kernel.service.PortletLocalServiceUtil;

CompanyLocalServiceUtil.forEachCompanyId(
        PortletLocalServiceUtil::checkPortlets);
```

Running this allowed me to access the Style Books portlet. This could potentially work as a workaround (besides using `auto.upgrade`). I'll keep looking into how we can do this during upgrade.

cc: @SamZiemer

**Comment by achaparro** [comment]
That's great @kevhlee At least we know now the root of the issue

Thanks!

**Comment by achaparro** [comment]
I proceed to close this pull since @kevhlee is working on another solution

**Pull request closed without merging**
