### PR TITLE
LPS-103034 Auto SF

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Failure likely related, Service builder: https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/281045/AXIS_VARIABLE=0,label_exp=!master/consoleText

Functional tests look good.

**Comment by achaparro** [comment]
We finally realized that the issue wasn't related.

@vicnate5

**Pull request closed without merging**
