### PR TITLE
LPS-86764 Useless upgrade processes run during the initial database creation

### PR DESCRIPTION
**Pull request by kevhlee**
**Ticket:**
<https://issues.liferay.com/browse/LPS-86764>

**Notes:**
After looking at the startup logs and diving into the code, these are the modules where unnecessary upgrades are being run:

```log
com.liferay.asset.publisher.layout.prototype.internal.upgrade
com.liferay.blogs.layout.prototype.internal.upgrade
com.liferay.blogs.web.internal.upgrade
com.liferay.calendar.web.internal.upgrade
com.liferay.captcha.internal.upgrade
com.liferay.change.tracking.web.internal.upgrade
com.liferay.contacts.web.internal.upgrade
com.liferay.document.library.document.conversion.internal.upgrade
com.liferay.document.library.layout.set.prototype.internal.upgrade
com.liferay.exportimport.internal.upgrade
com.liferay.knowledge.base.web.internal.upgrade
com.liferay.license.manager.web.internal.upgrade
com.liferay.message.boards.layout.set.prototype.internal.upgrade
com.liferay.microblogs.web.internal.upgrade
com.liferay.organizations.internal.upgrade
com.liferay.portal.search.web.internal.upgrade
com.liferay.portal.settings.web.internal.upgrade
com.liferay.portal.upload.internal.upgrade
com.liferay.portal.workflow.kaleo.designer.web.internal.upgrade
com.liferay.portal.workflow.kaleo.forms.web.internal.upgrade
com.liferay.site.navigation.menu.web.internal.upgrade
com.liferay.users.admin.web.internal.upgrade
com.liferay.wiki.layout.prototype.internal.upgrade
```

In the future, we should implement some way (perhaps a SF rule) to check upgrade paths for modules and prevent situations like this. Let me know if I need to change/modify anything. Also, please take your time reviewing these changes as many files/upgrades are being changed.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
see https://github.com/achaparro/liferay-portal/pull/983

**Pull request closed without merging**
