### PR TITLE
LPS-184077 Simplify release publication, we should only publish relea…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…se in good state.

@achaparro the InitialUpgradeStep change turned out to expose a lot of dependency issues due the timing and executor thread change for the Release object publication. It is too big to solve all of them at once. I am starting to do some surrounding cleanup first to slowly approach to the goal.

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @shuyangzhou,

In [76926](https://issues.liferay.com/browse/LPS-76926) we allowed service modules to be available even if there were pending **micro** upgrade processes since this kind of upgrades are not required. This is really useful for our customers since it is not mandatory to upgrade Liferay when only micro upgrades are pending. We trained the teams and created SF rules to developers categorize upgrade schema versions properly.

To support this, we implemented a range of required micro schema version instead of just one specific required schema version when registering the service dependency, see [the implementation of the range](https://github.com/achaparro/liferay-portal/blob/c7244b85dd2e1e902d299706eb2f2a6a19831028/modules/apps/portal/portal-spring-extender-impl/src/main/java/com/liferay/portal/spring/extender/internal/configuration/ServiceConfigurationExtender.java#L178).

The reason why we added the "In progress" state was that, when micro upgrades are pending for a module, this module must be available but once those upgrades are running, we must put "In Progress" so it can not be used until they finish.

If we remove the publication of the state we must cover the following in another way:
- A way to put the module in an unavailable state when executing pending micro upgrades
- A way to keep the modules unavailable if an upgrade fails (with these changes, the release publication does not change so it will always available when only micro upgrades are pending regardless the upgrade results)

I guess we can fix this by unpublishing the release entry before executing the upgrades in the _upgradeExecutor_ class, but we should create a test to be sure we fulfill this requirement.

Let me know you thoughts about it.

Best regards.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hey @shuyangzhou,

I have added a missing change we need:
https://github.com/liferay-uniform/liferay-portal/pull/1173/commits/0157b89dee2e83b08be480e9ca2530144d69fda2

And also tests so we can detect future problems:
https://github.com/liferay-uniform/liferay-portal/pull/1173/commits/923108396e0d21f11b45960359e863055154d6fe

The whole pull is in the uniform user:
https://github.com/liferay-uniform/liferay-portal/pull/1173

Thanks!

**Comment by shuyangzhou** [comment]
Thanks @achaparro !

**Pull request closed without merging**
