### PR TITLE
LPS-107149 Deactivate cacheRegistryUtil after checking for build number, otherwise it will always be inactive

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@vicnate5, FYI, it's the issue that happened when settings developer properties

**Comment by vicnate5** [comment]
The LRQA commits should be dropped from this branch since they are no longer up to date and are causing merge conflicts

**Comment by achaparro** [comment]
Thanks @jkappler, I will test it again locally and resend.

@vicnate5 ok, I will remove those commits.

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/531. [See changes here.](https://github.com/achaparro/liferay-portal/compare/f882f1ac5ddd~1...f882f1ac5ddd)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/532. [See changes here.](https://github.com/achaparro/liferay-portal/compare/3b3beb1829ac~2...3b3beb1829ac)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/533. [See changes here.](https://github.com/achaparro/liferay-portal/compare/de52b2b90b69~3...de52b2b90b69)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/534. [See changes here.](https://github.com/achaparro/liferay-portal/compare/de52b2b90b69~3...de52b2b90b69)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/535. [See changes here.](https://github.com/achaparro/liferay-portal/compare/3a755cd4d1ad~3...3a755cd4d1ad)

**Pull request closed without merging**
