### PR TITLE
LPS-98866 Semantic Versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
see tests in https://github.com/marianoalvarosaiz/liferay-portal/pull/222

Semantic Versioning tests failing not related.

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/356. [See changes here.](https://github.com/achaparro/liferay-portal/compare/c4fe9aa5afbb~5...c4fe9aa5afbb)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78649. [See changes here.](https://github.com/achaparro/liferay-portal/compare/c4fe9aa5afbb~5...c4fe9aa5afbb)

**Pull request closed without merging**
