### PR TITLE
[TECHNICAL-SUPPORT] LPS-85535

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @matthewchan123

Notes from Matt:
> https://issues.liferay.com/browse/LPS-85535
> 
> Issue:
> Web Content's published radio buttons have no selections after upgrade from 6.2 to 7.1 and newer. This issue is important because data should not be seemingly "lost" when completing an upgrade.
> 
> Cause:
> In 6.2, content with radio fields contain unused characters '[""]' in the database. The values are still functional in journal article content but the format is not valid for 7.1. See [LPS](https://issues.liferay.com/browse/LPS-85535) ticket description for an example.
> 
> Fix:
> Drawing inspiration from predecessor [UpgradeContentImages.java](https://github.com/liferay/liferay-portal/blob/a8fe2b74e3c9218c09a1d95cd5374b9ac7df3d42/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/upgrade/v1_1_5/UpgradeContentImages.java#L45), I have added an UpgradeProcess which handles removal of these characters. The main changes from UpgradeContentImages.java are the type of dynamic-element tag being "radio" instead of "image", and how data is updated/replaced in dynamicContentElement of convertTypeImageElements().
> 
> The version number is 3_0_1 because this is a [micro change](https://grow.liferay.com/share/Schema+version+and+upgrade+processes+in+7.1) that modifies data to adapt it to the current logic.
> 
> After upgrading, liferay will have removed the unused characters, so content radio selections are retained.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75746. [See changes here.](https://github.com/achaparro/liferay-portal/compare/1ff8007299fe~1...1ff8007299fe)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75749. [See changes here.](https://github.com/achaparro/liferay-portal/compare/0d132c9a359e~2...0d132c9a359e)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75750. [See changes here.](https://github.com/achaparro/liferay-portal/compare/7de65fc22bbd~2...7de65fc22bbd)

**Pull request closed without merging**
