### PR TITLE
LPS-81467 Use MOD function

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @dacousalr

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @dacousalr, @jkappler,

Sorry for the delay but I was analyzing the issue and the solution in depth.

I will like to talk to you in person tomorrow due to points:
- I am not sure if this is going to solve completely the problem. I've realized that if you create a web content in 7.1 for an upgraded database and you add it to a web content display, site member can't see that web content either. Taking into account that the solution adds resource permissions for already existing contents I think this won't solve this use case.
- There is an important problem with the permissions in journal for 7.1. These are the resource actions in 7.1:
'VIEW', '1'
'UPDATE_DISCUSSION', '2'
'DELETE', '4'
'PERMISSIONS', '8'
'EXPIRE', '16'
'DELETE_DISCUSSION', '32'
'UPDATE', '64'
'SUBSCRIBE', '128'
'ADD_DISCUSSION', '256'

And these are the values in 6.1.30 and 6.2:
VIEW', '1'
ADD_DISCUSSION', '2'
DELETE', '4'
DELETE_DISCUSSION', '8'
EXPIRE', '16'
PERMISSIONS', '32'
UPDATE', '64'
UPDATE_DISCUSSION', '128'

This means that UPDATE_DISCUSSION, DELETE_DISCUSSION and ADD_DISCUSSION have changed their value and this can mix up permissions for users using journals.

Let's talk tomorrow about this.

Thanks.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60362. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
