### PR TITLE
Lps 146655 mising upgrade

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
Hey @achaparro 
I tested the upgrade with upgrade.database.auto.run=true
and after portal restarted, the table got upgraded

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:stop

**Pull request closed without merging**
