### PR TITLE
LPS-79882

### PR DESCRIPTION
**Pull request by jonathanmccann**
Please see my notes on how I tested the `checkSystemsGroup` method - https://github.com/jonathanmccann/liferay-portal/pull/1609#issuecomment-384688309

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Thanks for the explanation @jonathanmccann!

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58062. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
