### PR TITLE
LPS-137225 ResultRow adjustments

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
I'll go ahead and forward this then, thanks!

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:reevaluate:1307401_621

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by SamZiemer** [comment]
The failures here don't look related to the changes, but @Preston-Crary maybe you can check with QA?

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/107993

**Pull request closed without merging**
