### PR TITLE
Lps 72046 master

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi, Alberto. This is the change you requested to check if running the BaseUpgradeWebModuleRelease is required before actually running it. Let me know if you have any questions.

Thanks,
Sam

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:stop

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:restart

**Comment by SamZiemer** [comment]
ci:stop

**Comment by SamZiemer** [comment]
ci:retest

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @SamZiemer, I already reviewed the pull but there is a problem with the source formatter, I am talking to  Andrea di Giorgi about that in slack. I hope to be able to push the changes tomorrow.

Cheers

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/migue/liferay-portal/pull/977. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/migue/liferay-portal/pull/978. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
