### PR TITLE
LPS-118622 Ensure URLTitles are unique before adding

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-118622

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
It looks good @SamZiemer  :-)

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
