### PR TITLE
[TECHNICAL SUPPORT] LPS-104599 SF

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-104599

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:upgrade

**Comment by rodrigopaulino** [comment]
Can you confirm if those failures are still related to this PR, @achaparro?

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/642.

**Pull request closed without merging**
