### PR TITLE
LPS-103035 We need to normalize the companyId column name

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:stable

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:backend

**Comment by achaparro** [comment]
Hi @vicnate5, can you check the results here?

**Comment by vicnate5** [comment]
@achaparro Test results look good

**Pull request closed without merging**
