### PR TITLE
[TECHNICAL SUPPORT]LPS-75166 Upgrade from 6.2 to DXP fails during UpgradeMobileDeviceRules if a Device Family is added to a page

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-75166

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:reopen

**Comment by NorbertKocsis** [comment]
ci:retest

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @NorbertKocsis, @amadeafejes,

I will review this on Monday since I am on vacation today.

Thanks!

**Comment by NorbertKocsis** [comment]
Ok. Thanks! :)

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/amadeafejes/liferay-portal/pull/2. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
See https://github.com/amadeafejes/liferay-portal/pull/2

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52256. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
