### PR TITLE
Lps 105658 master

### PR DESCRIPTION
**Pull request by SamZiemer**
@achaparro,

I have updated the test and it should pass now.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82359. [See changes here.](https://github.com/achaparro/liferay-portal/compare/37be908a23bb~2...37be908a23bb)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82360. [See changes here.](https://github.com/achaparro/liferay-portal/compare/114cc190b15f~3...114cc190b15f)

**Pull request closed without merging**
