### PR TITLE
LPS-139342 Processing company IDs can be parallelized

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://issues.liferay.com/browse/LPS-139342>

__Notes:__
Added multithreading when processing company IDs. For now, I decided to use a work-stealing pool and keep it open while the portal is running, but let me know if we need to change any of that. Also, added a new portal property (`database.partition.thread.pool.enabled`) in case we need the option to enable/disable multithreading.

Let me know if you have any thoughts/questions. Thank you!

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hey @achaparro,

I will need to push one more commit, as the code does not use the `ThrowableCollector` at all.

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @kevhlee,

The changes look except for the test because we are not testing if we are opening different threads when DATABASE_PARTITION_THREAD_POOL_ENABLED is enabled. The idea I have is to:
- Create a new method called for example _testForEachCompanyIdThreadPoolEnabled_ that check that we run the upgrades for every company in different threads. I have thought that maybe we can use _Thread.currentThread().getId();_ and compare later that the ids are different. You will need to create a couple of companies, it is enough to call insertCompanyAndDefaultUser but probably you will need to modify it to add the companyId as parameter.

Let me know what you think.

Thanks!

**Comment by kevhlee** [comment]
Hi @achaparro,

I think that makes sense and having that test case would add better coverage. I'm going to implement your idea as well as make some refactoring adjustments to the current tests. I'm going to close this pull request and send a new one.

**Comment by kevhlee** [comment]
ci:close

**Pull request closed without merging**
