### PR TITLE
LPS-59420 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
Hi @achaparro, sorry to ask you again, but could you please double check this pull against your dbs?

@inacionery removed the direct SQL statements (BP modules) on this pull and moved some other things around on the workflow.

cc @migue

Thanks a lot!

### CODE REVIEW

**Comment by achaparro** [comment]
Hey @marcellustavares,

I was pretty busy today and I couldn't test the verify. I will let you know tomorrow.

Cheers!

**Comment by marcellustavares** [comment]
Thanks @achaparro, this is another part of the upgrade process. The verifier is already in master :)

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hey @marcellustavares, @inacionery,

Two things:
- I couldn't rebase the pull request since there are conflicts so I tested it using this current branch.
- I just tested _com.liferay.dynamic.data.mapping.service_ since I haven't worked yet doing kaleo upgrades for Liferay 7. My work with developers finished last week and just maybe in some weeks will be able to do some tests with other modules.

Regarding _com.liferay.dynamic.data.mapping.service_, it finished well (I can see some exceptions related to roles but they did no stop the process) but it is not changing any resourcePermission. This code is always returning null:
https://github.com/marcellustavares/liferay-portal/blob/pr-970/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/upgrade/v1_0_0/UpgradeDynamicDataMapping.java#L659
https://github.com/marcellustavares/liferay-portal/blob/pr-970/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/upgrade/v1_0_0/UpgradeDynamicDataMapping.java#L778

I guess because you are trying to get a value from a map using an String when the key is a Long.

I hope it helps.

Thanks!

**Comment by marcellustavares** [comment]
Thx @achaparro, I'll push it to Brian so we can continue our tests using the upstream.

Thanks for all the help!

**Pull request closed without merging**
