### PR TITLE
Lps 121639 2

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @achaparro,

Here are the changes we discussed. I tested navigating around the portal and adding/interacting with content both prior to and after the upgrade and I did not see any issues, so I believe this should be the right fix.

One note, when running ant all, both the portal-kernel and portal-impl bnd.bnd files were updated, but I don't really understand why as nothing in the changes should warrant a bundle change. Let me know what you think.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hey @SamZiemer,

> One note, when running ant all, both the portal-kernel and portal-impl bnd.bnd files were updated, but I don't really understand why as nothing in the changes should warrant a bundle change. Let me know what you think.

Maybe that's because we remove a protected method that can be used by child classes. I run the ant baseline locally and I didn't get any issue or change so I think it's fine, maybe Brian has already increased the bundle version and it hasn't been published yet.

It's good to commit :-)

Thanks!

**Pull request closed without merging**
