### PR TITLE
LPS-107785 The version column is of type VARCHAR so fetch it as a string and transform it to an integer

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/366.

**Pull request closed without merging**
