### PR TITLE
LPS-113044

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/574. [See changes here.](https://github.com/achaparro/liferay-portal/compare/af3bd8609100~1...af3bd8609100)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/575. [See changes here.](https://github.com/achaparro/liferay-portal/compare/a28c13e66f23~1...a28c13e66f23)

**Pull request closed without merging**
