### PR TITLE
LPS-137699 Upgrade Report: new features

### PR DESCRIPTION
**Pull request by achaparro**
@samziemer Brian had some suggestions regarding the naming, please check the latest commit

### CODE REVIEW

**Comment by achaparro** [comment]
ci:forward

**Comment by SamZiemer** [comment]
hi @achaparro, I think the changes make sense, thank you.

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
Already in master

**Pull request closed without merging**
