### PR TITLE
LPS-84602 Fix test to avoid Sybase errors due to empty string handling.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
some fix as in df630112dbb8

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62695. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
