### PR TITLE
LPS-133955 com.liferay.portal.upgrade.v7_0_0.UpgradeLookAndFeel fails when portletSetupShowBorders is read-only

### PR DESCRIPTION
**Pull request by kevhlee**
**Ticket:**
<https://issues.liferay.com/browse/LPS-133955>

**Notes:**
The issue is that the method `reset()` cannot be run when the portlet preference is read-only, which can be problematic for custom portlets. Looking at the changes that created the upgrade process `v7_0_0.UpgradeLookAndFeel` ([LPS-58651](https://issues.liferay.com/browse/LPS-58651)), the intention of running `reset()` seems to be to remove `portletSetupShowBorders` from the portlet preferences. My solution is to avoid running `reset()` and instead create the portlet preferences while only considering the preference values.

Let me know if you have any questions and/or if I need to revise anything.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
@kevhlee I tested it and works perfectly. Good job!

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
