### PR TITLE
LPS-79875

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
It might be good to leave this until LPS-79876 and LPS-79878 are committed since they utilize the `verifyUuid` method currently.

**Comment by achaparro** [comment]
Hi @jonathanmccann,

This process was included in 6.1EE GA3:
https://issues.liferay.com/browse/LPS-29879

Since we allow direct upgrades from any version of 6.1.x, could you move this logic to an upgrade process in the path UpgradeProcess_6_2_0?

Thanks!

**Comment by jonathanmccann** [comment]
Thanks for catching that. Some logic can still be removed so I sent a new pull here - https://github.com/achaparro/liferay-portal/pull/179

I will work on moving the rest of the logic to an upgrade process under LPS-80100

**Pull request closed without merging**
