### PR TITLE
[TECHNICAL-SUPPORT] LPS-79527

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @achaparro,

Here is the upgrade change to move the VerifySQLServer process into an upgrade. I placed it in the 6.2 upgrade path as requested and tested starting from 6.1 to master. I also tested a 6.2 clean database and  upgraded to master and did not see any ntext columns, so 6.2 looks like it is the first version of liferay to move totally away from ntext.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57132. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Thanks!

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57136. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
