### PR TITLE
LPS-108590 Set CompanyThreadLocal anytime we iterate companies

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
hey @vicnate5, can you verify if the failure is related? If so, is there any way I can test it locally?

Thanks!

**Comment by vicnate5** [comment]
@kyle-miho can you look into this at some point today?

**Comment by kyle-miho** [comment]
@achaparro these failures are not occuring at all upstream, it only happened in this, pull ill message you steps to run this locally

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Pull request closed without merging**
