### PR TITLE
LPS-108805 | Upgrade portlet preferences related to fragment entry links from 7.1.x

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi, 

This is an upgrade step necessary to revert the changes introduced in LPS-97133. 

More precisely, it goes over any portlet preferences associated to frangment entry links and changes the plid they point to from the group control-panel layout (introduced in LPS-97133) to the actual layout the fragment entry link is attached to. 

The last step is to remove these group control-panel layouts since they're only useful in 7.1.x. 

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @ricardocousolr,

Sorry for the delay, I will take a look early next week.

I am not sure about that now but, didn't book an upgrade step using a DummyUpgrade for this case? If so, why we create a new step?

Thanks.

**Comment by ricardocousolr** [comment]
Hi @achaparro,

We did include a DummyUpgrade to book a stop but I think it was in correlation with the upgrade step in 7.1.x:

- For `7.1.x` I included in LPS-97133 a step called `UpgradePortletPreferences` from `1.0.1` to `1.0.2`.
- For `master` I included in LPS-97133 a `DummyUpgradeStep` from `1.0.1` to `1.0.2`. 

Since someone already in `7.1.x` will be in `schemaVersion` `1.0.2`, the new upgrade step in this pr will have to be later than `1.0.2`.

Maybe there should've been two DummyUpgradeSteps: one from `1.0.1` to `1.0.2` and another one from `1.0.2` to `1.0.3` (or to `1.1.0`).

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/csierra/liferay-portal/pull/631. [See changes here.](https://github.com/achaparro/liferay-portal/compare/197feb9c1ce8~1...197feb9c1ce8)

**Comment by achaparro** [comment]
Hi @ricardocousolr,

I passed the pull to Carlos to see that regarding the dependency, the funcionality is ok to me but I think pavel should check it first. Regarding the upgrade framework, we shouldn't access to tables which don't belong to the module here such as Layout or PortletPreferences but I guess is complex or bad in performance to get the same records using the service, right?

Let's see what Carlos says.

Thanks.

**Comment by ricardocousolr** [comment]
Hi @achaparro,

I agree it would be best not to access those table directly but the query is complex. 

Thanks for your review!

**Pull request closed without merging**
