### PR TITLE
LPS-84602 ensure upgrade gets executed in next execution.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by marianoalvarosaiz** [comment]
ci:retest

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62507. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
