### PR TITLE
[TECHNICAL SUPPORT] LPS-72595

### PR DESCRIPTION
**Pull request by amadeafejes**
https://issues.liferay.com/browse/LPS-72595

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
FYI, I have got the following answer from Ray regarding the version bump:

**me**:
>Is it allowed to do a major version bump for a package on master? `portal-impl/src/com/liferay/portal/upgrade/v7_0_0/packageinfo` is `1.5.0` right now and the new changes (removing some protected method   from an Upgrade* class) requires `2.0.0`.

**Ray**:
>it's not allowed
>however, this class isn't for client consumption, you could do a couple of things
>* you could mark it as `@ProviderType` which should reduce the semantic version strain on the baseline operation (may not completely address the versioning issue, but isn't a bad option)
>* deprecate the class and remove it from the upgrade configuration, and provide a new package `portal-impl/src/com/liferay/portal/upgrade/v7_0_0/i2/` which will have version `1.0.0`
>also, is it really required for fixing anything to remove methods? sounds like that's just cleanup which shouldn't be needed

**Comment by lipusz** [comment]
Hi Alberto,

Can you please give it a prioerity? It'd be great if we could include it in 7.0.0 CE GA4 which is already in progress.

Thanks!

@achaparro

**Comment by achaparro** [comment]
I know @lipusz, I'm also working with Nicole with other important issues with the new CE.

Anyway, I was waiting you for doing one of the alternatives that Ray told you, why didn't you do it?

Thanks.

@amadeafejes

**Comment by brianchandotcom** [comment]
@achaparro portal-impl/src/com/liferay/portal/upgrade/v7_0_0/packageinfo is now 2.0.0

We shouldn't do a breaking change like this.

**Comment by achaparro** [comment]
Hi @brianchandotcom,

@amadeafejes is working on avoiding that. I will close this pull waiting for a new one.

Thanks!

**Pull request closed without merging**
