### PR TITLE
Lps 88135

### PR DESCRIPTION
**Pull request by balazssk**
Hi @achaparro ,

I looked through https://issues.liferay.com/browse/LPS-87237 again, and found that https://issues.liferay.com/browse/LPS-88135 is the only thing needed to have these issue closed.

I'm not sure if introducing a new abstract class like this is a good practice, but I wanted to avoid as much code duplication as possible.

Can you please review it?
Also, if you have any suggestions to the javadoc, I'd be very happy to hear them.

ps.: Happy New Year!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:help

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @balazssk,

Happy new year too! I will review this today or tomorrow after the tests so you have an answer before the weekend.

Thanks.

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hey @balazssk,

I can't accept this pull because I think we are not solving the root cause of the issue: **avoid to add the suffix _INSTANCE_XXX to the Calendar row in the Group_.typesettings field during the upgrade.** 

After researching a bit, I have realized that the suffix is added in this point:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-web/src/main/java/com/liferay/calendar/web/internal/upgrade/v1_1_0/UpgradePortletId.java#L27

Because we have converted the Calendar portlet from non instanciable to instanciable portlet here:
https://issues.liferay.com/browse/LPS-67572

That can be right and we should change all references in tables such as ResourcePermission, portletPreferences, layout, etc.

However we also add the suffix here:
https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/upgrade/BaseUpgradePortletId.java#L569

When it's not needed in this case.

Could you send me a pull with a solution for that? Since the bug was added in 7.1, just a few customers have upgraded yet and it's a minor issue, this fix has to be enough.

I proceed to close the pull but please, let me know your thoughs here or via gtalk.

Thanks.

**Comment by balazssk** [comment]
Hey @achaparro ,
Thanks for the review, I was also eyeing the upgradeGroup call in upgradeUninstanceablePortletIds.

Only Calendar is implementing it in https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-web/src/main/java/com/liferay/calendar/web/internal/upgrade/v1_1_0/UpgradePortletId.java#L27 ,
but I was hesitant to change this method.

After your feedback and a bit more investigation I can't see any problem in removing upgradeGroup from upgradeUninstanceablePortletIds, but if we'd want to go for safe, I'd just extend the typeSettingCriteria to not replace staged typesettings if we are doing upgradeUninstanceablePortletIds.

What do you think?

**Comment by achaparro** [comment]
Hey @balazssk,

Good question.

After reasearching a bit, when we fill the method _getUninstanceablePortletIds_ our goal is to convert old uninstanceable portletId references to instanceable portletId references. That logic should never modify the staged portletId in the _Group.typesettings_ field since the portletId reference is always the same (without the suffix) either for uninstanceable or for instanceable portlets in that field.

Taking this into account and that the method _updateGroup_ is only meant to update staged portlets (right?) I would go ahead and I would remove the call from the Base class.

Thanks.

PS: Please, take into account that we already convert the old portletId to the new one here:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-web/src/main/java/com/liferay/calendar/web/internal/upgrade/CalendarWebUpgrade.java#L44

**Comment by achaparro** [comment]
@balazssk I noticed that but after that we call getNewTypeSettings:
https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/upgrade/BaseUpgradePortletId.java#L212

And it seems that we only modify typeSettings if the portletId is staged:
+https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/upgrade/BaseUpgradePortletId.java#L56

Did I miss something?

Thanks.

**Comment by balazssk** [comment]
o wow,
That really does look like only staged typesettings are updated (for Groups), but then... why do we need an overcomplicated query from getTypeSettingsCriteria for updateGroup?

Yes, I think we can remove the updateGroup call from the uninstanceable branch.
Might be even worth simplify the SQL query...

**Comment by achaparro** [comment]
> Yes, I think we can remove the updateGroup call from the uninstanceable branch.
> Might be even worth simplify the SQL query...

I agree with both. Ideally we should create another ticket for the query refactor but let's do it in the same since both changes are related to the updateGroup and we will be able to backport it together so that customer in 7.1 will be able to benefit from this rapidly.

Thanks @balazssk !

**Pull request closed without merging**
