### PR TITLE
LPS-72708 Improve DBInspector performance

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
Same failures as in https://github.com/brianchandotcom/liferay-portal/pull/49721

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49902. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49927. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49928. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
