### PR TITLE
LPS-134357 Added SQL Check

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi @achaparro,

I created a normal master based PR, please review/merge it if you find it correct.

Regards,
Vilmos

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by vilmospapp** [comment]
ci:test:sf

**Comment by vilmospapp** [comment]
ci:test:sf

**Comment by vilmospapp** [comment]
ci:test:sf

**Comment by vilmospapp** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Thanks a lot @vilmospapp !

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
