### PR TITLE
[TS] LPS-132719 Populate primKeyId and viewActionId columns

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-132719

The ResourcePermission table is not populated with a primKeyId and a viewActionId in the ResourcePermission  records created by com.liferay.portal.kernel.upgrade.BaseAdminPortletsUpgradeProcess subclasses. (BaseUpgradeAdminPortlets in the old 7.3.x branch)

The primKeyId and viewActionId are populated in the com.liferay.portal.upgrade.v7_0_0.UpgradeResourcePermission class, but BaseUpgradeAdminPortlets subclasses are upgrade modules that are executed after that class:
* modules/apps/bookmarks/bookmarks-web/src/main/java/com/liferay/bookmarks/web/internal/upgrade/v1_0_0/UpgradeAdminPortlets.java
* modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/upgrade/v1_0_0/UpgradeAdminPortlets.java

To avoid this issue, we have to populate these columns in the BaseAdminPortletsUpgradeProcess.addResourcePermission method.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @jorgediaz-lr, can you fix it? There is a compilation issue.

Thanks.

**Comment by jorgediaz-lr** [comment]
Resent here: https://github.com/achaparro/liferay-portal/pull/906

**Pull request closed without merging**
