### PR TITLE
LPS-108590 DB Partition: set companyThreadLocal anytime we iterate companies

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:retest

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:bundle

**Pull request closed without merging**
