### PR TITLE
LPS-88550 There may be more than two entries with the same fileVersionId due to LPS-30576

### PR DESCRIPTION
**Pull request by adolfopa**
Description in the original PR:

> Some notes on how it is possible to get into this situation:
>
>    Before LPS-30576 was introduced, there would be DLFileEntryMetadata entries for every DLFileEntry for each Portal Instance (ie 3 portal instances leads to 3 distinct entries within DLFileEntryMetadata)
>
>    In 6.2 a new DDMStructure was created for TIKARAWMETADATA (as evidenced by LPS-65441). If a user edits a DLFileEntry after this is introduced then a new DLFileEntryMetadata entry is created pointing to the new DDMStructure.
>
>    In 7.0 this issue was partially resolved by LPS-69329. It assumed that only duplicates would be encountered. However, this did not take into account #1 where multiple portal instances could errantly create duplicate DLFileEntryMetadata entries.
>
>The solution proposed here is instead of searching for exactly 2 duplicated entries we should search for 2 or greater entries.
>
>Please let me know if you have any questions or concerns.

@achaparro What would be the best way to make sure people that already upgraded get these changes? One of those PostUpgrade things or a regular (additional) step in the upgrade?

/cc @robertoDiaz @jonathanmccann

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@adolfopa @achaparro I believe that if someone needed this fix the upgrade would have failed and never completed successfully (as is happening with the current client) so I'm not sure if anything else would be necessary.

**Comment by achaparro** [comment]
Hi @jonathanmccann,

Thank you for the clarification, in that case we don't a new upgrade process or post upgrade fix.

I will sent it to Brian now.

Cheers!
cc/ @adolfopa @robertoDiaz

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66112. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
