### PR TITLE
SF rule to avoid having more than 1 verify process per module

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-176090

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @ling-alan-huang,

It looks good to me, you can forward the pull request.

Thank you!

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
