### PR TITLE
LPS-107816

### PR DESCRIPTION
**Pull request by jesseyeh-liferay**
**[LPS-107816](https://issues.liferay.com/browse/LPS-107816)**

**Previous pull request**: https://github.com/achaparro/liferay-portal/pull/894

> This changes the type of the version column in KaleoDefinitionVersion from a String to an int.

**Changelog**:
* Resolve additional test failures

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by jesseyeh-liferay** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:reevaluate:1257401_156

**Comment by achaparro** [comment]
ci:reevaluate:1257401_156

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/liferay-workflow/liferay-portal/pull/365. [See changes here.](https://github.com/achaparro/liferay-portal/compare/772940adc6f0~3...772940adc6f0)

**Comment by achaparro** [comment]
Good work @jesseyeh-liferay!

Please take into account this commit since it is really important:
https://github.com/liferay-workflow/liferay-portal/pull/365/commits/e7cc72a323b59a5e297dfd440933c9edcbee2e1d

Regarding the tests I also reproduced them without the changes

Thanks.

cc/ @samziemer please take into account the commit I mentioned for future pull request reviews

**Pull request closed without merging**
