### PR TITLE
Lps 87237 2

### PR DESCRIPTION
**Pull request by balazssk**
Hi @achaparro ,

As we discussed, I've added the missing bits to the already existing upgrade processes.

This fixes all 6.2 portletIds to 7.0 version, so we won't need to create micro upgrade steps for them.

Followups:

1. I'll create a followup ticket to tackle the issue of new stageable portlets being installed and those showing up as enabled in the staging configuration form.
2. Also, I will create an upgrade process in a separate ticket for calendar and knowledge base, to handle the case of one of them being present in 6.2 before the upgrade. This might also include the refactoring of the verify processes we've talked about.

Given that this fix doesn't fully resolve the issue of the staging configuration form, should I reword the ticket or merge it with the 2 followups and resend this PR with those fixes included?

Best regards,

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @balazssk,

My believe is that, with this pull, we are covering all use cases where the portletId wasn't upgraded properly.

So we just need to remove the verifiers and create new upgrade processes to move to the admin id for staged cases, right?

If so, let me analyze the pull in depth and test it tomorrow to take the best approach.

Apart from this, I will fix the SF issue but, could you analyze if the CI errors can be related to your changes?

Thanks!

**Comment by balazssk** [comment]
Hi @achaparro ,

Sorry for getting back at you late, I was out of office yesterday.

I don't see any immediate connection between the test failures and the fix. 
Given the fix only changes anything if an upgrade is performed I don't see any reason why a fresh dxp would have any changes.

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hey @balazssk,

You were right regarding the semantic versioning, I have made some changes (trying to use a unique base class) to avoid to increase the package to a major version. I have also created a new ticket to avoid these problems in the future:
https://issues.liferay.com/browse/LPS-88005

I have also performed some tests and these are the typeSettings in 6.2:
```
staged-portlet_15=true
staged-portlet_167=false
staged-portlet_178=true
staged-portlet_183=false
staged-portlet_19=false
staged-portlet_1_WAR_calendarportlet=false
staged-portlet_1_WAR_knowledgebaseportlet=false
staged-portlet_1_WAR_opensocialportlet=true
staged-portlet_20=true
staged-portlet_25=false
staged-portlet_28=true
staged-portlet_33=false
staged-portlet_36=false
```
And these ones in master after an upgrade with our changes:
```
staged-portlet_1_WAR_opensocialportlet=true
staged-portlet_com_liferay_blogs_web_portlet_BlogsAdminPortlet=false
staged-portlet_com_liferay_bookmarks_web_portlet_BookmarksAdminPortlet=true
staged-portlet_com_liferay_calendar_web_portlet_CalendarPortlet_INSTANCE_mNdHX1tSDsm1=false
staged-portlet_com_liferay_document_library_web_portlet_DLAdminPortlet=true
staged-portlet_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet=false
staged-portlet_com_liferay_dynamic_data_mapping_web_portlet_PortletDisplayTemplatePortlet=false
staged-portlet_com_liferay_journal_web_portlet_JournalPortlet=true
staged-portlet_com_liferay_knowledge_base_web_portlet_AdminPortlet=false
staged-portlet_com_liferay_message_boards_web_portlet_MBAdminPortlet=false
staged-portlet_com_liferay_mobile_device_rules_web_portlet_MDRPortlet=true
staged-portlet_com_liferay_polls_web_portlet_PollsPortlet=false
staged-portlet_com_liferay_wiki_web_portlet_WikiPortlet=false
```

I see three errors here:
- Calendar has also one INSTANCE_ID
- Wiki portletId wasn't converted to the proper admin portlet id (even with a verify process)
- Open Calendar portlet (it is still a plugin)

My guess is that both errors are unrelated to this pull so, for now, I am going to send this pull. Please check those errors to be able to fix them (I will come back this Tuesday)

Thanks for the good job!

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65500. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65543. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65549. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65569. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
