### PR TITLE
[TS] LPS-95312 Change version numbering in portal-security-audit to ensure that the AUDIT_AUDITEVENT table can be upgraded in Liferay 7.1

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Dear @achaparro ,

I have changed the AuditStorageServiceUpgrade.java file based on your suggestions from:
https://github.com/achaparro/liferay-portal-ee/pull/49#issuecomment-490985419

Is this what you had in mind? I hope I understood correctly :)

Thank you for your help,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test:relevant

**Comment by peterpetrekanics** [comment]
Dear @achaparro ,

I would like to ask for your kind help:
I found that the BaseUpgradeSQLServerDatetime.java was created with LPS-84513 and it does not exist on 7.1.x yet.
Do you have any best practices how to handle that?
Would you suggest to backport that LPS to 7.1.x, too, or would you use another class in AuditStorageServiceUpgrade.java ?

Many thanks,
Peter

**Comment by achaparro** [comment]
Hi @peterpetrekanics,

```
> I found that the BaseUpgradeSQLServerDatetime.java was created with LPS-84513 and it does not exist on 7.1.x yet.
> Do you have any best practices how to handle that?
> Would you suggest to backport that LPS to 7.1.x, too, or would you use another class in AuditStorageServiceUpgrade.java ?
```
This is the reason why we are implementing these changes. We are moving that class BaseUpgradeSQLServerDatetime to the latest steps in the upgrade because we don't want to backport it.

Your changes look good, I will send them today.

Let me know if this is clear enough.

Thanks!

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73017.

**Pull request closed without merging**
