### PR TITLE
LPS-124848 Lost the Subscription of blog after upgrade

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @achaparro ,

Could you please review this pull request?

@robertoDiaz
Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @IstvanD,

I will check the pull today.

Thanks.

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
ci:forward

**Pull request closed without merging**
