### PR TITLE
LPS-93557 Avoid using 'user dashboard' and 'user profile' themes

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @achaparro ,

Can you review this PR, please?

Thanks.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75961. [See changes here.](https://github.com/achaparro/liferay-portal/compare/6baf61d2d109~2...6baf61d2d109)

**Comment by achaparro** [comment]
Hey @antonio-ortega,

The pull was perfectly fine from the logic perspective but I have added two changes:
- I have created a base upgrade since we have two classes now and we can have more in the future.
- I have moved the upgrade to the 7.2 path so that all also customers moving from 7.1.x to 7.2 can benefit from that (if they had the error and they didn't solve it during this time). In these cases, if you need to backport to 7.1.x, then you can commit your upgrade in the 7.1 path in that branch.

Thanks!

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75962. [See changes here.](https://github.com/achaparro/liferay-portal/compare/2d30145511c4~3...2d30145511c4)

**Pull request closed without merging**
