### PR TITLE
LPS-74615 upgrade wrong portletId in 7.0 above

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:test

**Comment by daviddotzhang** [comment]
@achaparro  just considering the point that whether we need to remove the code of updating status part?
1: if removed it, the default behavior is different as ee-6.2.x. 
ee-6.2.x:  176 1
master:    com_liferay_license_manager_web_portlet_LicenseManagerPortlet 0

2: if kept it,  it will change customer's setting if  they have disabled LicenseManagerPortlet

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @daviddotzhang,

I am not sure if I understood you but I think that the proper logic is to create a new upgrade step which:
1. Check if there is a record in PortletId table with portletId 176 (with this we detect the use case when DXP users upgraded before your fix)
2. If so we shoud:
2.1. Remove the portlet record which portletId is "com_liferay_license_manager_web_portlet_LicenseManagerPortlet"
2.2 Execute UpgradePortletId()); for new String[] {"176", LicenseManagerPortletKeys.LICENSE_MANAGER}

If you don't see any drawback to this please, send me another pull request with this.

Thanks.

**Comment by daviddotzhang** [comment]
see https://github.com/achaparro/liferay-portal/pull/126

**Pull request closed without merging**
