### PR TITLE
LPS-86461 SF

### PR DESCRIPTION
**Pull request by anthony-chu**

### CODE REVIEW

**Comment by anthony-chu** [comment]
hey @achaparro, i tried to resolve some of the unsatisfied references that came up during startup, but it looks like there are still some that are unresolved (like asset publisher and calendar). here's the `ds:unsatisfied` result:

```
2018-12-21 00:51:14.869 WARN  [main][SystemCheckOSGiCommands:134] Declarative Service Unsatisfied Component Checker check result:
Bundle {id: 356, name: com.liferay.asset.publisher.web, version: 3.0.0}
        Declarative Service {id: 1319, name: com.liferay.asset.publisher.web.portlet.AssetPublisherPortlet, unsatisfied references:
                {name: Release, target: (&(release.bundle.symbolic.name=com.liferay.asset.publisher.web)(&(release.schema.version>=1.2.0)(!(release.schema.version>=1.3.0))))}
        }
        Declarative Service {id: 1321, name: com.liferay.asset.publisher.web.portlet.HighestRatedAssetsPortlet, unsatisfied references:
                {name: Release, target: (&(release.bundle.symbolic.name=com.liferay.asset.publisher.web)(&(release.schema.version>=1.2.0)(!(release.schema.version>=1.3.0))))}
        }
        Declarative Service {id: 1322, name: com.liferay.asset.publisher.web.portlet.MostViewedAssetsPortlet, unsatisfied references:
                {name: Release, target: (&(release.bundle.symbolic.name=com.liferay.asset.publisher.web)(&(release.schema.version>=1.2.0)(!(release.schema.version>=1.3.0))))}
        }
        Declarative Service {id: 1323, name: com.liferay.asset.publisher.web.portlet.RecentContentPortlet, unsatisfied references:
                {name: Release, target: (&(release.bundle.symbolic.name=com.liferay.asset.publisher.web)(&(release.schema.version>=1.2.0)(!(release.schema.version>=1.3.0))))}
        }
        Declarative Service {id: 1324, name: com.liferay.asset.publisher.web.portlet.RelatedAssetsPortlet, unsatisfied references:
                {name: Release, target: (&(release.bundle.symbolic.name=com.liferay.asset.publisher.web)(&(release.schema.version>=1.2.0)(!(release.schema.version>=1.3.0))))}
        }
Bundle {id: 389, name: com.liferay.calendar.web, version: 3.0.0}
        Declarative Service {id: 1625, name: com.liferay.calendar.web.internal.portlet.CalendarPortlet, unsatisfied references:
                {name: Release, target: (&(release.bundle.symbolic.name=com.liferay.calendar.web)(&(release.schema.version>=1.0.0)(!(release.schema.version>=1.1.0))))}
        }
Bundle {id: 440, name: com.liferay.document.library.layout.set.prototype, version: 4.0.0}
        Declarative Service {id: 1855, name: com.liferay.document.library.layout.set.prototype.internal.instance.lifecycle.AddLayoutSetPrototypePortalInstanceLifecycleListener, unsatisfied references:
                {name: AssetPublisherPortlet, target: (javax.portlet.name=com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet)}
        }
Bundle {id: 673, name: com.liferay.message.boards.layout.set.prototype, version: 3.0.0}
        Declarative Service {id: 3437, name: com.liferay.message.boards.layout.set.prototype.internal.instance.lifecycle.AddLayoutSetPrototypePortalInstanceLifecycleListener, unsatisfied references:
                {name: AssetPublisherPortlet, target: (javax.portlet.name=com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet)}
        }
```

**Comment by achaparro** [comment]
Thanks for fixing this @anthony-chu!

I have continued checking the rest of the errors and this pull brought to light some errors like this one where we haven't defined a path which reaches the final schema version:
https://github.com/achaparro/liferay-portal/blob/master/modules/apps/asset/asset-publisher-web/src/main/java/com/liferay/asset/publisher/web/internal/upgrade/AssetPublisherWebUpgrade.java#L55

As you can see after reaching 1.0.2, there is no path to reach 1.2.0

I will fix these issues in a separate LPS and I will send this pull once they are solved.

Cheers!

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66214. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66222. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
