### PR TITLE
Lps 106145

### PR DESCRIPTION
**Pull request by SamZiemer**
@achaparro,

I ran the semantic version command locally, but there were not any changes. If this pull fails with a Semver error, I'll update it and retest.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevat

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82800.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82801.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82803. [See changes here.](https://github.com/achaparro/liferay-portal/compare/453842cdabde~1...453842cdabde)

**Pull request closed without merging**
