### PR TITLE
LPS-99973,LPS-89065

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-99973
https://issues.liferay.com/browse/LPS-89065

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hey @ryannealeigh,

There are some issues in SF and tests. It seems that we don't need this anymore:
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/asset/service.xml#L103

And also, we are removing some methods that they are used here:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-categories-service/src/main/java/com/liferay/asset/categories/internal/service/AssetEntryAssetCategoryRelAssetCategoryLocalServiceWrapper.java#L60

Can you check it?

Thanks.

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Pull request closed without merging**
