### PR TITLE
LPS-139166 Add integrations tests for LPS-138029

### PR DESCRIPTION
**Pull request by kevhlee**
**Tickets:**
<https://issues.liferay.com/browse/LPS-139166>
<https://issues.liferay.com/browse/LPS-138029>

**Notes:**
In general, the integration tests do the following:

- Check if tables are sorted by initial number of rows (or by name if initial rows are equal).
- Verify that tables that are empty before and after upgrade are excluded.
- Verify that upgrade report catches changes in number of rows.

Let me know if anything should be changed.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Looks like the issue with liferay-continuous-integration is affecting other engineers: <https://liferay.slack.com/archives/C19PWQ74J/p1631713017084700>.

**Comment by michaelhashimoto** [comment]
ci:test:relevant

@kevhlee - I retriggered this pull request.

**Comment by kevhlee** [comment]
Thanks, @michaelhashimoto!

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
These two tests keep failing:
* `com.liferay.portal.osgi.debug.spring.extender.test.SpringExtenderDependencyManagerTest.classMethod`
* `com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest.classMethod`

I ran these tests on my machine with and without the changes. They passed on my machine so I'm not sure what's happening here. I'll run the tests again to check.

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:reevaluate:1207401_9470

**Comment by kevhlee** [comment]
Redirecting pull to Sam.

**Pull request closed without merging**
