### PR TITLE
LPS-102810 SF

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @achaparro, 

I used the latest master to format your pull.

Please check this commit: [LPS-102810 Auto SF](https://github.com/achaparro/liferay-portal/commit/116e2f40693c66b8b75d335a796e5b45f1f3a527)

Thanks.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
cc: @hhuijser

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
cc: @nhpatt

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79992.

**Comment by achaparro** [comment]
Thanks for the quick response @ling-alan-huang

**Pull request closed without merging**
