### PR TITLE
Lps 128860

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-128860

Hi @achaparro, 

I've updated the branch a little bit to remove the SF commit and I added a portal property to create control the new behavior. Let me know if you have any concerns otherwise I think we can send this forward.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
@achaparro, The SF failure does not appear to be related to the property I added. When I run SF on my branch locally I do not get the error, and I see it mentions "jsp.engine." which is nothing like what I added.

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @SamZiemer,

Yes, the SF error seems unrelated but you didn't run baseline for this pull request again and that's causing the semver issue.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/932. [See changes here.](https://github.com/achaparro/liferay-portal/compare/cc8e0b59b769~3...cc8e0b59b769)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/933. [See changes here.](https://github.com/achaparro/liferay-portal/compare/cc8e0b59b769~3...cc8e0b59b769)

**Pull request closed without merging**
