### PR TITLE
Pr 690

### PR DESCRIPTION
**Pull request by SamZiemer**
My tests did not pass locally, but I am going to try here in case something on my end is messed up.

The only thing I can find that looked wrong was the properties we use in the test were not changed after https://github.com/achaparro/liferay-portal/commit/9990030834dc31ae602cdd80ddb3ddb66ecc9509

I changed them to the proper properties, but the tests still do not pass locally.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/samziemer/liferay-portal/pull/757. [See changes here.](https://github.com/achaparro/liferay-portal/compare/201e761de72c~2...201e761de72c)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/samziemer/liferay-portal/pull/758. [See changes here.](https://github.com/achaparro/liferay-portal/compare/f15530f65a85~3...f15530f65a85)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/93892. [See changes here.](https://github.com/achaparro/liferay-portal/compare/927b1b4346a8~3...927b1b4346a8)

**Pull request closed without merging**
