### PR TITLE
LPS-109116 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-109116

### CODE REVIEW

**Comment by kyle-miho** [comment]
Tested on both SQLServer2019 and SQLServer2017. One thing we should note is that SQLServer2019 is much faster than SQLServer2017, Running DBInspectorTest on 2019 took ~4 seconds while ~55 on 2017.

**Comment by kyle-miho** [comment]
You can check the _SQL_SERVER template to notice that the datatypes being added didnt really match what we had previously. DBInspectorTest is a pretty accurate test to use as a model, since it calls runSQL(), its very likely that this is what types are normally generated when creating SQL tables.

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85293.

**Pull request closed without merging**
