### PR TITLE
LPS-117402 Upgrade Group table according to LPS-86236

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hey @arthurchan35,

I think this class does the logic you need, right?
https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/upgrade/BaseUpgradeStagingGroupTypeSettings.java

If so, please, use the base class since we got performance issues when doing the replace in a single query having a huge number of Layout records.

Thanks.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
Hi @achaparro 
Thanks for letting me know! Didnt know such class existed.
I am reusing this pull, and new commit is under ci test

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
Thank you @arthurchan35

**Pull request closed without merging**
