### PR TITLE
LPS-119275 Add a CAST_TEXT to preferences column to avoid problems with SYBASE database

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-119275

Regression caused by the upgrade added in https://issues.liferay.com/browse/LPS-118902

It seems it is a SYBASE limitation that is solved adding a CAST_TEXT to the preferences column.

I have applied same solution than https://issues.liferay.com/browse/LPS-95571

/cc @ricardocousolr

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hey @jorgediaz-lr, @ricardocousolr

In LPS-105530 we had to rollback one of the commits from LPS-95571 because it was failing in DB2. I am not sure why exactly? Do you know more about that and if that can apply to this case?

Thanks.

**Comment by jorgediaz-lr** [comment]
Hi @achaparro 

I didn't noticed LPS-105530 regression. It seems applying CAST_TEXT to every database is a bad idea.

I have send you a new PR using DBTypeToSQLMap, see: https://github.com/achaparro/liferay-portal/pull/685

Regards,
Jorge

**Pull request closed without merging**
