### PR TITLE
LPS-161695: initialize the Release for web modules

### PR DESCRIPTION
**Pull request by qz1010**

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @qz1010,

It looks really good to me, in fact, you catch an issue:
https://github.com/achaparro/liferay-portal/pull/1038/files#diff-23b8029468c570ca027b8c9c08a0b989a4ef7fcd587356f2a7968d6f3d512e51R39

You can move forward with it.

Thank you!

**Comment by ling-alan-huang** [comment]
@qz1010 I made some changes, can you have a look at it?
https://github.com/qz1010/liferay-portal/pull/26

**Comment by ling-alan-huang** [comment]
ci:close

**Comment by ling-alan-huang** [comment]
@achaparro Should we also apply this check to 7.x?
If yes, I will send the fixes for them before sending this SF changes.

**Comment by achaparro** [comment]
Hi @ling-alan-huang,

This only applies to master, so no need to send to 7.x

Thank you!

**Pull request closed without merging**
