### PR TITLE
LPS-110555 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-110555

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
Max Length was the cause, I couldn't find a clear answer online on why so, but using the recommended URL type should be big enough for their usecase

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/398.

**Pull request closed without merging**
