### PR TITLE
LPS-99014 Use batch update for the different locales instead of one by one execution

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hey @achaparro, could you please take a look?
I don't see any other ways to improve the performance of this upgrade because anyway it is an iteration through the whole JournalArticle table, no way to avoid it.
Any thoughts?

Thanks!

**Comment by achaparro** [comment]
Hey @pavel-savinov,

Sorry for the late reply but I was on vacation until today. I will check early this week and I will let you know.

Thanks!

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @pavel-savinov,

I have reviewed your changes and they can be beneficial in those cases where you have more than 4 or 5 locales. However, the tests were made with one single locale so I don't why the QA Engineer didn't get a better result after previous changes implemented by @jonathanmccann. For that reason I have asked the QA Engineer for the conditions used to execute the tests:
https://issues.liferay.com/browse/LPS-99014?focusedCommentId=1971763&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1971763

Let's wait for his answer.

Best regards.

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81049. [See changes here.](https://github.com/achaparro/liferay-portal/compare/4c77fedcf9a9~1...4c77fedcf9a9)

**Pull request closed without merging**
