### PR TITLE
LPS 86764

### PR DESCRIPTION
**Pull request by achaparro**
Good job @kevhlee!

Just a few questions regarding the changes:
- I noticed that you din't remove some logic to add the Release like in this case: https://github.com/liferay/liferay-portal/blob/master/modules/apps/archived/chat-web/src/main/java/com/liferay/chat/web/internal/upgrade/ChatWebUpgrade.java#L37 I guess it is because those modules were plugins before so we still need to check if the portlet existed before, is that right?
- I added a commit with some missing changes https://github.com/achaparro/liferay-portal/pull/983/commits/2e4b788a79f0f542fc40d6c8cf3e55e1dfa715c9, didn't you modify them for any reason? I just want to be sure that we can change them.

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:reevaluate:1187401_6119

**Comment by kevhlee** [comment]
Hi @achaparro,

I did see those modules but I didn't change the upgrade paths for them because they are considered archived.

**Comment by achaparro** [comment]
@kevhlee I think it is fine how it is right now if they are archived

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hi @achaparro,

For the ones you changed in your new commit <https://github.com/achaparro/liferay-portal/pull/983/commits/2e4b788a79f0f542fc40d6c8cf3e55e1dfa715c9>, I didn't see those simply because I was only looking at the startup logs as reference. For some reason, I didn't see upgrades from those modules execute on startup.

**Comment by achaparro** [comment]
Ok @kevhlee, probably it is because there were customized upgrade processes that didn't print any stack trace.

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
Hi @vicnate5, can you help us to check if these tests are failing in other pull requests?

Thanks.

**Comment by achaparro** [comment]
ci:forward

**Comment by koor4356** [comment]
@achaparro @kevhlee  @vicnate5, 
everything is looking good but except for this error on the PR: Can take a look?

`com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest > testWronglyLocalizedSiteLayoutPrivateFriendlyURL1 FAILED
     [exec]     org.junit.ComparisonFailure: expected:</[en/]group/enzdqltl/home> but was:</[]group/enzdqltl/home>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest._assertLocalizedSiteLayoutFriendlyURL(PortalImplLocalizedFriendlyURLTest.java:645)
     [exec]     	at com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest._testWronglyLocalizedSiteLayoutFriendlyURL(PortalImplLocalizedFriendlyURLTest.java:827)
     [exec]     	at com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest.testWronglyLocalizedSiteLayoutPrivateFriendlyURL1(PortalImplLocalizedFriendlyURLTest.java:359)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)`


https://testray.liferay.com/home/-/testray/case_results/1553862957?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1553860979%26testrayRunId%3D1553861208%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

**Comment by achaparro** [comment]
Hi @kevhlee,

Do you think it can be related? Can you try to reproduce it locally?

Thanks.

**Comment by kevhlee** [comment]
Hi @achaparro, @koor4356,

The changes shouldn't make that particular test fail. I ran `com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest` locally with and without the changes. The tests passed in both instances.

**Comment by koor4356** [comment]
Thank you @kevhlee, This PR is good since the mentioned issue is not related.

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
ci:reevaluate:1307401_308

**Comment by vicnate5** [comment]
@achaparro This is good, can be manually forwarded.

**Comment by achaparro** [comment]
thanks @vicnate5, resent:
https://github.com/brianchandotcom/liferay-portal/pull/105824

**Pull request closed without merging**
