### PR TITLE
Lps 111719

### PR DESCRIPTION
**Pull request by SamZiemer**
Hello @achaparro,

As we discussed this fix updates the existing records related to a subscription rather than creating new ones. This keeps all of the original data the same, the only thing that changes now is the classNameId. We have kept the deletion method since there could be some customers who have used the old method to upgrade discussion class names but did not get to the deletion step yet.

I did test out moving this to a more appropriate module, but I don't believe that is going to work without additional changes to the class and I thought it would be better to do fewer changes to this class as it has already proven to have many issues in the past. This may be one of the cases where we need to make an exception for a module accessing other module's tabes.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hey  @vicnate5,

Do you know if the tests in the CI are stable? We are getting more failures than in the first try.

Thanks.

**Comment by vicnate5** [comment]
@achaparro @SamZiemer Looks like a real problem here. Portal does not start

```
ERROR [Portal Dependency Manager Component Executor--1][UpgradeStepRegistratorTracker:144] Failed upgrade process for module com.liferay.comment.page.comments.web
com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.subscription' doesn't exist
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:109)
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:127)
	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeInfosRunnable.run(UpgradeExecutor.java:200)
	at com.liferay.portal.output.stream.container.internal.OutputStreamContainerFactoryTrackerImpl.runWithSwappedLog(OutputStreamContainerFactoryTrackerImpl.java:134)
	at com.liferay.portal.upgrade.internal.executor.SwappedLogExecutor.execute(SwappedLogExecutor.java:51)
	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:155)
	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:118)
	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:137)
	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:86)
```
https://testray.liferay.com/reports/production/logs/test-1-5/1587175387105/test-portal-acceptance-pullrequest(master)/6633/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/liferay-log.txt.gz

**Comment by achaparro** [comment]
Thanks @vicnate5 

@SamZiemer can you take care of it? Thx

**Comment by vicnate5** [comment]
ci:stop

**Comment by SamZiemer** [comment]
Thanks @vicnate5,

Do you have a link to the DB backup that caused this error? In my own testing, I was not seeing this when upgrading.

**Comment by vicnate5** [comment]
Sent DM to Sam with db backup

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by SamZiemer** [comment]
Thanks @vicnate5  and @achaparro I've updated the fix with proper capitalization. my own testing was passing due to my own MySQL configurations.

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Looks good now @SamZiemer! thanks, I will execute relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/560. [See changes here.](https://github.com/achaparro/liferay-portal/compare/403e0d96c73b~7...403e0d96c73b)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/562. [See changes here.](https://github.com/achaparro/liferay-portal/compare/d104f77f8234~7...d104f77f8234)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/563. [See changes here.](https://github.com/achaparro/liferay-portal/compare/965b0c5498d9~7...965b0c5498d9)

**Pull request closed without merging**
