### PR TITLE
Lps 121639

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPP-38865
https://issues.liferay.com/browse/LPS-121639

Hi @achaparro,

The issue here is when the reports service module gets registered, we check if the ResourceActions are present in the database, and if not, we add them. Later, when we are upgrading we attempt to rename the old className during the upgradeKernelpackage upgrade, this causes the duplicate entry exception.

This fix for the most part copies some [existing solutions](https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-service/src/main/java/com/liferay/calendar/internal/upgrade/v1_0_4/UpgradeClassNames.java#L109-L133) to this same problem for other modules with a few changes to adapt it to the reports module.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hey @SamZiemer,

Do you think this parameter "preventDuplicates" could do the same?
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/upgrade/v7_0_0/UpgradeKernelPackage.java#L185

Can we apply the preventDuplicates to true to all modules or only this one?

Also, what do you think this didn't happen before? My guess is that customer started the portal 7.2 before the upgrade and then the records were created, do you think that's feasible? Do you reproduce it without starting the module before the upgrade? (step 6 and 7 in the LPS)?

Thanks!

**Comment by SamZiemer** [comment]
Hey @achaparro,

This happened when upgrading directly without starting the bundle first. I tested reproducing the error both with and without step 6 and 7, those are not required to start the issue. The ResourceActions are created when registering the module service lifecycle during [_upgradeModules](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/tools/DBUpgrader.java#L297)

As for setting preventDuplicates to true globally, I did not look into that possibility as I did not know what other issues that could lead to. Since the customer is in somewhat of a hurry, I wanted to focus on the module they are getting errors with for now. This could be an option for us to invest some time to determine if preventing duplicates should be set for all modules.

If you would prefer, I can override the doUpgrade to change preventDuplicates to true for the ResourceAction table.

**Comment by SamZiemer** [comment]
Resent here with changes we've discussed: https://github.com/achaparro/liferay-portal/pull/721

**Pull request closed without merging**
