### PR TITLE
LPS-86291

### PR DESCRIPTION
**Pull request by jcampoy**
Here it is the upgrade for dates in SQLServer in the Forms & Workflow modules. I am going to send a similar pull request for master-private. /cc @rafaprax @jeyvison

### CODE REVIEW

**Comment by jcampoy** [comment]
Failures unique to this pull will be fixed by https://github.com/achaparro/liferay-portal-ee/pull/46

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64733. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64735. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
