### PR TITLE
Lps 113771

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-113771

Hello @achaparro,

The issue in this ticket is in 7.0 we add validation to data definition objects but we do not fill it with anything. During the upgrade that validation string is turned from this:

"validation":{}

to this:

"validation":{"expression":{"name":"","value":""},"parameter":{},"errorMessage":{}}

Post upgrade, when adding a new record to the DDL using that definition, the validation express fails to compile and throws an exception. In 7.2 and master, when creating a DDL, if there is no validation added in the definition, then it is not added to the definition string stored in the database. Let me know if you have any questions.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hi @SamZiemer,

I have been doing some research and I think this module is not the proper place to execute the upgrade. We should do it in the DDMServiceUpgrade. Apart from that, we are missing to update the table DDMStructureVersion too (maybe other tables too?)

In the DDMServiceUpgrade we have other similar upgrades, for example:
- com.liferay.dynamic.data.mapping.internal.upgrade.v1_1_0.UpgradeDDMStructure
- com.liferay.dynamic.data.mapping.internal.upgrade.v1_1_1.UpgradeDDMFormFieldSettings
- com.liferay.dynamic.data.mapping.internal.upgrade.v1_1_2.UpgradeDynamicDataMapping
- com.liferay.dynamic.data.mapping.internal.upgrade.v2_0_5.UpgradeDDMFormFieldValidation

In fact, the string "validation":{"expression":{"name":"","value":""},"parameter":{},"errorMessage":{}} is added in:
com.liferay.dynamic.data.mapping.internal.upgrade.v1_1_0.UpgradeDDMStructure#updateDefinition

Taking this into account, I think we should:
1. Understand why we are adding that validation at that point. I think this is important because we are using this class DDMFormSerializerSerializeResponse and we are not sure if that class is called somehow during the regular use of that portlet in 7.2 or master. 
2. Depending on the previous point, decide where to do the modification. If it's something which only happens with DDL and required fields maybe we can just modify the current upgrade processes. If we consider that it's more problematic, analyze how to implement it trying to reuse the current logic we already have to modify the DDMStructures. To make this decision it can be interesting to to know the expected behaviour in 7.1 too.

Please, review that and we can talk tomorrow about it.

Thanks.

**Pull request closed without merging**
