### PR TITLE
LPS-73266 create a couple of OSGi commands to provide information about verify executions.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:open

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
I've added a couple of commands to provide more information either to the user or for debugging purposes. Feel free to remove last two commits if you don't consider them useful.

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51095. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
