### PR TITLE
Lps 88135 2

### PR DESCRIPTION
**Pull request by balazssk**
Hi @achaparro ,

Thank you for your help on https://github.com/achaparro/liferay-portal/pull/261

I implemented what we discussed:
Removed the updateGroup from the Uninstanceable branch
and simplified how updateGroup works.

One question came up: even though the number of users upgrading to 7.1 is small at the moment, what can we do for them to ensure their db will be corrected?

Thanks

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66792. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hey @balazssk,

Regarding your question:

> One question came up: even though the number of users upgrading to 7.1 is small at the moment, what can we do for them to ensure their db will be corrected?

Let me answer you tomorrow, I have to do a test to answer properly.

Thanks.

**Comment by balazssk** [comment]
Thanks!

**Pull request closed without merging**
