### PR TITLE
Lps 107322

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83680. [See changes here.](https://github.com/achaparro/liferay-portal/compare/ebe9fe6aa35e~2...ebe9fe6aa35e)

**Pull request closed without merging**
