### PR TITLE
Lps 128860

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-128860

Hi Alberto, here is the renamed log interceptor. I do wonder if we should remove the changes to UpgradeClient.java and add those later when we do the actual report generation part of this epic, but I wanted to include them in this PR incase we wanted to keep them here.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:stop

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/927. [See changes here.](https://github.com/achaparro/liferay-portal/compare/394b681dbe0f~1...394b681dbe0f)

**Pull request closed without merging**
