### PR TITLE
LPS-129559 Shopping tables may exist without the shopping module info in Release_

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi @achaparro, could you please review these changes? I'm not sure it is completely safe to try to delete, in general, non-registered  (in release_ table) modules data, but as you can check some tables may still exist.

Please let me know your thoughts.

Thank you.

**Comment by achaparro** [comment]
Hi @crodriguezy,

I have been checking why the release records weren't added for the shopping portlet and the reason is that we created a shopping module with its upgrade processes that generated that record but we removed the module in 7.2.x! After removing it, the release record is not created, and hence, the tables can't be removed before your changes.

For that reason, your modifications make total sense. I am thinking about applying to the rest of the cases since we can end having the same case.

Once I make a decision I will resend to Brian.

Thanks Cristina!

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/907. [See changes here.](https://github.com/achaparro/liferay-portal/compare/5bb06212fda2~2...5bb06212fda2)

**Pull request closed without merging**
