### PR TITLE
LPS-109105 More log info

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@achaparro Only 2 failure logs seen here so far, they are different errors.
https://testray.liferay.com/reports/production/logs/test-1-7/1582324757310/test-portal-acceptance-pullrequest(master)/4915/functional-upgrade-jboss71-mysql57-jdk8/0/0/liferay-log.txt.gz
https://testray.liferay.com/reports/production/logs/test-1-14/1582333836989/test-portal-acceptance-pullrequest(master)/5544/functional-upgrade-jboss71-mysql57-jdk8/0/0/liferay-log.txt.gz

**Comment by vicnate5** [comment]
Most recent failure at head: https://testray.liferay.com/reports/production/logs/test-1-6/1582540282169/test-portal-acceptance-pullrequest(master)/5624/functional-upgrade-tomcat90-mysql57-jdk8/2/0/liferay-log.txt.gz

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@achaparro We hit a rebase conflict and this is not proving to be helpful in reproducing the issue. I do have a lot of examples from upstream runs if you need. Any other way I can help us catch this?

**Pull request closed without merging**
