### PR TITLE
LPS-120146 Archived modules upgrade need to be moved out of the archi…

### PR DESCRIPTION
**Pull request by SamZiemer**
I think this is the best place to move the archived-modules-upgrade to. I looked into moving it to core or dxp, but I don't think it fits in either of those categories.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
@SamZiemer

The SF didn't pass, can you check it?

Also, is it possible to change the name of the apps without modifying the keys? I don't why we used the words upgrade and module because it's not related to the upgrade and we can remove other things, not only modules.

Please, contact me in Slack to talk about a proposal.

Thx

**Pull request closed without merging**
