### PR TITLE
[TS] LPS-117568 Check also templateKey = '' because some databases as SQL Server need it

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-117568

Hi @achaparro 

I have added the `templateKey = ''` condition to the update as you said in https://github.com/achaparro/liferay-portal-ee/pull/70#issuecomment-669597962

We haven't sent this LPS to any customer and we haven't backported it yet, so I don't think it worth creating a different LPS to fix this.

Can you review this minor change and forward it to Brian?

Thank you,
Jorge

/cc: @leoadb

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/681. [See changes here.](https://github.com/achaparro/liferay-portal/compare/3a787764232f~1...3a787764232f)

**Pull request closed without merging**
